### ISSUE TITLE
Move existing code into this repo

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#1]
## Problem

Currently we have Waku (https://specs.vac.dev/specs/waku/waku.html) code in a few different places:

- Wakunode in Nimbus: https://github.com/status-im/nimbus/tree/master/waku with CLI app, RPC (https://github.com/status-im/nimbus/blob/master/nimbus/rpc/waku.nim) and simulation.

- Protocol implementation in nim-eth as RLPx subprotocol in DevP2P: https://github.com/status-im/nim-eth/tree/master/eth/p2p/rlpx_protocols

For Waku version 2, we'd like to move it over to libp2p. This means pieces are spread in various places that don't accurately reflect what Waku is as a protocol/"app" or how to make changes to it.

Additionally, we'd like to lower the barrier to entry for people who purely want to run Waku, and e.g. interact with it via JSON-RPC.

## Proposed Solution

A bit like nim-beacon-chain is a standalone repo using both Nimbus, nim-libp2p and nim-eth, structure things as follows:

![image](https://user-images.githubusercontent.com/1552237/80450300-d2ca8500-8953-11ea-96a5-33beb41b5d13.png)

To start with, move over Waku stuff from Nimbus to here.

## Acceptance criteria

- Can easily run Waku node from individual git checkout
- Can easily develop against both devp2p and libp2p
- Don't throw away existing v1 code, but instead keep it around and augment with v2 namespace

**Comment by oskarth** [comment]
cc @kdeme  @status-im/status-protocol

**Comment by oskarth** [comment]
@kdeme Is there anything else you want to do for this issue or should we close it?

Main thing I can think of are:
- remove code from other repos
- update references in other places (specs, etc)
- move tests to namespaces
- create any lingering follow up issues

**Comment by kdeme** [comment]
Code has been removed from other repos & tests moved under general v1 namespace.
Before closing this I want to move the readme file to top level and adjust it a bit.

**Comment by kdeme** [comment]
I think that after https://github.com/status-im/nim-waku/pull/9 and https://github.com/vacp2p/specs/pull/120  this can be closed.
