### ISSUE TITLE
Node deployment plan

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-waku#10]
Figure out a deployment plan for https://github.com/status-im/infra-nimbus/issues/13

Something like:

* Run single node in test
* Take over existing nodes in test
* Run single node in prod
* Take over existing nodes in prod

**Comment by oskarth** [comment]
Just a note to make sure we are deliberate about it: Currently in https://github.com/status-im/nim-waku/blob/master/Makefile#L18 insecure flag is enabled, which means we'll expose a HTTP server for metrics etc. For prod we want to make sure we don't use it I believe.

cc @jakubgs in case you aren't aware of it.

**Comment by jakubgs** [comment]
Why would we not want to use it?

**Comment by kdeme** [comment]
I believe the `-d:insecure` flag comes rather from the used HTTP server implementation than the actual exposing of an HTTP server endpoint itself. Of course the latter also has security related concerns, which is why it is defaulted to localhost. 

See also https://github.com/status-im/nimbus/issues/358 and discussion linked in it.

**Comment by jakubgs** [comment]
I don't see the issue with the metrics endpoint, since it's just localhost.

Not sure about other implications of `-d:insecure` tho.

**Comment by stefantalpalaru** [comment]
> Not sure about other implications of `-d:insecure` tho.

There are no others. The Nim stdlib HTTP server is considered buggy and therefore "insecure". That's all there is to it.

**Comment by jakubgs** [comment]
Well, then we should not care about it in the slightest, since metrics endpoint is not public. All ports on our hosts are closed for incoming connections unless explicitly opened in `iptables`.
