### ISSUE TITLE
 Waku v2 protocol - filter: Implement basic `vac/waku/filter` protocol

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#100]
Should be mounted onto Waku node and implement basic req/resp RPC.

MAY use a similar req/resp mechanism as `store` protocol.

https://github.com/vacp2p/specs/issues/171

## Acceptance criteria

- Direct wire exchange, a la req-resp or push
- Mounted on node
- Hooked up to node API
- Proven to work in some end to end fashion (simulation, test, command line commands, example, etc)

## Note
This issue may be broken down into smaller issues.

**Comment by decanus** [comment]
@oskarth can you link spec issue.

**Comment by oskarth** [comment]
https://github.com/vacp2p/specs/issues/171 but needs to be filled out in more detail

**Comment by decanus** [comment]
So @oskarth from my understanding this endpoint would allow a peer to keep a connection open to listen to messages in a specific topic that a peer receives, right?

**Comment by oskarth** [comment]
Updated issue. Merged existing partial work. Please break it down appropriately as discussed yesterday on call @decanus.

**Comment by oskarth** [comment]
@decanus where are the other issues? please link them in this before closing so one can follow the trail...

**Comment by decanus** [comment]
- https://github.com/status-im/nim-waku/issues/129
- https://github.com/status-im/nim-waku/issues/124
