### ISSUE TITLE
Waku v2: Store Protocol Improvements

### ISSUE THREAD

**Issue by decanus** [status-im/nim-waku#109]
The store protocol is currently very basic, it allows retrieving all messages that are in a specific topic. However to be efficient we should be able to query more specifically.

This includes things such as:
 - pagination (limit, from, etc)
 - time based bounds, for all messages before or after a specific time or in between a given range.

**Comment by oskarth** [comment]
This seems to be missing a spec issue @decanus

**Comment by decanus** [comment]
@oskarth https://github.com/vacp2p/specs/issues/193
