### ISSUE TITLE
Waku v2: Filter protocol - Mount it on node

### ISSUE THREAD

**Issue by decanus** [status-im/nim-waku#124]
The waku filter protocol is mounted on the node.

...and works.

**Comment by oskarth** [comment]
This is one of the issues, where are the others? Req-resp, node api integration...

**Comment by decanus** [comment]
Not sure what we mean by req-resp for this scenario, maybe I missed that.

**Comment by oskarth** [comment]
It is in the original issue, it was talked in the PR, and we talked about it for a long time in the Vac PM call... what do you mean ?

**Comment by oskarth** [comment]
So where is that req resp issue?

**Comment by oskarth** [comment]
@decanus if this issue is blocked by some other issue, please mark it as such. Though I can't really tell how it would be blocked. What's the problem exactly?
