### ISSUE TITLE
Waku v2: Filter protocol - Node API integration

### ISSUE THREAD

**Issue by decanus** [status-im/nim-waku#129]
the Waku filter protocol is currently not integrated into the node api, however it should be.

**Acceptance Criteria**
 - The Filter protocol is mounted on the node
 - The Filter protocol can be called to subscribe to other nodes.
 - Basic tests written.
 - Docs updated: https://github.com/status-im/nim-waku/blob/master/docs/api/v2/node.md

**Comment by oskarth** [comment]
Please add this to the board.

**Comment by oskarth** [comment]
What's happening with this?

**Comment by oskarth** [comment]
What is the status of this?

**Comment by oskarth** [comment]
Issue been open for too long with unclear progress, acceptance criteria fuzzy. Removing.

**Comment by decanus** [comment]
@oskarth added some acceptance criteria

**Comment by oskarth** [comment]
Ok seems fine, I moved it to In progress on board

**Comment by oskarth** [comment]
@decanus where is the updated proposed signature and acceptance criteria here that we talked about?
