### ISSUE TITLE
Deploy a single wakunode2 into cluster

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#144]
For Nagang testnet (https://github.com/vacp2p/research/issues/43) we want to deploy a single, publicly connectable wakunode.

```
# 1. Build
make wakunode2

# 2. Deploy to some server, ensure port 60000 is open

# 3. Note the listen address, i.e.
# Note the "listening on address" in logs.
# :/ip4/0.0.0.0/tcp/60000/p2p/16Uiu2HAmF4tuht6fmna6uDqoSMgFqhUrdaVR6VQRyGr6sCpfS2jp
```

## Acceptance criteria

1. Publicly connectable Waku v2 wakunode2 deployed, with a known address.
2. Ideally some simple way of deploying an updated version.

For now only a single node in any location is sufficient. We can scale it up from there with static node connections, metrics etc, etc.

---

@jakubgs is this something you can assist with?

(Alternatively, we can also do this on an ad hoc VPS for now)

**Comment by jakubgs** [comment]
Adjustment for `Dockefile`: https://github.com/status-im/nim-waku/pull/145

**Comment by jakubgs** [comment]
The host is `node-01.do-ams3.wakuv2.test.statusim.net`.

Change: https://github.com/status-im/infra-nim-waku/commit/4c186cb8

**Comment by oskarth** [comment]
Awesome cheers!

**Comment by oskarth** [comment]
@jakubgs Two questions:

1. Where can one see the logs? E.g. `Listening on ....` address. It should look something like `/ip4/0.0.0.0/tcp/60000/p2p/16Uiu2HAmGviKxh3Ky2Gh9vACdDTi5zVyraZr4ncwnz66MFtji2be`. I'm not 100% how smart multiaddress is with DNS resolution etc.

2. If we need to update the binary, what does the flow look like?

**Comment by jakubgs** [comment]
If you ssh into the host (or [just check the changes I made]()) you can see the Docker tag used:
```

**Comment by oskarth** [comment]
`oskarth@node-01.do-ams3.wakuv2.test.statusim.net: Permission denied (publickey).`

```
> cat ~/.dotfiles/private/ssh_keys/id_rsa.pub 
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCrMTsMLpwvGsVAFz1i3T2Pf3STCe8hGCS7QcfU27GGEFbM02qm62j4upk7HLJxgc//LiX1S7ZDmWewLD0/afg/TXOdCjg6o+IC/viI5Ik2nMhK0SqFnXyqZC92YgOci3dMlwEjsCsdKTd3Z4l15bIBR8Cb4IjrWvi9/A/bixeMFQwJTAijYuY4p4fPrLzZ2TEh/l8SHTdGn3pcVekk3VpCBmSOvIzn5ED0ta5b4Pqvuwxx9TYXdlyalHsGmDx26R77jRWe2F+a+Z7KE+NUiTSFn8GNJ6HXA2dZ6ii7YAOd0FfMJjCk273vM8iIiA0pLUXO5d3qfZcTbfxEb0RQ+MRHFhA3yjDOqSODPNZU+2sXJXheZa/q21HUO552I0iszh0JsLzAuokzaRCtcSgfmbUUNYh0HJc6Sn0nmKFu9j57e69mkFdJsDSGT4+WJefz8RyXz7gPzYg5lCXw0iR7gYJqHhxA3bsCaJbUni5RZ0NlTkZ1bMzDr9Es/2/VjKmrWtjeXiGg/plvfdpJs8ExTP9PwbtAXrQmVxQq4bj6U2TLUDZR6jycaQZMx4RxSsNSHroxmveh73GlijgyxRuYvghM3XoSx6EyYTziwPUHyfoGyoUgFBbcNJgsmnvUu57Fb0ovZr/PiubhHwyb7EcooY/Afu78J8JoaMCzKPuU6GvqdQ== ot@oskarthoren.com 2019-05-03 (x1c1)
```

**Comment by jakubgs** [comment]
```
admin@node-01.do-ams3.wakuv2.test:~ % sudo cat /home/oskar/.ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDQ5/9yNF35OcnhsXtWHOdnPG5JYS2l/hJ34+2/zxJQSGa/akCou6UNckY5/FOD+boTF9dAZ7i9Fm6OXqKSBf9s6NMrBz+q3zT46SAqrEoq4ln2bBtpDoJxWwkrSRsGN/uml/fn7JaYW8GgCZQ0vTKcSH2r27k9LlSgrx/Z7D0ktOO0flzw+K0Ly/SbAWysK2NySZpOh5TdfrM/PFiLgV1Qd1FuaxyrZz9ELkLnIrvwYuzvp3twA8aPhIT4wR4z6MUVwl9O9/I8Fi9ckozGbsmynFmMtlaYiBotZm0dv2uSWk6caoKSn+vXccPc5X0tqmk7rLFU292Ey9QbREqaiAJ8oBkeUI6lhWS3F8xvUWTaesXnwRL/doDbUFK3/K32eSuzotdyJnd3ujTcYG+1eVwepYjlSAf3e9OgeEGCxXcqyIQr4Qa2btMcY9rHDQxoUSpcUCGC9IgoPKHBUGXQUqsJphw8wYSntWOY4/a7WEryfVuQfyxxWLK9PrwJ4b5UvupO1IJUBFTma8CJirWlXJBRnQe3Ylfnjs94mz0BmzfQ4mMWb+xjIkPEijrSzJRYWbFkyNZNFm+ixXWJ5Jtrz3sbNKr5a6NNng5YLmeRfCZk7CtpVORaFbwdARrqbRjdfBYNc7gHSrOyAEJ9ON3gIAiLxF2aHu+RbeU/FznzkmqWCQ== oskar@status.im
```
