### ISSUE TITLE
Nangang: Unable to connect to cluster node

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#147]
# Problem

I want to add the Waku v2 cluster node to my static node list and connect to it.

It isn't clear to me what the multiaddress is. The most naive attempt is something like: `./build/wakunode2 --ports-shift:0 --staticnode:/dns4/node-01.do-ams3.wakuv2.test.statusim.net/tcp/60000` which doesn't work.

See https://github.com/status-im/nim-waku/issues/144#issuecomment-689973292

## Notes

If we have logs it is easy to see what the listen address, though there might be some gotchas here with DNS, external IP etc.

## Acceptance criteria

Can successfully connect to Wakuv2 node in cluster from local machine.

cc @jakubgs @kdeme

**Comment by jakubgs** [comment]
You hate two ways of checking the logs for that service:

1. SSH into the host and check the logs in `/var/log/docker/nim-waku-node` ([you do have access](https://github.com/status-im/infra-role-bootstrap/blob/13a7524fde5a34e3fd62308c3687e966d7705cfa/defaults/main.yml#L97))
2. Use Kibana to browse the logs for the service [like so](https://kibana.status.im/goto/a3c0bad8982f6ce1d68f50742ef66cc8).

**Comment by oskarth** [comment]
Thanks, looking at logs I can get the nodeid and this works:

`./build/wakunode2 --ports-shift:0 --staticnode:/ip4/134.209.139.210/tcp/60000/p2p/16Uiu2HAmJb2e28qLXxT5kZxVUUoJt72EMzNGXB47Rxx5hw3q4YjS`

Didn't try publish etc yet
