### ISSUE TITLE
(Cluster) Node should default subscribe to a "waku" topic

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#148]
# Problem

When connecting to the cluster node, it is run by a machine. This means it won't subscribe to Waku node automatically.

This could be a setting where it does this as part of init.

# Acceptance criteria

Node subscribes to "waku" topic by default, possibly with some toggle.

# Notes

See https://github.com/status-im/nim-waku/issues/147 as well.

cc @kdeme @decanus

**Comment by decanus** [comment]
@oskarth will have a look at this

**Comment by oskarth** [comment]
Thanks!

**Comment by oskarth** [comment]
FYI to connect https://github.com/status-im/nim-waku/issues/147#issuecomment-690159389

Once above works locally, you should be able to push a new version to cluster per https://github.com/status-im/nim-waku/issues/144#issuecomment-689998119

**Comment by decanus** [comment]
@oskarth I don't have credentials to connect.
