### ISSUE TITLE
Split up wakunode2 into CLI and API part

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#149]
# Problem

From https://github.com/status-im/nim-waku/issues/143#issuecomment-689971546

> The problem is that you are missing the wakunode2 import. But if you add it, other issues occur as wakunode2 already imports wakurpc. Although it strangely doesn't give the usual cyclic import warning/error.
> 
> Anyhow, I think the application (cli in this case, with rpc, metrics etc.) logic should be separated from the "Waku Node API", similar like in v1. I've already started with the split of the logic itself in previous PR, so should be convenient now. We can also decide to just call it Waku API by the way (and waku.nim alongside).
> 
> This PR #117 paves the road to separate this better.
> E.g. An application that wants to use the Waku Node API does not necessarily want all our wakunode cli application logic such as the RPC calls, metrics, logging, cli config, etc.
> 
> So, we should allow to only import Waku Node API calls, and nothing extra.
> 
> We can do this:
> 
> either by creating two files. Say waku.nim (API calls) and wakunode.nim (CLI application). Or if you want to keep the node name in there, wakunode.nim (API calls) and wakucli.nim (CLI application).
> or by putting the purely application parts (including its imports) under the when isMainModule.
> 
> This would remove also the cyclic import which I'm guessing causing the problem you are seeing.

# Suggested solution

1. Split up wakunode2 into waku.nim (API calls) and wakunode.nim (CLI application).
2. Everything still works

**Comment by dryajov** [comment]
Nim has a notorious issue with cyclic imports (not sure if this is the case you ran into here), but the recommended solution in many cases is to create one or several global `types.nim` packages that have all/most of the types defined there. It's a bit ugly and a hack at best, but it is the only way of solving this types of issues in many cases. With that said, your suggested solution sounds reasonable for now.
