### ISSUE TITLE
Nangang cluster node doesn't inform peer of subscriptions

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#155]
# Problem

Cluster node won't emit subscriptions and thus not be used for relaying messages on `waku` topic.

Node: `/ip4/134.209.139.210/tcp/60000/p2p/16Uiu2HAmJb2e28qLXxT5kZxVUUoJt72EMzNGXB47Rxx5hw3q4YjS`

## Details

Running three nodes locally, two connected to a single relay point one, I can confirm that subscriptions on `waku` topic are relayed by default as per https://github.com/status-im/nim-waku/issues/148. On the edge node I see logs such as:

```
RC 2020-09-14 10:44:55+08:00 read data from peer                        topics="pubsubpeer" tid=8209 file=pubsubpeer.nim:88 data=1a081a060a0477616b75 peer=16Uiu2HAm4SwK7pw9vUCcN3n1XLLvJue3UicXhg5deBkZYedSEkG1
TRC 2020-09-14 10:44:55+08:00 decodeRpcMsg: decoding message             tid=8209 file=protobuf.nim:241 msg=1a081a060a0477616b75
TRC 2020-09-14 10:44:55+08:00 decodeMessages: decoding message           tid=8209 file=protobuf.nim:216
TRC 2020-09-14 10:44:55+08:00 decodeMessages: no messages found          tid=8209 file=protobuf.nim:224
TRC 2020-09-14 10:44:55+08:00 decodeSubscriptions: decoding message      tid=8209 file=protobuf.nim:174
TRC 2020-09-14 10:44:55+08:00 decodeControl: decoding message            tid=8209 file=protobuf.nim:128
TRC 2020-09-14 10:44:55+08:00 decodeGraft: decoding message              tid=8209 file=protobuf.nim:85
TRC 2020-09-14 10:44:55+08:00 decodeGraft: read topicId                  tid=8209 file=protobuf.nim:88 topic_id=waku
```

However, for the cluster node the edge node produces no such output, and sometimes the dial appears to fail too:

```
TRC 2020-09-14 10:38:45+08:00 Dialing peer                               topics="switch" tid=6926 file=switch.nim:251 peer=16Uiu2HAmJb2e28qLXxT5kZxVUUoJt72EMzNGXB47Rxx5hw3q4YjS
TRC 2020-09-14 10:38:45+08:00 Dialing address                            topics="switch" tid=6926 file=switch.nim:255 address=/ip4/134.209.139.210/tcp/60000/p2p/16Uiu2HAmJb2e28qLXxT5kZxVUUoJt72EM
zNGXB47Rxx5hw3q4YjS peer=16Uiu2HAmJb2e28qLXxT5kZxVUUoJt72EMzNGXB47Rxx5hw3q4YjS
TRC 2020-09-14 10:38:45+08:00 dialing remote peer                        topics="tcptransport" tid=6926 file=tcptransport.nim:162 address=/ip4/134.209.139.210/tcp/60000/p2p/16Uiu2HAmJb2e28qLXxT5k
ZxVUUoJt72EMzNGXB47Rxx5hw3q4YjS
INF 2020-09-14 10:38:45+08:00 Post switch dial                           tid=6926 file=wakunode2.nim:194
INF 2020-09-14 10:38:45+08:00 Creating server on                         topics="JSONRPC-HTTP-SERVER" tid=6926 file=httpserver.nim:215 address=127.0.0.1:8548
DBG 2020-09-14 10:38:45+08:00 HTTP RPC server started                    topics="JSONRPC-HTTP-SERVER" tid=6926 file=httpserver.nim:317 address=127.0.0.1:8548
INF 2020-09-14 10:38:45+08:00 RPC Server started                         tid=6926 file=wakunode2.nim:211 ta=127.0.0.1:8548
 
TRC 2020-09-14 10:40:54+08:00 dialing failed                             topics="switch" tid=6926 file=switch.nim:266 exc="(110) Connection timed out"
```

Looking at the cluster node logs:

 https://kibana.status.im/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2020-09-14T02:00:00.000Z',to:now))&_a=(columns:!(message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:d6db7610-60fd-11e9-98fa-2f101d13f938,key:program.keyword,negate:!f,params:(query:docker%2Fnim-waku-node),type:phrase),query:(match_phrase:(program.keyword:docker%2Fnim-waku-node))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:d6db7610-60fd-11e9-98fa-2f101d13f938,key:fleet.keyword,negate:!f,params:(query:wakuv2.test),type:phrase),query:(match_phrase:(fleet.keyword:wakuv2.test)))),index:d6db7610-60fd-11e9-98fa-2f101d13f938,interval:auto,query:(language:kuery,query:''),sort:!())

I see stuff like:

![image](https://user-images.githubusercontent.com/1552237/93038473-ab145900-f677-11ea-8d50-e02f814c6bf4.png)

## Current hypothesis

1) Something related to stability of connection handling in nim-libp2p, which will be fixed when bumping nim-libp2p dep
2) Something related to external IP/NAT punching shenanigans
3) Something else?

## Acceptance criteria

Dial works reliability and subscriptions from cluster nodes are sent to edge node, so it can be used as a relay point.

---

cc @kdeme @decanus and also @dryajov in case you have some insight into this type of problem.

**Comment by oskarth** [comment]
I'll try bumping nim-libp2p as our version is quite old (end of July). Expecting some issues... :p

**Comment by oskarth** [comment]
Could also be related to https://github.com/status-im/nim-libp2p/issues/325

**Comment by decanus** [comment]
@oskarth yeah let's try bumping dependencies. Considering this is still alpha level software we'd probably best trail as closely to master from nim-libp2p as possible.

**Comment by arnetheduck** [comment]
notably, libp2p now has events for connections and disconnections that have been revamped significantly

**Comment by oskarth** [comment]
Seems like the bumping of nim-libp2p and new updated Dockerfile solves it. Can't reproduce.
