### ISSUE TITLE
WakuRelay - Fix FloodSub

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#161]
# Problem

Currently with https://github.com/status-im/nim-waku/pull/157#issuecomment-693150074 only gossipsub mode works. This is likely due to a bug in FloodSub.

It'd be nice to be able to use FloodSub as it is simpler and has less of a surface area for bugs.

@dryajov is aware of this potential bug

## Acceptance criteria

Can toggle gossipEnable to false and test pass

## Notes

Might be an opportunity to clean up how do we inheritance and toggling of floodsub and pubsub

**Comment by oskarth** [comment]
@dryajov is there an upstream issue for this?

**Comment by dryajov** [comment]
Not yet no. I need to investigate the failing test a bit more, it doesn't seem to happen in our tests and we do tests that scenario.

**Comment by oskarth** [comment]
As an alternative, perhaps we can simplify and just inherit from GossipSub... WDYT @kdeme?

**Comment by oskarth** [comment]
Out of date with https://github.com/status-im/nim-waku/pull/295
