### ISSUE TITLE
WakuFilter - Fix tests after nim-libp2p rebase

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#162]
# Problem

As per https://github.com/status-im/nim-waku/pull/157 there were some issues with filter protocol tests. Since they aren't on the critical path for Nangang these are currently disabled.

## Acceptance criteria

Tests enabled and passed

## Notes

Started here https://github.com/status-im/nim-waku/pull/160 but needs to fix merge conflicts ec

**Comment by oskarth** [comment]
What's the status of this?

**Comment by oskarth** [comment]
I believe this is addressed @decanus

**Comment by decanus** [comment]
Yeah.
