### ISSUE TITLE
Dealing with multiple protocol identifiers

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#165]
As per https://github.com/status-im/nim-waku/pull/164 we want to change the protocol identifier to beta1. This will mean node deployment has to be in sync with cluster.

It seems to me like we'd want to have multiple versions supported to avoid these "sync" issues. It isn't obvious to me how this should be done right now in an idiomatic fashion, especially when the changes might be minimal (such as bumping a beta version).

cc @kdeme @decanus @dryajov for ideas

**Comment by decanus** [comment]
@oskarth I was researching this and it seems like in the JS version there is a method for dealing with semver. https://docs.libp2p.io/concepts/protocols/#match-using-semver Maybe this needs to be implemented fully in libp2p on the nim side. @dryajov?

**Comment by dryajov** [comment]
There is already a way of doing custom protocol matches, which can be extended to anything including `semver`, by way of protocol matchers. A matcher (`Matcher* = proc (proto: string): bool {.gcsafe.}`) takes a proto string and returns a bool which indicates if the proto matched or not. 

Unfortunately, this isn't exported on the `switch`, fortunately, the change is trivial and requires adding an optional `matcher` parameter to the `mount` method.

**Comment by oskarth** [comment]
https://github.com/status-im/nim-libp2p/pull/387

**Comment by oskarth** [comment]
@decanus you were looking into this, but it isn't clear to me what conclusion you came to. Could you please document (a) your initial design thinking aka what do we actually want (b) problems you encountered.

**Comment by oskarth** [comment]
Nothing done here it seems like.

cc @jm-clius for awareness of this re production-ready. Putting in icebox for now.

**Comment by oskarth** [comment]
Basic implementation done
