### ISSUE TITLE
Waku v2: Implement rpc message flow for WakuStore

### ISSUE THREAD

**Issue by kdeme** [status-im/nim-waku#168]
Same story as https://github.com/status-im/nim-waku/issues/167 applies for WakuStore.

# Acceptance Criteria
- Be able to send `HistoryQuery`. 
- Be able to receive `HistoryResponse` after a query.
- Have some message distinguishing logic in place so it is clear which response to which query and also so that other message types can be added in future. 
- Have possibility to set a handler on receival of HistoryResponse (actual implementation can be done later for that handler, for now a debug print)

**Comment by oskarth** [comment]
Can we make the acceptance criteria of this more precise?

**Comment by oskarth** [comment]
See https://github.com/status-im/nim-waku/issues/179 for Nim node API

**Comment by kdeme** [comment]
> Can we make the acceptance criteria of this more precise?

Updated.

**Comment by decanus** [comment]
@kdeme I feel like this PR might address what you are looking for: https://github.com/status-im/nim-waku/pull/174 or am I incorrect?

**Comment by oskarth** [comment]
@decanus what's the state of this?
