### ISSUE TITLE
Nim Node Query API

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#179]
Part of https://github.com/status-im/nim-waku/issues/78

# Problem

Query API isn't implemented.

# Acceptance criteria

1) `method query*(w: WakuNode, query: HistoryQuery): HistoryResponse` is implemented
2) Basic test written for it
3) Docs updated: https://github.com/status-im/nim-waku/blob/master/docs/api/v2/node.md

**Comment by oskarth** [comment]
This is the missing issue as far as I understand it https://github.com/status-im/nim-waku/pull/174

@decanus I'd appreciate it if you could create your own issues with clear acceptance criteria. Right now I'm wasting as lot of time chasing up and trying to connect dots because of things like (1)  poor problem statements (2) poor follow up (3) fuzzy issues and PRs that don't target specific issues.

**Comment by oskarth** [comment]
Signature to be revisited by @decanus with request id

**Comment by decanus** [comment]
@oskarth just had another look. I am happy with this signature.

**Comment by decanus** [comment]
@oskarth Actually reconsidering, I have changed the signature to the following:

```
method query*(w: WakuNode, query: HistoryQuery, handler: QueryHandlerFunc)
```

The reason being that like this we can query multiple peers at once.
