### ISSUE TITLE
Waku v2: History response pagination

### ISSUE THREAD

**Issue by decanus** [status-im/nim-waku#189]
# Problem

Currently all messages found are returned as one big block. However if we are in a group chat for example this could be a lot of messages returned to the client.

# Solution

What we should do is add pagination to the query and the response. The user will be able to set the amount of messages to return and the offset to start from. The queried node MUST then use this information to return messages in the queried range.

The pagination can look similar to a cursor in a rest api, however in our protobufs: https://jsonapi.org/profiles/ethanresnick/cursor-pagination/

# Notes
- our current node stores all these messages in memory. They may need to be stored differently (eg sql) in order to be queried more efficiently.

**Comment by oskarth** [comment]
>     our current node stores all these messages in memory. They may need to be stored differently (eg sql) in order to be queried more efficiently.

I would leave that out of scope for now. Pagination can happen in-memory too

**Comment by decanus** [comment]
see spec issue: https://github.com/vacp2p/specs/issues/195
