### ISSUE TITLE
Makefile naming makeover

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#193]
# Problem

Currently the Makefile targets are a bit inconsistent which makes it hard to remember what to type.

https://github.com/status-im/nim-waku/blob/master/Makefile#L71-L105

# Proposed solution

1) Remove `waku` prefix from targets
2) Consistently append name all targets with either 1 or 2

# Acceptance criteria

Makefile done over and clarified, including the Nimbus target file.

--

cc @kdeme @decanus for thoughts

**Comment by oskarth** [comment]
Another somewhat annoying thing is that we have things like v2/../foo2, so the 2 is specified in two places. Though it means binary names are easier/unique, and easier to deal with multiple buffers, so I suppose this is OK.

Not sure what other good patterns here would be?

**Comment by decanus** [comment]
@oskarth yeah the v2 in file names annoys me too, how about we make a separate issue for that?

**Comment by kdeme** [comment]
I'd keep it in the same issue as it is directly related. The names are currently used as resulting binary in the same folder.

**Comment by oskarth** [comment]
To fix the 2 in filename we'd probably need to change the script to append a 2 in the binary, or similar. Not sure if that makes problem worse in terms of not mapping directly? Other alternatives don't seem much better to me:

- Using the same name seems like a bad idea since you might want both and don't know which is which
- Having a separate/nested build folder for v2 seems like a PITA
