### ISSUE TITLE
Integrate store protocol into chat2 example

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#196]
# Problem

As a user of chat2 example app I can't get historical messages.

# Acceptance criteria

In examples/chat2.nim, act as a storeclient and pull down messages from store server node. Show these messages in the beginning of the chat.

**Comment by oskarth** [comment]
> In examples/chat2.nim, act as a storeclient and pull down messages from store server node. Show these messages in the beginning of the chat.

Beginning of the chat means it should finish the REQ-RES operation before proceeding to show other stuff.

**Comment by oskarth** [comment]
Not done. https://github.com/status-im/nim-waku/pull/208#issuecomment-708899645

https://github.com/status-im/nim-waku/commits/master

**Comment by decanus** [comment]
@oskarth I just tested this locally with a local node. It works, I also tested with the cluster node (store does not work there because it has not been updated) but other than that it does.
