### ISSUE TITLE
Deploy and ensure cluster node support store and filter server role

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#198]
# Problem

I want to run a light node and be able to use a node with more capabilities in the cloud that supports historical messages and content filtering.

# Acceptance criteria

1. I can run a node with command line flags that indicate store and filter node to use. 

2. Cluster full node configuration is updated and node  is deployed in the cluster.

3. Tutorial docs for Dingpu updated, including with cluster node address.

**Comment by oskarth** [comment]
@decanus ^ blocker for store and filter protocol to draft.  Itink 1 was done but 2 and 3 not yet?

**Comment by decanus** [comment]
@oskarth the cluster node is now updated. Do we have a node for dingpu? also I am not sure what about the dingpu docs should be updated at this point. Because it would just be the same node as the previous no?

**Comment by decanus** [comment]
Deployed and tested

**Comment by decanus** [comment]
aDded node to doc

**Comment by oskarth** [comment]
Where?

**Comment by oskarth** [comment]
> what about the dingpu docs should be updated at this point. Because it would just be the same node as the previous no?

The node should be there and also how you use it as a store/filter node. That didn't exist for Nangang.

**Comment by oskarth** [comment]
I don't see any PR targeting this, and the acceptance criteria wasn't met, so reopening. Please write here what the actual state is @decanus, right now it is far from clear.

**Comment by oskarth** [comment]
Yeah I don't think this was addressed, at least not properly. See linked issue above.

**Comment by oskarth** [comment]
Searching for `store` I also don't see any `beta1` being mounted, so seems like codec wasnt bumped either?

`https://kibana.status.im/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2020-10-03T22:23:04.892Z',to:now))&_a=(columns:!(message,severity_name,_type),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:d6db7610-60fd-11e9-98fa-2f101d13f938,key:program.keyword,negate:!f,params:(query:docker%2Fnim-waku-node),type:phrase),query:(match_phrase:(program.keyword:docker%2Fnim-waku-node))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:d6db7610-60fd-11e9-98fa-2f101d13f938,key:fleet.keyword,negate:!f,params:(query:wakuv2.test),type:phrase),query:(match_phrase:(fleet.keyword:wakuv2.test)))),index:d6db7610-60fd-11e9-98fa-2f101d13f938,interval:auto,query:(language:kuery,query:store),sort:!())
