### ISSUE TITLE
Namespaced topics

### ISSUE THREAD

**Issue by kdeme** [status-im/nim-waku#206]
Implement namespaced topics as mentioned here: https://github.com/vacp2p/specs/issues/180#issuecomment-692528715

> One thing I've had on my backlog but didn't turn into an issue yet is namespaced topics a la Eth2 p2p spec. What are your thoughts on this? That way perhaps we can have have something like /waku/v1/<prev-topichash>/encoding.

> From p2p spec:

>    Topics are plain UTF-8 strings and are encoded on the wire as determined by protobuf (gossipsub messages are enveloped in protobuf messages). Topic strings have form: /eth2/ForkDigestValue/Name/Encoding. This defines both the type of data being sent on the topic and how the data field of the message is encoded. and https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/p2p-interface.md#topics-and-messages

> Yeah, that sounds like a good idea for keeping compatibility when bridging, however allowing different topic type in the future.

> We do have to watch out with how much information we provide in such string.
> (Side node: ofcoursein eth2 this topic string is different from our contentTopic, as it is on pubsub level, and for Waku it is not)

**Comment by kdeme** [comment]
Blocked basically by decision of solution here: https://github.com/vacp2p/specs/issues/180

**Comment by oskarth** [comment]
Largely superseded by https://github.com/vacp2p/specs/issues/221 Note that this is about PubSub topics, not contentTopic.

**Comment by oskarth** [comment]
It is also worth noting that per https://github.com/vacp2p/specs/issues/180 we made it less obvious what a potentially hierarchical structure would look like (which you'd get for free with string representation). Though I guess we haven't explicitly said that it is a hash, just bytes type... https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/p2p-interface.md#why-are-the-topics-strings-and-not-hashes

**Comment by decanus** [comment]
@oskarth we could use the byte encoding of a https://github.com/vacp2p/multiprotocol for the hierarchical representation.

**Comment by oskarth** [comment]
Done in https://github.com/vacp2p/specs/issues/221#issuecomment-717705617
