### ISSUE TITLE
Kibana filter by log level

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#214]
# Problem

I want to filter Kibana logs by severity level.

## Notes

In [Kibana](https://kibana.status.im/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2020-10-12T22:23:04.892Z',to:now))&_a=(columns:!(message,severity_name),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:d6db7610-60fd-11e9-98fa-2f101d13f938,key:program.keyword,negate:!f,params:(query:docker%2Fnim-waku-node),type:phrase),query:(match_phrase:(program.keyword:docker%2Fnim-waku-node))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:d6db7610-60fd-11e9-98fa-2f101d13f938,key:fleet.keyword,negate:!f,params:(query:wakuv2.test),type:phrase),query:(match_phrase:(fleet.keyword:wakuv2.test)))),index:d6db7610-60fd-11e9-98fa-2f101d13f938,interval:auto,query:(language:kuery,query:waku),sort:!())) I can see views such as this:

![image](https://user-images.githubusercontent.com/1552237/95811025-ef614a80-0d44-11eb-826d-fef4c74840ab.png)

This has a `severity_info` column, but it doesn't seem to map to severity level in `message` field.

I assume this has to do with the (lack of) interpretation of log fields. The message field is picked apart correctly though. Perhaps this is some toggle for the log format to use in production?

@kdeme do you know? Or someone in Nimbus team perhaps.

Also cc @jakubgs if this is something on Kibana end, though that seems unlikely.

**Comment by jakubgs** [comment]
This is a LogStash matter. We either have to add a regex to Logstash that extracts severity, or you can print the logs in a format that's easily consumable like JSON, and then we can make Logstash parse the JSON.

Example:
https://github.com/status-im/infra-hq/blob/c8515dba9b791f363370e2cf101a747aa51b8ddc/ansible/roles/logstash/templates/pipe/52-filter-beacon-node.conf#L6-L10

**Comment by jakubgs** [comment]
@oskarth which one do you want? Just parse the current logs? It shouldn't be that difficult.

**Comment by oskarth** [comment]
I want the severity_info extractor to reflect the actual severity level. Currently it says `info` everywhere instead of INF, TRC, DBG, etc. That way I can filter out all TRC messages, or only show WRN, etc.

**Comment by jakubgs** [comment]
I understand what you want.
I was asking if you want me to parse the current format or would you prefer to switch the format to JSON?

**Comment by jakubgs** [comment]
But that's irrelevant now, I already made the change: https://github.com/status-im/infra-hq/commit/b0510534

![nim_waku_logs_severity](https://user-images.githubusercontent.com/2212681/95851174-28ec8280-0d52-11eb-9f7b-59dfafe5a131.png)

https://kibana.status.im/goto/5c82b64a7cbbb9102d675965cd4d9268

**Comment by oskarth** [comment]
Oh sorry gotcha, skimmed before. Awesome thanks!

**Comment by jakubgs** [comment]
@oskarth Here you go, more detailed field parsing: https://github.com/status-im/infra-hq/commit/1491600e

![nim_waku_moar_fields](https://user-images.githubusercontent.com/2212681/95970157-eb4e2f00-0e0f-11eb-99f5-04e4e3874790.png)

https://kibana.infra.status.im/goto/efad242b740b223dc668ef0ed86165f0
