### ISSUE TITLE
Cluster node not relaying messages (deployed recently?)

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#215]
# Problem

After https://github.com/status-im/nim-waku/issues/198 I can't use the cluster node in e.g. `chat2`.

Looking at [Kibana](https://kibana.status.im/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:%272020-09-09T20:21:49.910Z%27,to:now))&_a=(columns:!(message,severity_name),filters:!((%27$state%27:(store:appState),meta:(alias:!n,disabled:!f,index:d6db7610-60fd-11e9-98fa-2f101d13f938,key:program.keyword,negate:!f,params:(query:docker%2Fnim-waku-node),type:phrase),query:(match_phrase:(program.keyword:docker%2Fnim-waku-node))),(%27$state%27:(store:appState),meta:(alias:!n,disabled:!f,index:d6db7610-60fd-11e9-98fa-2f101d13f938,key:fleet.keyword,negate:!f,params:(query:wakuv2.test),type:phrase),query:(match_phrase:(fleet.keyword:wakuv2.test)))),index:d6db7610-60fd-11e9-98fa-2f101d13f938,interval:auto,query:(language:kuery,query:Listening),sort:!())) it seems like the last deploy was a week ago.

It is unclear to me exactly how https://github.com/status-im/nim-waku/issues/198 was tested end to end with chat2.

## Details

Looking at [recent logs](https://kibana.status.im/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2020-10-12T22:23:04.892Z',to:now))&_a=(columns:!(message,severity_name,_type),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:d6db7610-60fd-11e9-98fa-2f101d13f938,key:program.keyword,negate:!f,params:(query:docker%2Fnim-waku-node),type:phrase),query:(match_phrase:(program.keyword:docker%2Fnim-waku-node))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:d6db7610-60fd-11e9-98fa-2f101d13f938,key:fleet.keyword,negate:!f,params:(query:wakuv2.test),type:phrase),query:(match_phrase:(fleet.keyword:wakuv2.test)))),index:d6db7610-60fd-11e9-98fa-2f101d13f938,interval:auto,query:(language:kuery,query:waku),sort:!())), I see a few suspicious things that may or may not be related:

`DBG 2020-10-13 03:10:26.006+00:00 Error generated                            tid=1 file=router.nim:115 error="{"code":-32601,"id":1,"message":"Method not found","data":"admin_nodeInfo is not a registered RPC method."}" id=1`

Though no ERR or WAR AFAICT.

To be investigated further.

**Comment by oskarth** [comment]
The node info RPC DBG seems unrelated, but it could have some side effects. @jakubgs I should've been more clear, the name of this RPC is `waku_info` and it currently returns a string with multiaddr (to be expanded in future). It takes no arguments.

@jakubgs could you comment here what consequences a failing health check (e.g.) currently has for Waku nodes?

**Comment by oskarth** [comment]
My guess is that the node was never actually deployed, but I can't test that since e.g. codecs weren't updated (and it is hard to filter log level etc). Other alternative is that it was started but for some reason "Listening on" was never printed? (?!?)

**Comment by oskarth** [comment]
Locally I also notice that peer length for message forwarding is 0 when three nodes A, B, C are running, A connected to B and C and B sending to A (which should forward to C, but doesn't).

```
TRC 2020-10-13 12:36:46.527+08:00 forwared message to peers                  topics="gossipsub" tid=16649 peers=0 msgId=000000000000000216Uiu2HAm2Fgfb5GgrRWVsxKEcqGrqbXAkgG41xACLn4oosNd898Y peer=
16Uiu2HAm2Fgfb5GgrRWVsxKEcqGrqbXAkgG41xACLn4oosNd898Y
```

**Comment by oskarth** [comment]
See https://github.com/status-im/nim-waku/issues/221 for separate issue (last comment)

**Comment by oskarth** [comment]
Looking back at the issues I realize the cluster node was updated a week ago, so the dates check out:

However, if it was tested I'm not sure what happened with https://github.com/status-im/nim-waku/issues/221

Additionally the codecs are wrong, increasing my confusion here https://github.com/status-im/nim-waku/issues/216

https://github.com/status-im/nim-waku/issues/221

**Comment by jakubgs** [comment]
>could you comment here what consequences a failing health check (e.g.) currently has for Waku nodes?

It appears as unhealthy in Consul. That's it.

>I should've been more clear, the name of this RPC is `waku_info`.

I know, I just never updated that because I was busy with other things. My understanding was that that RPC call was just for v2.
If that's the case then I would have to use different healthcheck depending on image used, which is quite ugly.

**Comment by jakubgs** [comment]
I made it use `waku_info` in https://github.com/status-im/infra-nim-waku/commit/07f44ab8.

Better to have 1/3 healtchecks working than all 3 broken:
https://consul.status.im/ui/do-ams3/nodes/node-01.do-ams3.wakuv2.test

**Comment by jakubgs** [comment]
Waku v1 doesn't even appear to be listening on the RPC port at all.
```
admin@node-01.gc-us-central1-a.waku.test:~ % d exec -it nim-waku-node sh
/ # netstat -lpnt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.11:34923        0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:30303           0.0.0.0:*               LISTEN      1/wakunode
tcp        0      0 0.0.0.0:8008            0.0.0.0:*               LISTEN      1/wakunode
```

**Comment by oskarth** [comment]
Waku v1 and v2 are best thought of as two separate projects. We are not really doing active changes to v1.

**Comment by jakubgs** [comment]
If v1 is not actively developed and v2 is the next generation why are we running just 1 node of v2 and 3 of v1?

Shouldn't it be vice versa?

**Comment by oskarth** [comment]
Because v1 is what nim-status will initially target and probably have in production. As Vac we aren't actively improving it, but there might be improvements from nim-status as a production team.

We can have more nodes for v2, that'd be good, it just isn't really a blocker right now

**Comment by oskarth** [comment]
Since the fix mostly impacts client node, there is no need to update cluster for this specific bug I believe. There would be if there was a mesh in our cluster, but that is currently not the case.
