### ISSUE TITLE
Address already in use when quickly restarting - lack of sockets cleanup?

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#218]
# Problem

Often when restarting a process (e.g. after recompile) such as `chat2` or `wakunode` this error happens:

```
TRC 2020-10-13 12:04:11.398+08:00 starting node                              tid=15761 address=/ip4/0.0.0.0/tcp/60000
Traceback (most recent call last, using override)
/home/oskarth/git/status-im/nim-waku/vendor/nim-eth/eth/common/eth_types.nim(576) main
/home/oskarth/git/status-im/nim-waku/vendor/nim-eth/eth/common/eth_types.nim(569) NimMain
/home/oskarth/git/status-im/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim(407) reportUnhandledError
/home/oskarth/git/status-im/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim(358) reportUnhandledErrorAux
Error: unhandled exception: (98) Address already in use [TransportOsError]
```

Waiting a bit it takes care of itself. It seems to me that we should ensure sockets etc are properly cleaned up on SIGINT, e.g.

I haven't investigated it so I'm not sure exactly where resource cleanup should happen. Perhaps NBC is doing something here? @kdeme do you know?

## Acceptance criteria

Better resource cleanup to allow restarting with same address/port. Alternatively, understanding of where limitation comes from (in case this is a OS thing).

**Comment by oskarth** [comment]
Also cc @dryajov for any information you might have about hanging connections in nim-libp2p

**Comment by kdeme** [comment]
It is unlikely that proper resource clean-up will remove this issue (at best it might stop a last send earlier). After all the OS will do this clean-up anyhow. 
This is more likely because of a socket in `TIME_WAIT` state, and thus all you can do is wait or use the `SO_REUSEADDR` flag.

You can pass it to `newStandardSwitch` with `{ServerFlags.ReuseAddr}`.

**Comment by kdeme** [comment]
This hopefully resolves the issue: https://github.com/status-im/nim-waku/pull/223

**Comment by oskarth** [comment]
Ah nice, TIL. I thought it was a hanging fd or something.
