### ISSUE TITLE
Add a --log-nocolor flag

### ISSUE THREAD

**Issue by jakubgs** [status-im/nim-waku#22]
Colors are horrible for log aggregators, just look at this shit:
```
docker/nim-waku-node[17151]: #033[32mINF#033[0m 2020-05-28 19:15:18+00:00 #033[1mStarting metrics HTTP server              #033[0m #033[32mtid#033[0m=#033[94m1#033[0m #033[32mfile#033[0m=#033[94mwakunode.nim:127#033[0m #033[32maddress#033[0m=#033[94m0.0.0.0#033[0m #033[32mport#033[0m=#033[94m8008#033[0m
```

**Comment by zah** [comment]
Wouldn't logging with JSON make more sense if the logs end in ElasticSearch/Kibana?

**Comment by kdeme** [comment]
You can already provide a flag at compile time to disabled the colors: `NIM_PARAMS="-d:chronicles_colors:none"`
And we can also change the format to JSON as mentioned by zah. Could also log to file if that is more convenient.

**Comment by jakubgs** [comment]
Json is nice. Sure.

**Comment by zah** [comment]
To enable JSON, compile the binaries with `NIM_PARAMS="-d:chronicles_sinks=json"`.

**Comment by jakubgs** [comment]
It's nice as a temporary solution, but I wouldn't want to recompile a tool just to change log format.

**Comment by arnetheduck** [comment]
if it helps, think of compiling as running a python script ;)

**Comment by jakubgs** [comment]
It's not the same when i have to re-compile Nim compiler too :D.

**Comment by stefantalpalaru** [comment]
> It's not the same when i have to re-compile Nim compiler too :D.

Use Docker's step-based caching to your advantage, by building the compiler in a separate step: https://github.com/status-im/nim-beacon-chain/blob/4b731b266d89e92d8a22c111f18de578dabcf1a0/docker/Dockerfile#L10

**Comment by zah** [comment]
You are giving docker lessors to the wrong man, @stefantalpalaru :P

**Comment by jakubgs** [comment]
Yeah, I saw that, it would help, I just really dislike the `clone` step there. Which files specifically does the Nim compilation require from the repo? Maybe we could `ADD` just those first for just that.
I'll probably add something like that in my next PR with some other fixes.

**Comment by kdeme** [comment]
Closing this as it is possible at compile time with `make NIM_PARAMS="-d:chronicles_colors:none" wakunode`.
Run time option is rather an issue to be created at chronicles library repo.

**Comment by jakubgs** [comment]
If so then we should use `-d:chronicles_colors:none` by default for Docker images: #26
