### ISSUE TITLE
Messages not being forwarded properly with a third node

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#221]
# Problem

Sometimes recently, the chat2 example stopped working for multiple nodes.

Note that this is both before and after latest nim-libp2p bump (see open PR).

Topology:
- A, B, C nodes
- B and C connects to C

Scenario:
- C publishes message, A receives it, but not B
- B publishes message, A receives it, but not A
- A publishes message, B and C receives it

## Details

Using trace:

```
INF 2020-10-13 13:16:08.282+08:00 Hit subscribe handler                      tid=10767 topic=waku payload=blol contentTopic=dingpu                
TRC 2020-10-13 13:16:08.282+08:00 broadcasting messages to peers             topics="pubsub" tid=10767 peers=0 msg="(subscriptions: @[], messages: @[(fromPeer: \"16*hmkWy3\", data: \"0a04626c6f6c
...64696e677075\", seqno: \"0000000000000001\", topicIDs: \"@[\\\"waku\\\"]\", signature: \"\", key: \"\")], control: (ihave: @[], iwant: @[], graft: @[], prune: @[]))"
TRC 2020-10-13 13:16:08.282+08:00 forwared message to peers                  topics="gossipsub" tid=10767 peers=0 msgId=000000000000000116Uiu2HAkv8dhuLiN1FXML96iDVEUZVsauJJviZny1o2FjvhmkWy3 peer=
16*hmkWy3
```

Notice the `peers=0`. If A is sending a message directly, it says `peers=2`. So for some reason it doesn't know to send messages to B and C.

**Comment by oskarth** [comment]
I looked a bit but didn't go too deep, nor tried bisecting etc

**Comment by decanus** [comment]
I am currently looking at libp2p as to where this issue could arise, I haven't found anything productive yet. Will keep digging.
