### ISSUE TITLE
Waku v1 RPC and v2 RPC calls are in conflict

### ISSUE THREAD

**Issue by kdeme** [status-im/nim-waku#240]
There are several conflicting waku rpc calls e.g. `waku_version`, `waku_info`, `waku_subscribe`, etc.

This is specifically a problem when running a bridge that might enable both.

We need to decide how to resolve this, e.g. by having a different prefix or by running a separate rpc server on different ports for each version.

Considering this is only an issue for the bridge, perhaps the latter is fine.
RPC calls are not even that important for the bridge, except perhaps for the `info` call.

**Comment by oskarth** [comment]
To mirror how Eth2 and Nimbus does it (with JSON RPC), perhaps the easiest here is to have a version number? E.g. a la https://ethereum.github.io/eth2.0-APIs/#/

/waku/v1/<name> and /waku/v2/<name>

I don't know how big of a deal it'd be to have v1 use that name? If there are compatibility issues due to status-nim etc, we can leave them as is and add shadow functions to make things consistent. WDYT @kdeme?

**Comment by oskarth** [comment]
This will or could also be an issue downstream with status-nim, etc

**Comment by kdeme** [comment]
> To mirror how Eth2 and Nimbus does it (with JSON RPC), perhaps the easiest here is to have a version number? E.g. a la https://ethereum.github.io/eth2.0-APIs/#/
> 
> /waku/v1/ and /waku/v2/

Yes, but that is for the REST API, where it is in the URL. 
The equivalent for json-rpc would be to add that as prefix or so in the method name.



> This will or could also be a problem downstream with status-nim, status-react, etc. So I don't think just running it on different ports is a good long term solution.
Right, good point. So looks like we will have to go with adapting the method names.

**Comment by oskarth** [comment]
>       Yes, but that is for the REST API, where it is in the URL.
> The equivalent for json-rpc would be to add that as prefix or so in the method name.

Yeah to me this was obvious, I should've made it explicit. Prefix ~= /

**Comment by oskarth** [comment]
Will be addressed as part of https://github.com/status-im/nim-waku/issues/243

**Comment by kdeme** [comment]
I'll go ahead and adjust API's with `waku_v2_` prefix

**Comment by oskarth** [comment]
@kdeme what happened with this issue? Also think some of it is outdated considering @jm-clius JSON RPC API. It isn't clear to me what we want to achieve with Waku v1 JSON RPC API here though...

**Comment by kdeme** [comment]
This can be closed. I see all got added here: https://github.com/status-im/nim-waku/tree/37a3a4faddbe29341d1af354159ca8ae2874d79f/waku/v2/node/jsonrpc

We can leave v1 as is. 
I do see the old rpc directory still exists, if this should be removed.

**Comment by jm-clius** [comment]
Thanks, @kdeme. Yes, `infra` had some dangling dependency on the old `rpc` code. This has now also been refactored, so I will remove the directory.
