### ISSUE TITLE
Production-ready: Persistence of store messages

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#245]
# Problem

As a node runner, I want to be able to restart a node and still keep state of historical messages.

As a user, I want historical messages to work better for HA nodes that restart.

# Notes

Requires basic integration with sqlite, a la what Desktop has done.

Out of scope:
- Efficient indices and optimizations

Suggested approach:
- Either do a basic append-only log with JSON/BLOB which reads into memory on startup and then appends each new state change, or
- Do more traditional interactive INSERT/LOOKUP for each item etc (probably a bit more work)

cc @decanus I believe this is needed at a basic level for getting nim-waku production ready for Status.

# Further issues

Look into how the existing mailserver production setup works, and make sure this can be re-used in some form.

**Comment by decanus** [comment]
If we do a basic append only log we could use https://github.com/decanus/minima :P

**Comment by oskarth** [comment]
> This software is still pre-alpha, and should not be considered reliable.

Meanwhile, SQLite is one of the most robust and ported libraries on the planet, including being used by Status desktop. I think I know which one wins...

**Comment by decanus** [comment]
Fair, I think the sqlite could be easy to do although I remember sqlite in particular being a bit annoying to work with with regards to blobs. I may be wrong however.
