### ISSUE TITLE
Production-ready: Relay improvements

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#246]
# Problem

Currently the relay protocol needs some improvements. This is a list of things that we want to address. They may be split up into individual issues.

- [x] FloodSub use is broken -> disable? https://github.com/status-im/nim-waku/issues/161
- [x] Simplify inheritance of Flood/GossipSub (right now the model is a bit odd, probably easier if we remove FloodSub)
- [x] Use GossipSub 1.1 for extra protection (default in Eth2)
- [x] Use StrictNoSign policy (needed for basic privacy, https://github.com/libp2p/specs/pull/294/files - should be done in nim-libp2p already)

...more?

---

cc @decanus @jm-clius these are some things I believe are needed to be production-ready, also cc @kdeme

**Comment by oskarth** [comment]
See linked spec issue

**Comment by oskarth** [comment]
To be aware of: https://github.com/status-im/nimbus-eth2/commit/937decb0e99baee02bdf9445d069b16728c94743

**Comment by decanus** [comment]
So @oskarth after upgrading nim-libp2p, gossip1.1 is the default so this is already the case. as @dryajov said however `StrictNoSign` is not yet implemented in nim-libp2p.

**Comment by oskarth** [comment]
StrictNoSign is part of Eth2 spec as far as I know, so how does that work? Seems odd that this capability wouldn't be in. Perhaps it exists informally without being called a policy per se? @zah do you know?
