### ISSUE TITLE
Store protocol: Handling duplicate waku messages

### ISSUE THREAD

**Issue by staheri14** [status-im/nim-waku#254]
### Problem
In the store protocol, if a node receives multiple copies of the same message, it stores all of them as distinct messages. This takes up unnecessary memory space.

### Acceptance Criteria
The store protocol keeps only one instance of each waku message and ignores the duplicates

**Comment by decanus** [comment]
Hmm, what do you mean by duplicate right now? This is not something the node should determine imo on what is duplicated and what is not. I believe @oskarth and I had a discussion about this on wakuv1.

**Comment by staheri14** [comment]
@decanus By duplicate waku messages I meant  those with the same payload and contentTopic.
Removing duplicates saves the storage and the bandwidth (history responses only include unique waku messages) 
What do you see as the benefits of keeping the duplicates or the downside of removing them?  there might be other aspects that I am not aware of

**Comment by kdeme** [comment]
I guess this stems from the fact that the Index is the received time combined with the hash?

If instead the sender would add a transmitTime, this issue would not occur as the Index would be the same.

So perhaps look into https://github.com/vacp2p/specs/issues/219

**Comment by oskarth** [comment]
@staheri14 is this still relevant?

**Comment by jm-clius** [comment]
Closing this issue, as there is a duplicate and I don't want to split the comment thread: https://github.com/status-im/nim-waku/issues/729

@staheri14 feel free to reopen if this issue is subtly different and needs to remain open.
