### ISSUE TITLE
Production-Readiness

### ISSUE THREAD

**Issue by decanus** [status-im/nim-waku#256]
> This issue highlights some requirements and things that will need to be turned into issues for integrating `nim-waku` into `nim-status`.

# Problem

Now that nim-waku is getting more and more stable we need to start thinking about some of the features / requirements there are on the codebase and the protocol itself to get it production ready. This is an issue that needs the input of various stakeholders and parts of it will most likely be up for debate.

Tagging @iurimatias @michaelsbradleyjr @arnetheduck just so they are informed.

# Solution

Here are a few of the things we need to discuss, take a look at and potentially will need solutions for:

 - **Persistent Storage** - This is one of the issues being worked on already [#245](https://github.com/status-im/nim-waku/issues/245). It is important to note as @michaelsbradleyjr mentioned that for the client side this may not be as urgent. This is due to the fact that the stimbus team has decided to build their own storage thing.

   What we do need to achieve for the node side is having a persistent storage for messages, right now messages are being stored in-memory, on restart this causes a crash.
   
 - **Bridge** - Work on the bridge has already started, I personally cannot say what state it is in but @kdeme can probably elaborate. But to be able to shift to WakuV2 we need a reliable and **tested** method to relay messages from v1 to v2.
 - **Cluster** - For our cluster it will probably make sense to have different clusters, one for dev, staging and production. This is similar to v1. The nodes should be visible on <https://fleets.status.im>
 - **Privacy Analysis** - This will probably be something @staheri14 works on, but as @arnetheduck had mentioned, one of the things that is important for wakuv2 is that we can provably state that it is an improvement from v1. Not only that but this is something we can give back to the libp2p community.
 - **Ensuring we can retain current users & grow** - Another thing we need to analyze beforehand is whether wakuv2 can actually retain the current users we have and has enough head room to grow beyond current user counts. This would be nice to verify through simulations.
 - **Metrics** - Oskar mentioned that grafana stats for v2 nodes used to work, but it seems like they do not anymore. It would be good to get these working again and could be a pretty low hanging fruit.
 - **Docs** - The docs of the nim-waku codebase can use a lot of improvements, this could include publishing docs (see: https://decanus.github.io/minima/), but it also means basics like adding docs on how the payload encryption works.
 - **Status Specs** - We will need to update the status specs similar to how we did for v1 with a wakuv2 usage spec. This will dictate how the integration in the clients works.
   
   
# Accceptance Criterias

 - WakuV2 can be used in status desktop when running with an `experimental` flag.
 - There is reasonable confidence that it will work in production.

# Notes

 - https://github.com/status-im/nim-waku/issues/246
 - https://github.com/status-im/nim-waku/issues/245
 - https://github.com/vacp2p/specs/issues/232
 - https://github.com/vacp2p/specs/issues/233

**Comment by oskarth** [comment]
What about bridge? Deploying more nodes to cluster? Discovery/static nodes? Specs freeze to stable? Filter ACK? Pagination in chat2 example? Store node deployment?

It's fine if some things are out of scope, but we should be explicit about it then with rationale.

**Comment by oskarth** [comment]
Ping on this @decanus

**Comment by oskarth** [comment]
@decanus can we make it clear:

1. What the must haves are for acceptance criteria to be met?
2. What we can reasonable achieve in the 2-3 weeks that are left of November?
3. Make it explicit what blockers/unknowns are?

And break the most pressing issues down to separate issues.

**Comment by decanus** [comment]
@oskarth 

1. I'd say `peristent storage`, `cluster`
2. I'd say `peristent storage`, `cluster` and `metrics`

Not sure on 3

**Comment by decanus** [comment]
Unknowns - How we handle state. cc @michaelsbradleyjr

**Comment by decanus** [comment]
@oskarth metrics resolved by: https://github.com/status-im/infra-hq/commit/299a598b

**Comment by oskarth** [comment]
Can we add details to docs or somewhere? Where is dashboard, etc

**Comment by oskarth** [comment]
For metrics, I'm missing an issue of what we are tracking that's special for Waku v2 and what we want to track. The current view in https://github.com/status-im/nim-waku/pull/293 is basically useless.

**Comment by oskarth** [comment]
@decanus see above re metrics.

**Comment by decanus** [comment]
Yeah @oskarth, I am currently trying to figure out how it works etc.

**Comment by jm-clius** [comment]
Adding to Vac PM Board for visibility and moving to icebox. Quick review shows we've made some progress towards the listed items, though there are still some outstanding investigations. Notably:
- Continuing work on the **bridge**
- Verify that **clusters** are still running as expected (`prod` and `test`)
- **Ensure we can retain current users & grow** by adding benchmark tests and simulations. I'll add to this the need to show improved performance over Waku v1 using similar simulation(s) and metrics.
