### ISSUE TITLE
Folder restructure - make v1 and v2 separate folders at waku top level

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#261]
# Problem

Currently we have the following structure:

- waku/node/{v1,v2}/...
- waku/protocol{v1,v2}/...

It'd also be useful to have a common/util module.

This doesn't reflect how work is done, since v1 and v2 are usually done in isolation. This leads to annoying imports and unclear separation between v1 and v2 etc.

# Proposed solution

Change to:

- waku/v1/{node,protocol}/...
- waku/v2/{node,protocol}/...

Common utils can then either be in v1 or v2, as appropriate.

Bridge can be in waku/common/wakubridge.nim

This would reflect better how we work, and also mirror how tests are structured.

---

cc @jm-clius @decanus @kdeme @staheri14 thumbs up or down and/or comments!

**Comment by staheri14** [comment]
Just a suggestion, we may put common utils under waku/common/utils or waku/utils

What about the structure test folders and files?

**Comment by staheri14** [comment]
It might be also helpful if we add some descriptions about the content of each file (at the top of each file)
For example, [waku_types.nim]( https://github.com/status-im/nim-waku/blob/master/waku/node/v2/waku_types.nim ) does not only contain the data types but also has some procs, and constructors, but the description of the file does not reflect this. Not sure if this fits the scope of this issue, but just wanted to bring to your attention :)

**Comment by staheri14** [comment]
We could also dedicate a spec to explain the structure of the codebase, folders, where to find what. It is really needed specially for those who are new to the codebase.

**Comment by oskarth** [comment]
Good ideas! As for spec, for nim-waku as an implementation basic documentation probably makes more sense.

Let's attack this iteratively, if there's an easy fix you (or someone) sees feel free to just issue a PR! I might do the basic folder restructure PR when I have some downtime from accounting, will see.

**Comment by decanus** [comment]
I think beyond a spec just generally better documentation + a generated documentation site will drastically help this.

**Comment by oskarth** [comment]
Closing this as main OP has been addressed; feel free to open additional issues as needed.
