### ISSUE TITLE
Discovered peer list / Peer pool

### ISSUE THREAD

**Issue by kdeme** [status-im/nim-waku#265]
Currently nodes are passed as cli arguments. Arguments being staticnodes, storenode & filternode.

Staticnodes are immediately dialed for use in libp2p pubsub, and from outside the protocol code.
The other two are dialed when needed from within the WakuFilter and WakuStore protocol.

It should be possible to add nodes through other means, such as different discovery ways, static lists from web or local disk, etc.
In order to do this we need a place where all these nodes are stored before they are used in the protocols.
Not sure whether to call this a "peer pool", as afaik, the WakuFilter and WakuStore will not actively stay connected to the peers.

We should be able to distinguish the capabilities of these peers so that the proper peer can be selected for the right protocol.
This will also allow to have more than 1 storenode or filternode available.

**Comment by dryajov** [comment]
This is a missing feature in libp2p and it would be nice to add it there as opposed to yet another ad hoc implementation. 

From what it looks like you need both (node/peer) discovery mechanisms and peer management mechanisms, both of which are part of the libp2p stack but are missing from our implementation. 

There isn't a spec I can find that describes discovery and peer management, but we can come up with a consistent api for each of this use cases. 

For example, static nodes can be considered bootstrap nodes that are known in advance and `WakuFilter` and `WakuStore` nodes are discovered over some dynamic discovery mechanism such as a DHT. Both the DHT and bootstrapping are discovery mechanisms that can share the same interface. I started something like that a while back but never managed to finish it  - https://github.com/status-im/nim-libp2p/pull/87. As I remember it, the API that I ended up with was not ideal, so I advice against trying to rely on it too much at this point.

The discovery interface can be something very very simple, like a `getNodes*[T](query: T = nil): Future[Nodes]` that will work for both static and dynamic lookup. For static lookup (bootstrapping), we simply call the `getNodes()` method periodically, say on a timer and it returns the same list of nodes every time, for the DHT based lookups we provide a query `get(query: string): Future[Nodes]` and call it on demand, whenever specific nodes are needed.

Lets continue the discussion either here or in libp2p to further refine it and hopefully come up with something more consistent 👍 (I'll add an issue in libp2p and link it here)

**Comment by jm-clius** [comment]
Would a good place to start be adding a "Peer Store"/"Peer Book" to nim-libp2p, not unlike the go-implementation [here](https://github.com/libp2p/go-libp2p-peerstore) with interface definition [here](https://github.com/libp2p/go-libp2p-core/blob/master/peerstore/peerstore.go)?
Its function would be:
- collect, store and expose information about all "known" peers, including supported protocols, performance metrics and connection metadata. Sophisticated peer scoring and ageing mechanisms can be added over time.
- provide API calls to add/remove peers in an agnostic way (whether via discovery/bootstrapping/file stream/explicit external API call)
- perhaps eventually some persistence

Peer management and peer discovery can then be built on top of this store. @dryajov I think this is similar to what you suggest above, except that it explicitly separates the store from the management/discovery. This way protocols such as `WakuRelay` can choose to populate its own Peer Store and implement rudimentary management until more sophisticated management/discovery implementations are available.

**Comment by jm-clius** [comment]
Basic peer store with manager implemented [here](https://github.com/status-im/nim-waku/issues/358).  There is an extended `nim-libp2p` effort for [peer and connection management](https://github.com/status-im/nim-libp2p/issues/537) in progress.
