### ISSUE TITLE
Implement connection management

### ISSUE THREAD

**Issue by kdeme** [status-im/nim-waku#266]
Currently nodes are passed as cli arguments. Arguments being staticnodes, storenode & filternode.

Staticnodes are immediately dialed for use in libp2p pubsub, and from outside the protocol code.
The other two are dialed when needed from within the WakuFilter and WakuStore protocol.

This means that once the staticnodes get disconnected from libp2p, there will be no reconnection and the WakuRelay protocol will no longer function. We need to set-up proper connection management to redialing the peers that are no longer connected (with some back-off table in case of failures)

Related peer pool issue: https://github.com/status-im/nim-waku/issues/265
Similar Waku v1 issue: https://github.com/status-im/nim-waku/issues/18

**Comment by oskarth** [comment]
I'd say this can be closed once we have basic peer store in nim-waku @jm-clius

**Comment by jm-clius** [comment]
Basic peer store with manager implemented [here](https://github.com/status-im/nim-waku/issues/358).  There is an extended `nim-libp2p` effort for [peer and connection management](https://github.com/status-im/nim-libp2p/issues/537) in progress.
