### ISSUE TITLE
Add hook on newly added envelope

### ISSUE THREAD

**Issue by kdeme** [status-im/nim-waku#267]
We need to be able to trigger a function call when a new envelope is being added to the envelope queue in Waku v1

This is useful e.g. for:
- when storing the envelopes for later retrieval -> Waku v1 mailservers
- when creating a bridge between waku v1 and waku v2.

**Comment by oskarth** [comment]
@jm-clius thoughts on this one?

**Comment by kdeme** [comment]
I'll add this, it is required for the bridge

**Comment by jm-clius** [comment]
Thanks @kdeme. Still moving to icebox to reflect that it's not necessarily in Feb timeframe.
