### ISSUE TITLE
Store Protocol Persistence Improvements

### ISSUE THREAD

**Issue by decanus** [status-im/nim-waku#272]
# Problem

Right now the store protocol persistence works in a very rough manner, it loads the messages from the dB into memory when it starts and saves and new messages in the db. This means that the querying we could do efficiently in a db using indexes, we still do in our code through excessive lines of code that could be written as a singular sql query that can probably be quite simple.

# Solution

We move the pagination to the SQLite db, this means we can take advantage of more performs the indexes and no longer require large amounts of code for essentially indexing and searching an array in code.

cc @staheri14 @oskarth

# Notes
 - Some work has already been done here: https://github.com/status-im/nim-waku/pull/247

**Comment by oskarth** [comment]
It isn't clear to me what:

1) The bottleneck would be (bad data structure? expensive writes or reads? out of memory?)
2) How this interacts with DB issues nim-status will look into

**Comment by oskarth** [comment]
I think a lot of this has been addressed by @jm-clius already, closing

**Comment by oskarth** [comment]
Putting in icebox
