### ISSUE TITLE
Refactor: Avoid result return, prefer expression

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#287]
we avoid `result` as it turns off useful compiler warnings and is prone to bugs - `expression` return is preferred, followed by explicit `return` (expressions don't work in all contexts, such as `async`) - in this case, just remove `result =`

_Originally posted by @arnetheduck in https://github.com/status-im/nim-waku/pull/263#discussion_r527466340_

---

Currently we use result in a few places, probably good opportunity and fairly quick to fix this.

**Comment by oskarth** [comment]
Also see https://github.com/status-im/nim-waku/issues/146

**Comment by oskarth** [comment]
Captured elsewhere

**Comment by jm-clius** [comment]
I think we've addressed this everywhere? Closing.
