### ISSUE TITLE
Refactor: Clean up import paths

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#288]
# Problem

Currently our imports are needlessly verbose and also not idiomatic. Clean this up.

# Notes

1. Generally remove unused imports
2. Use export for modules to get package wholesale instead of remember to import same misc stuff over and over
3. Use `std/options` std prefix for anything from std lib
4. Prefer explicit `./module` import (prefer explicit `./waku_api_tools` - nim path handling is fickle _Originally posted by @arnetheduck in https://github.com/status-im/nim-waku/pull/263#discussion_r527467566_)
5. In general, if imports are big this is a smell that we haven't separated out concerned correctly.

Also see https://github.com/status-im/nim-waku/issues/281

**Comment by arnetheduck** [comment]
re export, the guideline is that any public functions/types should export the corresponding module where the type resides (ie if a type exposes a public Option field, export options)

**Comment by oskarth** [comment]
Better captured elsewhere

**Comment by jm-clius** [comment]
This has been addressed in https://github.com/status-im/nim-waku/issues/639. Closing.
