### ISSUE TITLE
Refactor: Enforce explicit exception handling

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#289]
# Problem

> all modules except those that use async should start with {.push raises: [Defect].} and explicitly list any exceptions they raise

# Notes

See https://github.com/status-im/nimbus-eth2/blob/86348dcb97a0b7d608d4d13c334e03887ea072ef/docs/the_auditors_handbook/src/02.3_correctness_distinct_mutability_effects_exceptions.md#enforcing-exception-handling

and examples https://github.com/status-im/nimbus-eth2/search?q=%7B.push+raises%3A+%5BDefect%5D.%7D

Async macro doesn't currently support this.

Also see https://github.com/status-im/nim-waku/issues/146

**Comment by oskarth** [comment]
@jm-clius wdyt of this one? Should we leave it open for a bit longer? Right now the strategy of just doing it once we touch a namespace seems to make sense to me.

**Comment by jm-clius** [comment]
Agree re our approach. I think leaving this (and the other refactoring issues) open in icebox for a while longer may serve as handy "checklist" for refactoring-as-we-go-along. Could consider consolidating all of these into an actual checklist, especially if more things come up based on [the style guide](https://github.com/status-im/nimbus-eth2/pull/2249) (e.g. [preferring `new*` to `init*` for "constructing" ref objects](https://github.com/status-im/nimbus-eth2/blob/e33b4af4814f1694f1d37e04cb5b8ab9bb73d0f3/docs/the_style_book/src/02_formatting.md#naming-conventions))

**Comment by jm-clius** [comment]
For the most part this has been addressed in https://github.com/status-im/nim-waku/issues/639. Closing.
