### ISSUE TITLE
Handling inputs to a smart contract constructor  using nim-web3

### ISSUE THREAD

**Issue by staheri14** [status-im/nim-waku#323]
## Problem

The problem is about how to deploy a smart contract with its constructor's inputs using nim-web3. 

**Some thoughts**:
The [`EthSend`](https://github.com/status-im/nim-web3/blob/0361338cea1cf0c3999434c349287081ec81c133/web3/ethtypes.nim#L34)  has a [`data`](https://github.com/status-im/nim-web3/blob/0361338cea1cf0c3999434c349287081ec81c133/web3/ethtypes.nim#L40) field which  embodies the compiled code of the contract, probably the constructor's parameters should be passed/encoded as part of the `data` field, like `<smartcontract code><parameters of constructor>` but couldn't find the encoding procedure in the [nim-web3 repo](https://github.com/status-im/nim-web3).

See this file for a sample deployment of a contract: https://github.com/status-im/nim-web3/blob/master/tests/test_utils.nim

**Comment by oskarth** [comment]
I linked issue with similar thoughts. Also upstreamed this so Nimbus team is aware of issue, since it seems like this capability should ideally be provided by nim-web3 library. https://github.com/status-im/nim-web3/issues/33
