### ISSUE TITLE
nim-waku integration in nim-status: potential SQLite conflict

### ISSUE THREAD

**Issue by michaelsbradleyjr** [status-im/nim-waku#329]
Sorry for the length, but I want to give plenty of context so there's less chance of misunderstanding.

To date, the work to integrate nim-waku in nim-status has not proceeded quickly, or very far (yet), because e.g. the nim-status team faced a number of challenges around the decision to integrate [SQLCipher](https://github.com/sqlcipher/sqlcipher), by way of [nim-sqlcipher](https://github.com/status-im/nim-sqlcipher). Also, we're still in the early phases of building a "background task runner" so that, like status-go (which nim-status is intended to replace eventually), work done by the library doesn't interfere with the thread/s of an application using it without some effort by that application's developer/s.

The work on nim-sqlcipher and its integration in nim-status has just wrapped up, but there *may* be an additional hurdle related to a *possible* conflict with nim-waku's usage of [nim-sqlite3-abi](https://github.com/arnetheduck/nim-sqlite3-abi).

I will note that in the past it was suggested that [attention be paid](https://github.com/status-im/nim-waku/pull/247#issuecomment-719461469) to nim-sqlcipher's API design in relation to nim-sqlite3-abi (if I understood correctly). One of the challenges for the nim-status team has been the team's dearth of experience with makefiles, compilers, linkers, and all the concepts and concerns that go along with those things. In addition to slowing us down, that probably led to our underappreciating the future interplay between sqlcipher and sqlite3-abi.

Over the past weekend we realized that SQLite symbols in `libstatus.dll|dylib|so` ([status-go](https://github.com/status-im/status-go) built/linked as a [shared library](https://github.com/status-im/status-go/blob/develop/Makefile#L138)) can conflict with those of `libsqlcipher` linked to nim-status. We were hitting a strange edge case involving Windows; after realizing the nature of the conflict, we confirmed that it can affect other platforms as well, depending on the linking order. I then realized we could face a similar problem once the work to integrate nim-waku into nim-status really takes off. I did some quick experiments and here's what I found:

If `import waku/v2/node/sqlite` is added to our [`db_smoke.nim`](https://github.com/status-im/nim-status/blob/master/test/nim/db_smoke.nim) test, then compilation fails with errors like this: https://gist.github.com/michaelsbradleyjr/37a95e11925cd2338d5efdfe284cb89a.

If `import sqlcipher` is added to our [`waku_smoke.nim`](https://github.com/status-im/nim-status/blob/master/test/nim/waku_smoke.nim) test, compilation succeeds and the test runs successfully.

I'm not certain why it doesn't fail in the latter case, but I'm guessing it's because the test doesn't make direct use of any waku code that uses code from nim-sqlite3-abi, and therefore `sqlite3.c` from nim-sqlite3-abi isn't compiled/linked into the executable.

In another experiment, I combined nim-status' `db_smoke.nim` code with nim-waku's ` tests/v2/test_message_store.nim`. Compilation fails with the same errors seen in my gist linked above.

So, here are some questions:

When integrating nim-waku with nim-status, how *optional* is use of nim-waku's message store? In other words, if nim-status does persistence completely on its own terms (using nim-sqlcipher) will use of nim-waku's APIs be impeded significantly, slightly, not at all?

Depending on the answer to that question, does anyone have ideas as to how nim-status and/or nim-waku and/or nim-sqlcipher can be refactored so that we avoid sqlite-related conflicts?

**Comment by decanus** [comment]
> When integrating nim-waku with nim-status, how optional is use of nim-waku's message store? In other words, if nim-status does persistence completely on its own terms (using nim-sqlcipher) will use of nim-waku's APIs be impeded significantly, slightly, not at all?

Ok so this is problematic, the way the backend works, if 2 nodes are communicating, eg desktop clients are exchanging messages. then one is opened and the other is closed all messages are gone. Because SQL is used for that persistence, theoretically we could probably make it pluggable by adding a message loader interface, you pass a loader to the message store and it imports messages through that loader. This is just me quickly thinking off the top of my head. However, it seems like an overkill to store those encrypted packets in yet another encrypted database. @oskarth wdyt? Additionally we need to consider what affect something like this will have on futher improvements see: https://github.com/status-im/nim-waku/issues/272

**Comment by jm-clius** [comment]
Hi @michaelsbradleyjr, given that a data loader interface was extracted in #350 and the related issue in #334 has been closed, can this issue also be closed?

**Comment by michaelsbradleyjr** [comment]
Closed by #350 🎉.
