### ISSUE TITLE
Data Loader Interface

### ISSUE THREAD

**Issue by decanus** [status-im/nim-waku#334]
# Problem

Currently we have a message store, this uses SQLite to store messages during a nodes lifetime and retrieve them into memory when the node is started. However, this can lead to conflicts with the new nim-status. See: https://github.com/status-im/nim-waku/issues/329.

# Solution

To solve this problem what we should do is abstract the MessageStore in such a way, that an application using nim-waku can provide its own MessageStore which is responsible for saving and retrieving messages. The interface can be relatively simple for now and only needs 2 functions:

```nim
proc put*(db: MessageStore, cursor: Index, message: WakuMessage): MessageStoreResult[void]
proc getAll*(db: MessageStore, onData: DataProc): MessageStoreResult[bool]
```

**Comment by decanus** [comment]
@michaelsbradleyjr

**Comment by michaelsbradleyjr** [comment]
That looks very reasonable to me, looping in @richard-ramos and @emizzle to get their feedback too.

I just did an experiment: I created a database with `nim-sqlcipher` and put some data in it, but didn't call `key` on it (i.e. didn't encrypt it). In that case the db remains a plain sqlite3 database, e.g. can be opened without any problems with the `sqlite3` cli. The point being that the `MessageStore` nim-status passes to nim-waku can be an unencrypted database so we don't unnecessarily encrypt already encrypted messages.

Can you explain the `cursor: Index` part? (showing my ignorance here)

**Comment by decanus** [comment]
@michaelsbradleyjr the `Index` is what we use to store the data, it essentially contains an id and timestamp when the message was received, see: https://github.com/status-im/nim-waku/blob/master/waku/v2/waku_types.nim#L25-L28

It is used for pagination: https://specs.vac.dev/specs/waku/v2/waku-store.html#index, a further improvement we will want to do is make this happen with an SQLite query rather than in the node code, see: https://github.com/status-im/nim-waku/issues/272
