### ISSUE TITLE
Waku metrics return same label multiple times

### ISSUE THREAD

**Issue by jakubgs** [status-im/nim-waku#338]
The metrics endpoint for Prometheus returns multiple entries for the same name and label:
```
 % curl -s localhost:8008/metrics | grep nim_gc_heap_instance_occupied_bytes | sort
nim_gc_heap_instance_occupied_bytes{type_name="AsyncSocket"} 186208.0
nim_gc_heap_instance_occupied_bytes{type_name="Future[system.void]"} 301184.0
nim_gc_heap_instance_occupied_bytes{type_name="Future[system.void]"} 83520.0
nim_gc_heap_instance_occupied_bytes{type_name="TimerCallback"} 132768.0
nim_gc_heap_instance_occupied_bytes{type_name="anon ref object from /app/vendor/nim-chronos/chronos/asyncloop.nim(800, 30)"} 132768.0
nim_gc_heap_instance_occupied_bytes{type_name="seq[Message]"} 311328.0
nim_gc_heap_instance_occupied_bytes{type_name="seq[SelectorKey[asyncloop.SelectorData]]"} 106528.0
nim_gc_heap_instance_occupied_bytes{type_name="seq[StackTraceEntry]"} 355488.0
nim_gc_heap_instance_occupied_bytes{type_name="seq[byte]"} 164832.0
nim_gc_heap_instance_occupied_bytes{type_name="string"} 240678.0
```
As we can see the label `type_name="Future[system.void]"` appears twice. This results in errors when ingesting metrics:
```
level=error
ts=2021-01-05T14:35:26.493847706Z
caller=push.go:47
org_id=fake
traceID=6941c43e885061b4
msg="push error"
err="rpc error: code = Code(400)
  desc = user=fake: sample with repeated timestamp but different value;
    last value: 959088,
    incoming value: 132672 for series {
      __name__=\"nim_gc_heap_instance_occupied_bytes\",
      datacenter=\"gc-us-central1-a\",
      fleet=\"wakuv1.test\",
      group=\",wakuv1.test,nim,waku,metrics,\",
      instance=\"node-01.gc-us-central1-a.wakuv1.test\",
      job=\"nim-waku-v1-metrics\",
      source=\"slave-01.gc-us-central1-a.metrics.hq\",
      type_name=\"Future[system.void]\"
    }"
```

**Comment by jakubgs** [comment]
Oh, it appears the metrics are defined in a separate repo:
https://github.com/status-im/nim-metrics/blob/22a3867341f7b0a9d55661b41d7ee5febe35c86b/metrics.nim#L953-L957

**Comment by jakubgs** [comment]
The names appear to come from `dumpHeapInstances`:
```nim
        for data in dumpHeapInstances():
```
https://github.com/status-im/nim-metrics/blob/22a3867341f7b0a9d55661b41d7ee5febe35c86b/metrics.nim#L942

But not sure exactly where `dumpHeapInstances` is coming from.

**Comment by jakubgs** [comment]
Is `dumpHeapInstances` part of Nim? I can't seem to find it anywhere.

**Comment by jakubgs** [comment]
I can see it being used in another Nim Prometheus library:
https://github.com/dom96/prometheus/blob/eb4d67c1/src/prometheus/collectors/gccollector.nim#L84

**Comment by jakubgs** [comment]
There is a reference to it on Nim forum: https://forum.nim-lang.org/t/5516#34454

But I can't find any declaration/definition/specification.

**Comment by jakubgs** [comment]
The fact that the loop goes over the return value of `dumpHeapInstances` and saves `data.name` and `data.size` indicates that there might be more attributes to `data` that could further distinguish the two `Future[system.void]` values of `data.name`:
```nim
        for data in dumpHeapInstances():
          var smallest = 0
          for i in 1..<heapSizes.len:
            if heapSizes[smallest][1] >= heapSizes[i][1]:
              smallest = i
          if data.sizes > heapSizes[smallest][1]:
            heapSizes[smallest] = (data.name, data.sizes)
```
https://github.com/status-im/nim-metrics/blob/22a3867341f7b0a9d55661b41d7ee5febe35c86b/metrics.nim#L942-L948

So either the first value has to be extended with that different in addition to `name`, or the two values have to be combined.

**Comment by jakubgs** [comment]
If we look at how this is done in the `dom96/prometheus` library it appears to combine all the the values provided by `dumpHeapInstances` into a single metric:
```nim
    var totalAllocated = 0
    for it in dumpHeapInstances():
      a[n] = it
      inc n
      inc totalAllocated, it.sizes

    for i in 0 .. n-1:
      typeHeapUsageGauge.addMetric(
        a[i][2],
        labels={"type": $a[i][0]},
        merge=true
      )
      typeAllocCountGauge.addMetric(
        a[i][1],
        labels={"type": $a[i][0]},
        merge=true
      )
    typeHeapUsageGauge.addMetric(totalAllocated)
```
https://github.com/dom96/prometheus/blob/eb4d67c1/src/prometheus/collectors/gccollector.nim#L83-L100

**Comment by jakubgs** [comment]
Oh wait, they distinguish between two values:
```nim
      typeHeapUsageGauge.addMetric(
        a[i][2],
        labels={"type": $a[i][0]},
        merge=true
      )
      typeAllocCountGauge.addMetric(
        a[i][1],
        labels={"type": $a[i][0]},
        merge=true
      )
```
Both get the value for the `type` label from `a[i][0]`, but one is named `typeHeapUsageGauge` and takes `a[i][2]` as value while the `typeAllocCountGauge` metrics takes `a[i][1]`.

But I don't see anything actually distinguishing between the two `type` values of `Future[system.void]`.

**Comment by jakubgs** [comment]
If I try to print contents of `dumpHeapInstances`:
```nim
for it in dumpHeapInstances():
    echo "Name: ", it.name
    echo "Sizes: ", it.sizes
```
I get back:
```
test.nim(1, 11) Error: undeclared identifier: 'dumpHeapInstances'
```
And if I add:
```nim
when declared(dumpHeapInstances):
```
It does nothing. So I'm clearly missing some flag or setting to make this available.

**Comment by jakubgs** [comment]
Based on help from @stefantalpalaru and this doc: https://nim-lang.org/docs/gc.html
It turns out that availability of `dumpHeapInstances` is dependent on definition of `nimTypeNames`:
```nim
when defined(nimTypeNames):
```
https://github.com/nim-lang/Nim/blob/662c5080755eb5a42df2c3acb84c044876571a46/lib/system/gc_common.nim#L20-L52
Which appears to require the `-d:nimTypeNames` flag when compiling.

**Comment by jakubgs** [comment]
But when I compile my test program with the right flags I get no output:
```
 > nim compile --verbosity:0 -d:nimTypeNames --run test.nim
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
```
Which I guess means that I first need to allocate some stuff to get info about heaps.

**Comment by jakubgs** [comment]
There we go:
```nim
type Thing = object
  a: int
var t = new Thing

for it in dumpHeapInstances():
    echo "Name: ", it.name
    echo "Sizes: ", it.sizes
```
Output:
```
Name: ref Thing
Sizes: 24
```

**Comment by jakubgs** [comment]
At least now since we have the code for `` we can see the format of the values returned from the iterator:
```nim
        yield (it.name, it.instances, it.sizes)
```
https://github.com/nim-lang/Nim/blob/662c5080755eb5a42df2c3acb84c044876571a46/lib/system/gc_common.nim#L51
Which I guess shows that there can be multiple `instances` for a given `type`.

**Comment by jakubgs** [comment]
Yeah, so I don't really get why `Future[system.void]` appears twice instead of showing a `count` of 2:
```nim
type Thing = object
  a: int
var t = new Thing
var u = new Thing

for it in dumpHeapInstances():
    echo it
```
```
(name: "ref Thing", count: 2, sizes: 48)
```

**Comment by jakubgs** [comment]
It might be that the simplest fix would be to just modify `nim-metrics` to just sum up the `sizes` of instances with the same `name`.

**Comment by jakubgs** [comment]
The `count` attribute can be ignored because the `sizes` is already adjusted based on number of instances:
```
(name: "ref Thing", count: 1, sizes: 24)
```
```
(name: "ref Thing", count: 2, sizes: 48)
```

**Comment by jakubgs** [comment]
Warning about this sorting:
```nim
        for data in dumpHeapInstances():
          var smallest = 0
          for i in 1..<heapSizes.len:
            if heapSizes[smallest][1] >= heapSizes[i][1]:
              smallest = i
          if data.sizes > heapSizes[smallest][1]:
            heapSizes[smallest] = (data.name, data.sizes)
```
https://github.com/status-im/nim-metrics/blob/22a3867341f7b0a9d55661b41d7ee5febe35c86b/metrics.nim#L942-L948

Apparently it is "meant to avoid new heap allocations, while parsing the heap for those stats" and it should be probable left as it is, and any de-duplicating should be done after it.

**Comment by jakubgs** [comment]
Not merged or deployed yet, so re-opening.

**Comment by jakubgs** [comment]
Looks like the fix will be merged in https://github.com/status-im/nim-waku/pull/363 instead.

**Comment by jakubgs** [comment]
@jm-clius hey, I'm still seeing the errors for `wakuv2.prod` fleet. Any plans to update the image for that too?
```
Feb 17 07:27:31 master-01.do-ams3.metrics.hq cortex[15442]:
  level=error
  ts=2021-02-17T07:27:31.373233504Z
  caller=push.go:47
  org_id=fake
  traceID=2fccda466e3de348
  msg="push error"
  err="rpc error:
    code = Code(400)
    desc = user=fake: sample with repeated timestamp but different value; last value: 140448, incoming value: 72384 for series 
    {
      __name__=\"nim_gc_heap_instance_occupied_bytes\",
      datacenter=\"gc-us-central1-a\", 
      leet=\"wakuv2.prod\",
      group=\",wakuv2.prod,nim,waku,metrics,\",
      instance=\"node-01.gc-us-central1-a.wakuv2.prod\",
      job=\"nim-waku-v2-metrics\", source=\"slave-01.gc-us-central1-a.metrics.hq\",
      type_name=\"Future[system.void]\"
    }"
```

**Comment by jm-clius** [comment]
Hi @jakubgs, sorry for the slow response - been AFK for a while. I'll bump `.prod` and update here.
