### ISSUE TITLE
Waku v2: Sketch out historic messages API

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#38]
**NOTE: This is the implementation issue for historic messages, for implementation see https://github.com/vacp2p/specs/issues/157**

# Problem

We need a method to retrieve and retrieve messages on archive nodes. This allows a user to find messages sent to them when they were online. In Waku v1 we had the Mailserver design which was inspired by Whisper but was a sub-optimal solution to the problem.

It was problematic for various reasons:
 - It was baked into Waku / Whisper and wasn't some "orthogonal" protocol.
 - Due to it not being "orthogonal" messages were sent to peers normally, meaning they needed to fit envelope sizes constraints etc. making the API rather ugly and making request / response protocols impossible.

# Acceptance Criteria

Design a historic messages node / protocol that runs on-top of Waku v2, meaning requests and responses get wrapped in envelopes. Messages should be transported using protocol buffers. The protocol should be request / response and be able to run on desktop clients.

# Considerations

One thing to consider is how to query these nodes, prior we enabled bloom filter queries along with topics. If we only have topics, users may be leaking more metadata than willing.

# Notes

 - Discussions found in https://github.com/vacp2p/research/issues/38 can be considered relevant.

For prior discussions related to request / response see:
 - https://github.com/vacp2p/specs/pull/116
 - https://github.com/vacp2p/research/issues/24
 - https://github.com/status-im/specs/pull/54#issuecomment-543588052

**Comment by oskarth** [comment]
@decanus created a skeleton issue, please fill out with details as you see fit and we can discuss on Monday

**Comment by decanus** [comment]
https://github.com/vacp2p/specs/pull/116

**Comment by oskarth** [comment]
That's for v1 though, right? Can we update this issue with thinking here?

**Comment by decanus** [comment]
@oskarth, linked this because it will most likely be relevant for v2, like some of the discussions we had related to that issue.

**Comment by oskarth** [comment]
@decanus can you please update the issue to accurately capture the problem, acceptance criteria and related details. If it is too big, split it up so it can be finished on the timeframe of a few days please.

Right now this is issue is not specific enough and might be too big. It is also missing a spec counterpart issue.

**Comment by decanus** [comment]
@oskarth I updated the issue.

**Comment by oskarth** [comment]
Created a separate spec issue so we can discuss spec and implementation separately.

**Comment by oskarth** [comment]
@decanus  can we please make a smaller issue out of this that can be completed over a few days, as opposed to being pending for weeks?

**Comment by oskarth** [comment]
Created a smaller issue https://github.com/status-im/nim-waku/issues/74

**Comment by oskarth** [comment]
What's the overlap or distinction between this and https://github.com/status-im/nim-waku/issues/109 @decanus?

**Comment by oskarth** [comment]
Done ish
