### ISSUE TITLE
Git checkout 300mb, clean it up

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#389]
# Problem

Cloning nim-waku pulls down 300mb.

```
Cloning into 'nim-waku'...
remote: Enumerating objects: 18185, done.
remote: Total 18185 (delta 0), reused 0 (delta 0), pack-reused 18185
Receiving objects: 100% (18185/18185), 302.41 MiB | 11.21 MiB/s, done.
```

Most of it is coming from .git/objects/pack/pack-884f876083f454d719a7f21abdd136f824c102e8.pack in fresh checkout. Possibly previous library accidentally checked it? Couldn't find source of it in short timebox.

# Acceptance criteria

Figure out where it is coming from and prune the tree to make checkout smaller.

**Comment by arnetheduck** [comment]
there are several compiled binaries in the repo that were likely added by accident - both in history and in current checkout - there's no way to get rid of that without rewriting repository history

**Comment by oskarth** [comment]
yeah we might indeed have to rewrite history

**Comment by oskarth** [comment]
Not happening probably, we already have releases
