### ISSUE TITLE
Waku Mail Client implementation part II

### ISSUE THREAD

**Issue by kdeme** [status-im/nim-waku#4]
The Waku (Status Whisper fork) mail client implementation was started here: https://github.com/status-im/nim-eth/pull/141

This issue is about improving the implementation by addressing the many todos (some from review) in the code.

However, that work showed some pain points that could/should be improved but ideally this will require some specification changes:
- To be able to make use of the `requestResponse` mechanism of the DSL the `p2pRequest` packet and the `p2pRequestComplete` packet should have consecutive ids. While it would be possible to alter the DSL to support the current situation, the specification would benefit from having them consecutive, as it would be more clear for implementers that they are a request & response type of message.
- The `p2pRequest` wraps its data structure in a regular Whisper/Waku envelope. The `p2pRequestComplete` does not do this. It would be an improvement if both were wrapped in an envelope, this would make it more consistent and allow for the format to be agnostic for the Waku messaging protocol. Furthermore, if necessary, it would allow for encryption as with regular messages.
- The data structure of `p2pRequestComplete` contains a (custom) requestId. If the `requestResponse` system is used, we would have default access to such system. The `les` protocol already follows such practise: https://github.com/ethereum/devp2p/blob/master/caps/les.md#request-id . It would make sense to work in the same way here, especially if we move that data structure into an envelope, the requestId does not fit on that layer.
- Not a specification change, but rather missing of specification. It is not completely clear in case of P2P message (`p2pRequest`, `p2pRequestComplete`) which validation should be done on the envelope (in second case, there is no envelope..), if any at all.

**Comment by oskarth** [comment]
Also cc @iurimatias for client part
