### ISSUE TITLE
Ensure Protobuf messages are used in publish/subscribe

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#40]
As per PubSub interface and current raw WakuSub spec, we want to pass RPC Messages in publish/subscribe. See https://github.com/vacp2p/specs/blob/8046c3ed4accbde8cbe3606d3f00b68ebcb73963/specs/waku/waku-v2.md#protobuf

Currently, this is supported in nim-libp2p FloodSub/PubSub. However,  while `publish` takes a `seq[byte]` (https://github.com/status-im/nim-waku/blob/master/waku/protocol/v2/waku_protocol.nim#L120) and there is an RPC handler (https://github.com/status-im/nim-waku/blob/master/waku/protocol/v2/waku_protocol.nim#L106), we see that it currently deals with strings in the following in RPC calls:

https://github.com/status-im/nim-waku/blob/master/waku/node/v2/rpc/wakurpc.nim#L24
https://github.com/status-im/nim-waku/blob/master/waku/node/v2/rpc/wakurpc.nim#L24
Node API: https://github.com/status-im/nim-waku/blob/master/docs/api/v2/node.md

These should be generalized, to either `seq[byte]` and/or protobuf message type.

As a sanity check, the quicksim (https://github.com/status-im/nim-waku/blob/master/waku/node/v2/rpc/wakurpc.nim#L24) and/or tests (https://github.com/status-im/nim-waku/blob/master/tests/v2/test_waku.nim) can be adjusted accordingly.

^ @kdeme or @decanus  would either of you be able to take a look at this?

**Comment by oskarth** [comment]
I believe this is blocked by https://github.com/status-im/nim-waku/issues/58, but lets discuss during call

**Comment by oskarth** [comment]
@decanus What's missing or blocking for there to be an end to end test using protobuf?

**Comment by decanus** [comment]
@oskarth this test is probably as end-to-end as it can get in the current architecture: https://github.com/status-im/nim-waku/blob/master/tests/v2/test_waku.nim#L67, it encodes a protobuf, sends it and then decodes it to ensure it works. We can't do the decoding as part of nim-waku yet because we have not specified a message format. See my comment here: https://github.com/status-im/nim-waku/issues/61#issuecomment-663510728.

So i would be happy to close the issue and make one for next steps?
 - eg. A topic handler that returns a specified Message field.
 - Testing that topic handler.

Or am I missing something?

**Comment by oskarth** [comment]
That is a test I wrote a long time ago. The issue states an end to end test that has a protobuf serialization and deserialization step. That is still missing.

When you say message format, you really mean data field in the payload.

There are two levels of tests. One is for `Messages` and other is for `data` field. For the former, this is done in newMessage etc. That format is already specified. You are going to need to do a test like that anyway to get the `HistoryQuery` RPC working end to end.

The other is the data field. This isn't specified yet but it doesn't have to be. This means an end to end test here is an arbitrary protobuf and making sure it works end to end with de/serialization.

The difference between these two when it comes to protobuf is elaborated on in the "decide on protobuf solution" issue linked above.

If you want to cut out an issue for topic handler go ahead

**Comment by oskarth** [comment]
Seems fine for now, we can extend later with RPC message etc. Feel free to create next step issues
