### ISSUE TITLE
Create a Waku-Discord bridge

### ISSUE THREAD

**Issue by jakubgs** [status-im/nim-waku#404]
Currently in order to bridge Status via Waku v1 with Discord and other chat applications we use a [fork of MatterBridge](https://github.com/status-im/matterbridge) with [modification](https://github.com/status-im/matterbridge/commit/b60437d12e958a2f180ba2b371fc087b33df013d) that adds support for Status.

Since MatterBridge is written in Go the integration with `status-go` is easy, but integration with `nim-waku` might be a problem.

**Comment by jakubgs** [comment]
MatterBridge does provide an API plugin:
https://github.com/42wim/matterbridge/wiki/Api

Reference:
https://app.swaggerhub.com/apis-docs/matterbridge/matterbridge-api/0.1.0-oas3

Which does provide a `/stream` path:
![image](https://user-images.githubusercontent.com/2212681/109766634-b859db80-7bf6-11eb-8094-e1ff12aa7745.png)

So either a `wakunode` or some separate binary could provide support for for this API.

**Comment by jm-clius** [comment]
I'll start adding support for this API in `nim-waku` and integrate with the `chat2` app.

**Comment by jakubgs** [comment]
Are you sure you want to build that into the `nim-waku` node? Shouldn't this be a separate binary that talks to a Waku node and relays messages from specific configured chats to this API?

**Comment by jm-clius** [comment]
Agree. It will be a separate binary from the `node` and configured to bridge between a `wakunode` and matterbridge. I will then set this up for `chat2` (i.e. to bridge the default topic on the `test` cluster network).

**Comment by jm-clius** [comment]
blocked by https://github.com/status-im/infra-nim-waku/issues/8

**Comment by oskarth** [comment]
Done

**Comment by Fergulati** [comment]
Hello,

I stumbled across this because currently we only sent Spiff notifications into Status App. Would this allow us to send Spiff notifications into Discord?

**Comment by jakubgs** [comment]
No, because that was for Waku v1. But there is an implementation of Waku v2 for Matterbridge in the works here:

* https://github.com/status-im/matterbridge/pull/1
