### ISSUE TITLE
Cluster nodes should form a (single) network per deployment

### ISSUE THREAD

**Issue by jm-clius** [status-im/nim-waku#408]
Currently there is no peering between [Waku cluster nodes](https://fleets.status.im/) in either the `test` or `prod` deployments. The effect is that peers connecting to separate cluster nodes will essentially be connecting to separate networks (with no messages being relayed between cluster nodes, no shared history, etc.). The expected behaviour is that each Waku cluster forms a single mesh (or at least single network) so that peers can connect to any node in either the `prod` or `test` network and see all messages being relayed on that network.

### Acceptance criteria
Cluster nodes form a single network in their respective deployments (`test` or `prod`).

**Comment by jakubgs** [comment]
A JSON RPC API call that would allow adding new peers would be the best solution, because it would allow us to call that after the nodes have been set up. We could easily script querying Consul for available nodes and then calling the RPC API to inform nodes about available peers.

**Comment by jm-clius** [comment]
Thanks, @jakubgs. I'll go ahead and extend the API with a `connect` method.

**Comment by jm-clius** [comment]
Hi @jakubgs, I've now added a post method to the Admin API that allows adding new peers to a node.
https://github.com/status-im/infra-nim-waku/pull/4 enables the Admin API for Waku v2 nodes

The next step will be to script querying Consul for available nodes and calling the API, but I'm a bit at a lost where to add that to the deployment. The script for adding new peers will look something like this:

```
script: 'curl -s -X POST -H Content-type:application/json --data {"jsonrpc":"2.0","method":"post_waku_v2_admin_v1_peers","params":[[<extracted_peer_multiaddr1>,<extracted_peer_multiaddr2>]],"id":1} http://localhost:{{ nim_waku_rpc_tcp_port }}/'
```

**Comment by jakubgs** [comment]
Done in https://github.com/status-im/infra-nim-waku/commit/ab972182, appears to work:
```
admin@node-01.do-ams3.wakuv2.test:~ % /docker/nim-waku-v2/rpc.sh get_waku_v2_admin_v1_peers
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": [
    {
      "multiaddr": "/ip4/104.154.239.128/tcp/30303/p2p/16Uiu2HAmJb2e28qLXxT5kZxVUUoJt72EMzNGXB47Rxx5hw3q4YjS",
      "protocol": "/vac/waku/relay/2.0.0-beta2",
      "connected": true
    },
    {
      "multiaddr": "/ip4/134.209.139.210/tcp/30303/p2p/16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ",
      "protocol": "/vac/waku/relay/2.0.0-beta2",
      "connected": false
    },
    {
      "multiaddr": "/ip4/47.242.210.73/tcp/30303/p2p/16Uiu2HAmSyrYVycqBCWcHyNVQS6zYQcdQbwyov1CDijboVRsQS37",
      "protocol": "/vac/waku/relay/2.0.0-beta2",
      "connected": true
    }
  ],
  "error": null
}
```
I also took this opportunity to:

- https://github.com/status-im/infra-nim-waku/commit/b75c5c59 - nim-waku: add rpc.sh for easier JSON RPC calls
- https://github.com/status-im/infra-nim-waku/commit/e6d589d7 - nim-waku: move Docker Compose to a template

I assume that the fact that we include our own enode multiaddress in the call isn't a problem.

**Comment by jm-clius** [comment]
Thanks. This is great.
