### ISSUE TITLE
`post_waku_v2_relay_v1_message` only take hex string

### ISSUE THREAD

**Issue by D4nte** [status-im/nim-waku#415]
In the [specs](https://github.com/vacp2p/specs/blob/c9a305ad97eb632c553efecfc475ce30e09b0342/specs/waku/v2/waku-v2-rpc-api.md#L136), it is not clear that the `payload` can only be a hex string.

The following error is returned from the RPC if an arbitrary string is passed:

```
{
  jsonrpc: '2.0',
  id: 1,
  result: null,
  error: {
    code: -32000,
    id: 1,
    message: 'post_waku_v2_relay_v1_message raised an exception',
    data: 'When marshalling from JSON, parameter "payload" is not valid as a hex data "VGhpcyBpcyBhIG1lc3NhZ2Uu"'
  }
}
```

Could you please either allow arbitrary strings to be passed or clarify the spec?

Also, if the only accepted format is hex, then it sounds odd to force the user to pass the `0x` prefix:

```
{
  jsonrpc: '2.0',
  id: 1,
  result: null,
  error: {
    code: -32000,
    id: 1,
    message: 'post_waku_v2_relay_v1_message raised an exception',
    data: 'When marshalling from JSON, parameter "payload" is not valid as a hex data "546869732069732061206d6573736167652e"'
  }
}
```

`546869732069732061206d6573736167652e` is valid hex data. Forcing the `0x` prefix is useful when the field can have different formats (hex, base64, base58, utf-8, etc). In this instance the `0x` prefix can help processing the data by indicating it's encoded in hex.

However, if hex if the only supported format then it just makes the API more difficult to use.

**Comment by jm-clius** [comment]
@D4nte, this issue should now be addressed:
#428 should make the use of the `0x` prefix optional in JSON-RPC calls
vacp2p/specs#307 should clarify the specs
Feel free to close once you've tested the changes.

**Comment by jm-clius** [comment]
@D4nte, can this issue be closed?

**Comment by D4nte** [comment]
> @D4nte, can this issue be closed?

Sorry for the delay, I am trying it out now.
