### ISSUE TITLE
libp2p/identify message does not contain protocols field

### ISSUE THREAD

**Issue by D4nte** [status-im/nim-waku#419]
There is a known [issue](https://github.com/vacp2p/waku-web-chat/blob/master/patches/waku-hack-identify-peer-proto-manual.patch) with the usage of the identify protocol.

My findings are slightly different that what @oskarth's patch insinuates.

The identify message is [defined in the specs](https://github.com/libp2p/specs/tree/master/identify#the-identify-message) as follow:

```
message Identify {
  optional string protocolVersion = 5;
  optional string agentVersion = 6;
  optional bytes publicKey = 1;
  repeated bytes listenAddrs = 2;
  optional bytes observedAddr = 4;
  repeated string protocols = 3;
}
```

It is defined in [js-libp2p](https://github.com/libp2p/js-libp2p/blob/master/src/identify/message.js) as follow:

```
message Identify {
  optional string protocolVersion = 5; // e.g. ipfs/1.0.0
  optional string agentVersion = 6; // e.g. go-ipfs/0.1.0
  optional bytes publicKey = 1;
  repeated bytes listenAddrs = 2;
  optional bytes observedAddr = 4;
  repeated string protocols = 3;
  optional bytes signedPeerRecord = 8;
}
```

When extracting the message sent by nim-waku, my findings are:

```
publicKey <Buffer 08 02 12 21 03 63 c0 e2 6a ca 55 44 e8 85 6d 29 67 88 5b 9c e6 5b f3 64 12 1f 7d 78 ec 6c 2c 42 6d 46 d2 94 ac>
listenAddrs [ <Buffer 04 7f 00 00 01 06 f2 7c> ]
protocols []
observedAddr <Buffer 04 7f 00 00 01 06 ab 79>
signedPeerRecord null
```

The `signedPeerRecord` is not present. IMHO, it is ok because this field does not exist in the libp2p specs and is marked as `optional` in js-libp2p.

IMO, the actual issue is that the `protocols` field is empty. Which means that js-waku does not seem to nim-waku as a peer under the waku protocol. This leads to message exchange issues (ie, this [test](https://github.com/status-im/js-waku/blob/548c50668ae211bafc7c4a9a33f734d6791a7e94/src/lib/node.spec.ts#L99) fails without a patch).

I would expect the protocol field to at least include `/vac/waku/relay/2.0.0-beta2`.

**Comment by dryajov** [comment]
This seems to be a bug in `nim-libp2p`, we don't seem to be sending this info which should be read from the multistreamselect protocol and sent along the identify message. A quick workaround would be to set the protocols directly on the `switch.peerInfo.protocols` field.

**Comment by dryajov** [comment]
Here is a fix - https://github.com/status-im/nim-libp2p/pull/546

**Comment by D4nte** [comment]
@jm-clius Assigning to you as discussed. Looks like just need to update nim-libp2p dep now. Thanks @dryajov !

**Comment by jm-clius** [comment]
Should be done in #424 👍

**Comment by D4nte** [comment]
This is unfortunately not resolved.
I updated nim-waku to 4ae1cd4737dacdd30f879eea199e0a89a9c1532e, delete the `build` folder and ran `make wakunode2`). Let me know if I missed a step.

When running the test, I receive the following identify message from nim-waku:

Raw protobuf data:
```
{
  "type": "Buffer",
  "data": [
    10,
    37,
    8,
    2,
    18,
    33,
    3,
    20,
    239,
    96,
    25,
    167,
    255,
    237,
    122,
    7,
    207,
    32,
    23,
    20,
    253,
    164,
    79,
    105,
    208,
    165,
    29,
    127,
    127,
    172,
    154,
    79,
    202,
    58,
    41,
    36,
    198,
    166,
    209,
    18,
    8,
    4,
    127,
    0,
    0,
    1,
    6,
    235,
    24,
    34,
    8,
    4,
    127,
    0,
    0,
    1,
    6,
    147,
    201,
    42,
    10,
    105,
    112,
    102,
    115,
    47,
    48,
    46,
    49,
    46,
    48,
    50,
    16,
    110,
    105,
    109,
    45,
    108,
    105,
    98,
    112,
    50,
    112,
    47,
    48,
    46,
    48,
    46,
    49
  ]
}
```

Decode data:
```
{
  "publicKey": {
    "type": "Buffer",
    "data": [
      8,
      2,
      18,
      33,
      3,
      20,
      239,
      96,
      25,
      167,
      255,
      237,
      122,
      7,
      207,
      32,
      23,
      20,
      253,
      164,
      79,
      105,
      208,
      165,
      29,
      127,
      127,
      172,
      154,
      79,
      202,
      58,
      41,
      36,
      198,
      166,
      209
    ]
  },
  "listenAddrs": [
    {
      "type": "Buffer",
      "data": [
        4,
        127,
        0,
        0,
        1,
        6,
        235,
        24
      ]
    }
  ],
  "observedAddr": {
    "type": "Buffer",
    "data": [
      4,
      127,
      0,
      0,
      1,
      6,
      147,
      201
    ]
  },
  "protocolVersion": "ipfs/0.1.0",
  "agentVersion": "nim-libp2p/0.0.1",
  "protocols": [],
  "signedPeerRecord": null
}
```

**Comment by jm-clius** [comment]
Hi @D4nte, have you tried deleting the `vendor` folder and/or running `make update`?

**Comment by D4nte** [comment]
I thought I did but apparently not, bug is now fixed!
