### ISSUE TITLE
MessageIdProvider is not configured

### ISSUE THREAD

**Issue by richard-ramos** [status-im/nim-waku#420]
https://github.com/status-im/nim-waku/blob/b3208b343f35baebd2adea0da28bc9bf664d45ee/waku/v2/protocol/waku_relay.nim#L40

If `anonimyze` is set to true to not use an author in the message, a message id function should be provided, otherwise it will use the default message id which will return an incorrect message Id as seen in this function:

```nim
func defaultMsgIdProvider*(m: Message): MessageID =
  let mid = 
    if m.seqno.len > 0 and m.fromPeer.data.len > 0:
      byteutils.toHex(m.seqno) & $m.fromPeer
    else:
      # This part is irrelevant because it's not standard,   <----------------------------------
      # We use it exclusively for testing basically and users should  <--------------------
      # implement their own logic in the case they use anonymization <-----------------
      $m.data.hash & $m.topicIDs.hash   <------------------------------------------------------
  mid.toBytes()
  ```

A suggestion from @dryajov is to use a similar approach to eth2 which is to hash the message and use that as the messageId

This is the function used in nimbus
```nim
func gossipId(data: openArray[byte], valid: bool): seq[byte] =
  # https://github.com/ethereum/eth2.0-specs/blob/v1.0.0/specs/phase0/p2p-interface.md#topics-and-messages
  const
    MESSAGE_DOMAIN_INVALID_SNAPPY = [0x00'u8, 0x00, 0x00, 0x00]
    MESSAGE_DOMAIN_VALID_SNAPPY = [0x01'u8, 0x00, 0x00, 0x00]
  let messageDigest = withEth2Hash:
    h.update(
      if valid: MESSAGE_DOMAIN_VALID_SNAPPY else: MESSAGE_DOMAIN_INVALID_SNAPPY)
    h.update data

  result = newSeq[byte](20)
  result[0..19] = messageDigest.data.toOpenArray(0, 19)

func msgIdProvider(m: messages.Message): seq[byte] =
  try:
    let decoded = snappy.decode(m.data, GOSSIP_MAX_SIZE)
    gossipId(decoded, true)
  except CatchableError:
    gossipId(m.data, false)
 ```

**Comment by D4nte** [comment]
Maybe worth referring the gossip-sub [specs](https://github.com/libp2p/specs/blob/master/pubsub/README.md#signature-policy-options under) `StrictNoSign option`:

> A `message_id` function will not be able to use the above fields [`signature`, `key`, `from` and `seqno`], and should instead rely on the data field. A commonplace strategy is to calculate a hash.

FYI, js-libp2p implementation hashes the data as you suggested:

https://github.com/libp2p/js-libp2p-interfaces/blob/2429e7246fc6111a5e99b5e97440a91451d64ac6/src/pubsub/utils.js#L43

**Comment by oskarth** [comment]
How big of a problem is this @richard-ramos? Not currently something we are prioritizing
