### ISSUE TITLE
waku-relay: Messages are not processed when following `StrictNoSign` signature policy

### ISSUE THREAD

**Issue by D4nte** [status-im/nim-waku#422]
As per the [waku-relay specifications](https://github.com/vacp2p/specs/blob/a5c137002fb4dca401bf355546dbce1ff685132f/specs/waku/v2/waku-relay.md#L127), the `StrictNoSign` signature policy MUST be applied.

The `StrictNoSign` policy [states](https://github.com/libp2p/specs/tree/master/pubsub#signature-policy-options):

> On the producing side:
>   - Build messages without the signature, key, from and seqno fields.
>   - The corresponding protobuf key-value pairs are absent from the marshalled message, not just empty.
>
> On the consuming side:
>   - Enforce the fields to be absent, reject otherwise.
>   - Propagate only if the fields are absent, reject otherwise.
>   [...]

However, nim-waku is not able to process messages that follow the `StrictNoSign` policy.

Please find logs for both scenarios attached.

[strict_no_sign.log](https://github.com/status-im/nim-waku/files/6145819/strict_no_sign.log)
[strict_sign.log](https://github.com/status-im/nim-waku/files/6145820/strict_sign.log)

## js-libp2p Message samples

`StrictSign` signature policy: signature, key, from and seqno fields are present.
```
msgOBject {
  receivedFrom: 'QmcJAdina6KpaAbcAXnA6NzpSv3VoWoS344y3MSES5dh2y',
  data: Uint8Array(23) [
     10,  17, 84, 104, 105, 115,  32,
    105, 115, 32,  97,  32, 109, 101,
    115, 115, 97, 103, 101,  16,   1,
     24,   0
  ],
  topicIDs: [ '/waku/2/default-waku/proto' ],
  from: 'QmcJAdina6KpaAbcAXnA6NzpSv3VoWoS344y3MSES5dh2y',
  seqno: <Buffer d4 02 3c e4 64 ab 2b d1>,
  signature: <Buffer cf 47 80 d3 91 9c d0 03 08 6c a5 38 2a a3 3b 63 66 92 1f fe 83 7f 86 ac 99 e1 9a 7c 1c ff b2 c0 5a 80 c7 aa 0e 03 ab 10 36 3b 27 bf 67 f3 f0 15 97 58 ... 206 more bytes>,
  key: Uint8Array(299) [
      8,   0,  18, 166,   2,  48, 130,   1,  34,  48,  13,   6,
      9,  42, 134,  72, 134, 247,  13,   1,   1,   1,   5,   0,
      3, 130,   1,  15,   0,  48, 130,   1,  10,   2, 130,   1,
      1,   0, 220, 136, 245, 208, 123, 224, 163, 244, 153, 220,
    133, 240,  56, 100, 197,  83,  54, 177, 114, 165, 159,  98,
      3,  98, 112, 216, 167, 250, 128, 110,  12,  41, 177, 230,
     90,  96,  63, 161, 187, 181,  20, 240,  95, 166, 245, 161,
    124, 175, 145,  95, 221, 139,  42,  39, 193,  51, 199,  70,
    239, 108, 125,  66,
    ... 199 more items
  ]
}
```

`StrictNoSign` signature policy: signature, key, from and seqno fields are absent.
```
msgOBject {
  receivedFrom: 'QmWuk12TGDGUPeTAxSEjXVNqS7NfG9LXFu3UgWs1LV4nez',
  data: Uint8Array(23) [
     10,  17, 84, 104, 105, 115,  32,
    105, 115, 32,  97,  32, 109, 101,
    115, 115, 97, 103, 101,  16,   1,
     24,   0
  ],
  topicIDs: [ '/waku/2/default-waku/proto' ]
}
```

## nim-waku message sample

For reference, messages sent by nim-waku do follow the `StrictNoSign` policy: signature, key, from and seqno fields are absent.

Note they show as null below. I am uncertain whether it is due to the js `protons` library or because the field are indeed encoded in the protobuf message. It would be worth double checking this aspect.

```
{
  "data": {
    "type": "Buffer",
    "data": [
      10,
      24,
      72,
      101,
      114,
      101,
      32,
      105,
      115,
      32,
      97,
      110,
      111,
      116,
      104,
      101,
      114,
      32,
      109,
      101,
      115,
      115,
      97,
      103,
      101,
      46,
      16,
      1,
      24,
      0
    ]
  },
  "topicIDs": [
    "/waku/2/default-waku/proto"
  ],
  "from": null,
  "seqno": null,
  "signature": null,
  "key": null,
  "receivedFrom": "16Uiu2HAmJkgmhWdChoxaP2oEpwaf8drsxDyBcLJEBkmy5S173rvX"
}

```

**Comment by D4nte** [comment]
Please use critical thinking on this one, I am facing some issues with js-lib2p too and havent concluded my investigation.

**Comment by D4nte** [comment]
FYI https://github.com/ChainSafe/js-libp2p-gossipsub/issues/151

**Comment by dryajov** [comment]
Why are you using chainsafes gossipsub?

**Comment by D4nte** [comment]
> Why are you using chainsafes gossipsub?

What alternative are you suggesting?

**Comment by dryajov** [comment]
> > Why are you using chainsafes gossipsub?
> 
> What alternative are you suggesting?

Hmm, looks like it is the official implementation after all - nevermind.

**Comment by oskarth** [comment]
This is how StrictNoSign was "implemented" in nim-waku, perhaps there is more to it? @sinkingsugar do you have any idea?

https://github.com/status-im/nim-waku/blob/41fe4395a8acbe2f622cf81256478b1471d4de6c/waku/v2/protocol/waku_relay.nim#L38-L42

**Comment by sinkingsugar** [comment]
Hmm reading the trace I see no flaw in the protobuf decoding, the message was empty.

Now for the encoding, we skip missing/omitted fields
```nim
proc encodeMessage*(msg: Message, anonymize: bool): seq[byte] =
  var pb = initProtoBuffer()
  if len(msg.fromPeer) > 0 and not anonymize:
    pb.write(1, msg.fromPeer)
  pb.write(2, msg.data)
  if len(msg.seqno) > 0 and not anonymize:
    pb.write(3, msg.seqno)
  for topic in msg.topicIDs:
    pb.write(4, topic)
  if len(msg.signature) > 0 and not anonymize:
    pb.write(5, msg.signature)
  if len(msg.key) > 0 and not anonymize:
    pb.write(6, msg.key)
  pb.finish()

  when defined(libp2p_protobuf_metrics):
    libp2p_pubsub_rpc_bytes_write.inc(pb.getLen().int64, labelValues = ["message"])
  
  pb.buffer
```

That said when we implemented anonymize there was no official spec yet. But it seems to fit.

**Comment by sinkingsugar** [comment]
Also I'm assuming you setup the libp2p switch with `anonymize` and such.

`-d:libp2p_pubsub_anonymize=true`
`-d:libp2p_pubsub_sign=false`
`-d:libp2p_pubsub_verify=false`

**Comment by D4nte** [comment]
> Also I'm assuming you setup the libp2p switch with `anonymize` and such.
> 
> `-d:libp2p_pubsub_anonymize=true`
> `-d:libp2p_pubsub_sign=false`
> `-d:libp2p_pubsub_verify=false`

Is this comment for nim-waku or js-waku?

**Comment by sinkingsugar** [comment]
that's compile flags for `nim-libp2p` so that applies to the nim side.

**Comment by jm-clius** [comment]
> Also I'm assuming you setup the libp2p switch with `anonymize` and such.
> 
> `-d:libp2p_pubsub_anonymize=true`
> `-d:libp2p_pubsub_sign=false`
> `-d:libp2p_pubsub_verify=false`

This is a "yes" from [the `nim-waku` side](https://github.com/status-im/nim-waku/blob/master/waku/v2/protocol/waku_relay.nim#L35-L42)

**Comment by D4nte** [comment]
After further investigation, the issue is on js-waku side.

When `StrictSign` is enabled, then the message has a `from` field. this allows the nim-waku peer to be added to the `tosend` set at https://github.com/ChainSafe/js-libp2p-gossipsub/blob/12626e863075d5fb1ef88cfed36b72c3b70cdf0f/ts/index.ts#L1038

When `StrictNoSign` is enabled, the `from` field is absent and the peer not added.

Now, I need to review what conditions should be trigger to have the message sent to nim-waku peer.
