### ISSUE TITLE
Waku v2 Websocket support

### ISSUE THREAD

**Issue by D4nte** [status-im/nim-waku#434]
# Problem

Currently, libp2p only [supports](https://libp2p.io/implementations/) websockets and webrtc in the browser. We decided to start with websockets.

As nim-waku is the intended waku full node, browser client needs a way to connect to nim-waku nodes. 

Additionally, as described in https://github.com/status-im/js-waku/issues/50, the websocket connections needs to be wrapped in TLS. As modern browsers simply block insecure websocket connection within an https page.

My understanding is that the intent of nim-waku is to be ran by the community to run a network. Thus, it should be consider how one can easily deployed nim-waku with wss enabled (certificate generation, etc).

# Acceptance criteria

- [x] Ensure nim-waku can be run with Websockets and connect with js-waku
- [x] Ensure this works with wss enabled
- [x] Deploy and test with `test fleet`
- [x] Relevant spec changes as a new capability for Waku (https://github.com/vacp2p/rfc/issues/458)
- [x] Add a basic tutorial to docs folder explaining how  to setup a node with wss enabled (e.g. a couple of openssl command lines to generate an ip certificate).
 
# References

- nim websockets library: https://github.com/status-im/nim-ws/pull/5
- nim-libp2p websockets support: https://github.com/status-im/nim-libp2p/issues/407

**Comment by jm-clius** [comment]
I might be missing something, but it doesn't look like this is integrated in nim-libp2p yet?

Tracking issue there: https://github.com/status-im/nim-libp2p/issues/407

**Comment by jm-clius** [comment]
blocked-by status-im/nim-libp2p#407

**Comment by D4nte** [comment]
Sorry about that, I jumped the gun!

**Comment by jm-clius** [comment]
Unassigning myself here for now to clean up some issues. Feel free to ping me once this is unblocked/becomes a priority.

**Comment by D4nte** [comment]
Please note I updated the description to include wss.

**Comment by D4nte** [comment]
nim-libp2p is ready: https://github.com/status-im/nim-libp2p/issues/407#issuecomment-908941368.

**Comment by oskarth** [comment]
Probably good for a new hire

**Comment by oskarth** [comment]
@rshiv I think OP still has some open items for this to be closed.

Feel free to break out individual items into their own issues - in general the more granular (while still being useful on its own) the better

**Comment by rshiv** [comment]
All the task related to web-sockets is achieved including test in the fleets. 
However, I want to mention an issue in websock which might cause the fleets to go unpredictable and crash for websocket address, https://github.com/status-im/nim-websock/issues/79.

**Comment by D4nte** [comment]
Awesome news. Yes, will review, tracking with https://github.com/status-im/js-waku/issues/327.
Will open new issues if I encounter any bug.
