### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#44]
Not sure when this started yet, but `make wakunode2` etc stopped working.

> Building: build/wakunode2
[NimScript] exec: nim c --out:build/wakunode -d:chronicles_log_level=TRACE --verbosity:0 --hints:off -d:usePcreHeader --passL:"-lpcre" -d:release waku/node/v2/wakunode.nim
/home/oskarth/git/github.com/status-im/nim-waku/vendor/nim-libp2p/libp2p/crypto/secp.nim(136, 18) Error: type mismatch: got <SkPublicKey>
but expected one of: 
template `?`[T; E](self: Result[T, E]): T
  first type mismatch at position: 1
  required type for self: Result[?.T, ?.E]
  but expression 'toPublicKey(SkSecretKey(key))' is of type: SkPublicKey

expression: ?toPublicKey(SkSecretKey(key))
stack trace: (most recent call last)
/home/oskarth/git/github.com/status-im/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/nimscript.nim(416, 18)
/home/oskarth/git/github.com/status-im/nim-waku/waku.nimble(59, 15) wakunode2Task
/home/oskarth/git/github.com/status-im/nim-waku/waku.nimble(33, 8) buildBinary
/home/oskarth/git/github.com/status-im/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/nimscript.nim(260, 7) exec
/home/oskarth/git/github.com/status-im/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/nimscript.nim(260, 7) Error: unhandled exception: FAILED: nim c --out:build/wakunode -d:chronicles_log_level=TRACE --verbosity:0 --hints:off -d:usePcreHeader --passL:"-lpcre" -d:release waku/node/v2/wakunode.nim [OSError]
make: *** [Makefile:80: wakunode2] Error 1

**Comment by oskarth** [comment]
It works fine in `e5051b2` so my guess is that it was introduced in https://github.com/status-im/nim-waku/commit/181889dcd8c417af62b4589decaef7d8b36f5bd8

@kdeme can you take a look?

Also CI seems broken as this should never have been merged with Waku v2 node compile/tests failing.

**Comment by kdeme** [comment]
Fixed in https://github.com/status-im/nim-waku/pull/45
