### ISSUE TITLE
Does not GRAFT after receiving subscription

### ISSUE THREAD

**Issue by D4nte** [status-im/nim-waku#443]
# Scenario

[no_graft_after_subscribe.log](https://github.com/status-im/nim-waku/files/6225335/no_graft_after_subscribe.log)

## Steps:

1. js node dials nim node
2. nim node sends subscription message to js node
3. js node sends subscription message to nim node

### 4. Expected

nim node sends graft message to js node to inform that nim node added js node to local mesh for default topic

### 4. Actual

No further processing is done. From my logs, the subscription has been received at
`TRC 2021-03-30 10:47:14.497+11:00 peer subscribed to topic`
but nothing happens until nim waku is killed at
`nim-waku 4093597 getting SIGINT at 10:47:19 am` (5 seconds).

# Notes

## Heartbeat

What is the heartbeat configuration for nim-waku? Is the issue that the graft message is sent at heartbeat time but I do not leave enough time for it to happen?

## Subscribe before identify

In the attached logs, we can see that nim-waku sends the subscription message at
`TRC 2021-03-30 10:47:14.443+11:00 sending msg to peer  topics="libp2p pubsubpeer" tid=4093597 file=pubsubpeer.nim:237 peer=QmS*x2SoN8 rpcMsg="(subscriptions: @[(subscribe: true, topic: \"/waku/2/default-waku/proto\")], messages: @[], control: (ihave: @[], iwant: @[], graft: @[], prune: @[]))"
`.

However, the dial did not really finish at this stage as we can see the identify protocol still happening after:

```
DBG 2021-03-30 10:47:14.444+11:00 decodeMsg: decoded message                 topics="libp2p identify" tid=4093597 file=identify.nim:94 pubkey="RSA ke...10001\n" addresses="@[/ip4/127.0.0.1/tcp/46819, /ip4/192.168.178.251/tcp/46819]" protocols="@[\"/libp2p/circuit/relay/0.1.0\", \"/ipfs/id/1.0.0\", \"/ipfs/id/push/1.0.0\", \"/ipfs/ping/1.0.0\", \"/vac/waku/relay/2.0.0-beta2\"]" observable_address=Some(/ip4/127.0.0.1/tcp/64140/p2p/16Uiu2HAmPRqSvBdczSQYjqA4FnF4DXVhttHkhbQk2dU93xdJwPD9) proto_version="Some(\"ipfs/0.1.0\")" agent_version="Some(\"js-libp2p/0.30.10\")"
TRC 2021-03-30 10:47:14.444+11:00 identified remote peer                     tid=4093597 file=upgrade.nim:80 conn=QmS*x2SoN8:6062670231038b2d390eebe6 peerInfo="(peerId: \"QmSTjj31KM9GrLA4SUho397RsfJ781FhppUPmSuLx2SoN8\", addrs: @[\"/ip4/127.0.0.1/tcp/46819\", \"/ip4/192.168.178.251/tcp/46819\"], protocols: @[\"/libp2p/circuit/relay/0.1.0\", \"/ipfs/id/1.0.0\", \"/ipfs/id/push/1.0.0\", \"/ipfs/ping/1.0.0\", \"/vac/waku/relay/2.0.0-beta2\"], protoVersion: \"ipfs/0.1.0\", agentVersion: \"js-libp2p/0.30.10\")"
```

As the identify is not yet done when nim waku sends a subscribe to js waku, I believe it is dropped simply because js waku does not know yet that nim waku supports the waku relay protocol.

**Comment by jm-clius** [comment]
Mmm, this seems more of a question for `nim-libp2p`. Both `subscribe` and `identify` resides there, as well as dialing behaviour. Do you mind if we move the issue there?

**Comment by D4nte** [comment]
Created https://github.com/status-im/nim-libp2p/issues/554

Would you need to clarify what version of nim-libp2p you use and the parameters?

**Comment by jm-clius** [comment]
@D4nte, I believe this should now be fixed. Once you are happy that the heartbeat now works as expected we can close this issue.

**Comment by D4nte** [comment]
I'll close once I checked after my current task.

**Comment by jm-clius** [comment]
@D4nte, I think this can now be closed?

**Comment by D4nte** [comment]
Fixed
