### ISSUE TITLE
Change `contentTopic` type back to `string`

### ISSUE THREAD

**Issue by jm-clius** [status-im/nim-waku#447]
### Background

In Waku v2, `contentTopic` was changed from a `string` to an `int32` to enable easy mapping to Waku v1 topics (4-byte arrays). However, this has reduced the usability of the `contentTopic`-field in a number of ways:

1. Integers are less user-friendly/readable than strings, especially for API calls (e.g. publishing on "my/content/topic" using the JSON-RPC API is easier than publishing on some hash of that).
2. Namespacing will be easier implemented for strings (see https://github.com/vacp2p/specs/issues/227).
3. A 4-byte space is not wide enough for applications requiring a large amount of content topics (e.g. WalletConnect want to use 32-byte hex strings as content topics).

### Suggestion

Revert to a `string` representation for `contentTopic` as set out by @oskarth [here](https://github.com/vacp2p/specs/issues/227#issue-731115095). Individual applications of the Waku protocol can then design their contentTopics according to their own requirements. 

### What about bridging to V1?
Bridging to Waku v1 is one application of the Waku protocol, so shouldn't dictate the protocol design but rather how it's implemented. It has a requirement to have 4-byte topics, which can neatly fit into the above paradigm by [introducing namespacing](https://github.com/vacp2p/specs/issues/227).

cc @oskarth for comments

**Comment by oskarth** [comment]
Agree with OP, main question for me is what was set out in https://github.com/vacp2p/rfc/issues/227#issuecomment-811625966  (1) Core's POV (2) How strict/freeform we want namespaces to be

**Comment by jm-clius** [comment]
I commented on vacp2p/rfc#227, but in summary:
(1) I don't think Core has specific use cases in mind (yet), though I still think this will be a useful feature when designing new features. We can probably spec namespacing in a way that already suggests possible use cases.
(2) I think we should provide optional support for namespacing but make it mandatory for certain applications within our control, the most obvious one being the bridging-to-V1 use case.

**Comment by oskarth** [comment]
See https://github.com/vacp2p/rfc/pull/335

Any chance we could do this soon @jm-clius? Might help with interop and WalletConnect use case

**Comment by oskarth** [comment]
Is there something left on this issue @jm-clius?

**Comment by jm-clius** [comment]
Merged and tested. Closing issue.
