### ISSUE TITLE
Investigate if message confirmations are necessary (half-open sockets when publishing from mobile?)

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#448]
# Problem

In Waku v1 there are message confirmations https://rfc.vac.dev/spec/6/#batch-ack-and-message-response

This was introduced to address the following problem:

> The issue is that devp2p is fire and forget, meaning, if I send a message, there's no confirmation that's received on the other end.
> Most of the times this is fine, especially with high availability nodes, but when it comes to mobile that's problematic.
> A mobile connection will often suddenly go offline, resulting in a half-open sockets. 
> This means that if  you lose connectivity, and the user sends a message, we have no way to detect that the message was not 
actually sent (you can happily write on the socket, and no error will be thrown, until the connection is detected to be dead).
> Libp2p might have different semantics and that might not be an issue, that I don't know.
> A keepalive won't help much (I believe we have a 30s keepalive), as we can't set it too aggressive for the feedback we want to give to the user (you send a message, you expect the message to be confirmed within 1/2 seconds, and I don't think we want to set a keepalive that low).
> Of course we can remove it, but that would mean removing a feature essentially, as we rely on it, both to give feedback to the user and for automatic resending of messages 
> This applies both to unicast and broadcast messages, though with broadcast messages is the only way we can confirm a message has reached the network, while we have e2e on unicast, but they server a different purpose.

We have not yet ported this to Waku v2, with the (possibly faulty) assumption that message confirmations are a bit hacky and not necessarily needed, as well that it goes against the philosophy of a gossip network in terms of traffic amplification etc. However, we haven't tested this assumption and not paid enough attention to mobile failure modes.

I believe this behavior may also be used by the Status app to provide the first "tick" (second being end to end ack).

It seems to me that libp2p in general should be more robust w.r.t these types of failure modes in terms of transmitting data reliability, but it could be an inescapable reality that comes from running on mobile and using e.g. TCP as transport (perhaps things looks different with QUIC?).

It'd be good to get confirmation from people who know better whether this is a probably in libp2p or not.

cc @dryajov @sinkingsugar @jm-clius

# Acceptance criteria

Understanding of if this failure mode is still the case, if it can be mitigated in some way. If not, an issue describing next steps for message confirmations.

**Comment by oskarth** [comment]
This also somewhat relates to issue of sender generated timestamp https://github.com/vacp2p/rfc/issues/219 in terms of possibly rejecting some messages. Though Waku v2 doesn't have PoW, so the picture is a bit different...

**Comment by sinkingsugar** [comment]
Well, while the protocol is definitely reliable, currently TCP, there is no way to know what other nodes receive, so if 100% accuracy is required an ack is absolutely necessary.
Specifically even if we publish via gossip and we know for sure that the peer was included in the publish directly (which is not always the case), what happens on the remote side is obviously an unknown. Might be stuck in a queue, etc.

Specially with mobile devices there are lot of things to take care of indeed, like changing IP address etc, which we don't support directly. Of course with epidemic algorithms like gossip messages might linger enough for the receiver to pick it up but again there is no way to know for sure if the connection with the remote was lost before or after receiving something, specially from outside libp2p (some complex heuristics could be cooked up inside it). 

I understand that the question is more on the sender side but like a said before awaiting publish has no meaning in this case.
The actual sending happens asynchronously, at some undefined point.

In details for now we just log and close a failure:
https://github.com/status-im/nim-libp2p/blob/df497660bcf7aa23005f22aa7daced15b5668e3a/libp2p/protocols/pubsub/pubsubpeer.nim#L207

**Comment by oskarth** [comment]
With lightpush protocol I believe we have a path towards this. Closing issue.
