### ISSUE TITLE
Waku store protocol identifier not aligned with spec

### ISSUE THREAD

**Issue by D4nte** [status-im/nim-waku#456]
The protocol identifier for waku store https://github.com/status-im/nim-waku/blob/a0dba2fea4d56a97612e0c49d1fc4d432d67892e/waku/v2/protocol/waku_store/waku_store.nim#L30 does not match the spec.

`"/vac/waku/store/2.0.0-beta1"` vs `/vac/waku/store/2.0.0-beta2`.

What is the difference between beta1 and beta2?

**Comment by jm-clius** [comment]
I think the codec was just not updated once the spec changes were implemented. Afaik `beta2` introduced pagination. Assigning to @staheri14 as editor of 13/WAKU2-STORE
