### ISSUE TITLE
No colours in Logs

### ISSUE THREAD

**Issue by D4nte** [status-im/nim-waku#472]
## Problem

Logs contains shell coloring characters which makes it difficult to read in an editor. e.g.:

```
[96mINF[0m 2021-04-09 10:36:14.511+10:00 [1mInitializing networking                   [0m topics="[93mwakunode[0m" [96mtid[0m=[94m925084[0m [96mfile[0m=[94mwakunode2.nim:127[0m [96mhostAddress[0m=[94m/ip4/127.0.0.1/tcp/61996[0m [96mannouncedAddresses[0m=[94m@[][0m
```
## Proposed solutions

Either an option to have non-colorized logs or wakunode2 looking at whether it is being executed in a pipe or terminal and not output colors when executed in a pipe (see https://stackoverflow.com/questions/911168/how-to-detect-if-my-shell-script-is-running-through-a-pipe#911213 )

**Comment by oskarth** [comment]
Does this help? https://nimbus.guide/log-rotate.html#build

**Comment by jm-clius** [comment]
Unassigning myself. Feel free to add to [Vac PM Board](https://github.com/orgs/vacp2p/projects/3) if @oskarth's solution does not work or is not comprehensive enough.

BTW I use [`lnav`](http://lnav.org/) for navigating log files and find it quite useful, also in dealing with colourisation.

**Comment by D4nte** [comment]
> Does this help?
> 
> ```
> make NIMFLAGS="-d:chronicles_colors=off -d:chronicles_sinks=textlines" 
> ```
> 
> From [nimbus.guide/log-rotate.html#build](https://nimbus.guide/log-rotate.html#build)

Yes, this solves all my problems including trace logs. Cheers!
