### ISSUE TITLE
Querying a `storenode` should not require keeping local history

### ISSUE THREAD

**Issue by jm-clius** [status-im/nim-waku#481]
Currently querying a `storenode` for history requires mounting `store` protocol. Currently this implies that every node querying history will itself act as a `storenode` and keep local history. The configuration for _keeping_ history and _querying_ for history needs to be separated.

Previously this separate configuration was allowed, but resulted in `nil` access errors (https://github.com/status-im/nim-waku/issues/439) prompting a [change in how/when protocols are mounted](https://github.com/status-im/nim-waku/pull/441). It should be possible, though, to have `store` protocol mounted and query for historical messages from `storenode` without having to keep local history.

### Acceptance criteria
- A `wakunode2` can be configured with a `storenode` and successfully query that `storenode` for historical messages without having to be a "full" `storenode` that keeps local history itself.

**Comment by oskarth** [comment]
Probably duplicate of above, closing
