### ISSUE TITLE
Simplifying the pagination logic

### ISSUE THREAD

**Issue by staheri14** [status-im/nim-waku#484]
## Problem
The current implementation of pagination as in https://github.com/status-im/nim-waku/blob/38b7a257c58063d7cc5746e93393711598355e68/waku/v2/protocol/waku_store/waku_store.nim#L222 can be more simplified for the sake of understandability and maintainability This issue is to simplify the logic and possibly break this proc into distinct blocks each taking care of one  special case e.g.,  initial paging queries, empty list of messages, etc. This would result in more code lines but would add clarity and allow better maintainability.

**Comment by oskarth** [comment]
@staheri14 are you actively working on this? If not maybe we should add it to icebox again

**Comment by staheri14** [comment]
Did not have a chance to work on it last week due to the RLN talk preparation.
Now it is addressed in this PR https://github.com/status-im/nim-waku/pull/689
