### ISSUE TITLE
Enhancing the types of query in the store protocol 

### ISSUE THREAD

**Issue by staheri14** [status-im/nim-waku#485]
As suggested by @oskarth in https://github.com/vacp2p/rfc/issues/327#issuecomment-815459362, the structure of store protocol can be enriched to support querying history based on the content topic of waku messages as well as pubsub topics. 
A more detailed problem definition is provided below which in most part is borrowed from https://github.com/vacp2p/rfc/issues/327#issuecomment-815459362
## Problem
1. The current topic/contentTopic mismatch in store is confusing
2. The current store protocol design insufficiently captures the types of queries we want to do
3. Filter protocol does capture this, and the only structural difference between Filter and Store is push (live messages) vs pull (historical messages)
4. We can and should enable similar semantics for store protocol as we do for filter protocol

Specifically, here's how filter protocol works:

FilterRPC can contain multiple FilterRequests, and a FilterRequest contains a topic (pubsub topic) and a content filter. A content filter can contain multiple contentTopics. This means, in a single FilterRPC call, you can have a query for multiple sets of PubSub topics AND contentTopics.

Similar to the filter protocol, we would like to allow to query of historical messages based on the combination of
1. Content Topic (this is already imeplemented)
2. PubSub topic 
3. All in one single network call.

This would also provide us consistency across specs

# Solution sketch
The following are the current structure of `HistoryQuery` and `FilterRequest`. 

``` protobuf
message HistoryQuery {
  repeated string topics = 2;
  optional PagingInfo pagingInfo = 3; // used for pagination
}
```

``` protobuf
message FilterRequest {
  bool subscribe = 1;
  string topic = 2;
  repeated ContentFilter contentFilters = 3;

  message ContentFilter {
    repeated  string contentTopics = 1;
  }
}
```
The following steps are envisioned to make the store protocol  query structure and its logic consistent with the filter protocol:
- [x] Replace the `topics` field in the `HistoryQuery` with `ContentFilter`. This also has to be reflected on the specs.
- [x] Update the find message proc in the store protocol to filter the history of messages based on the `ContentFilter`s.
- [x] Add the new field of `topic` to the `HistoryQuery` signifying the queried pubsub topic. Specs update shall follow.
- [x] Update the find message proc in the store protocol to filter the history of messages based on the pubsub topic `topic.

## How this change impacts the codebase
We should be careful about how this change can affect other parts of the codebase:
- This modification affects the list of retrieved historical messages. As this list is going to be the input to the pagination, the pagination logic is expected to work just fine with no updates required. 
Re the concern raised in https://github.com/vacp2p/rfc/issues/327#issuecomment-815459362:
>  What this means for PagingInfo I'm not 100% sure clear, but it might be doable to put that in ContentFilter.
- This change impacts the protobuf messages and the way that  nodes interact in the store protocol. As such, the jsonrpc side is also affected by this update. @jm-clius How feasible and easy do you think that such modification would be?

**Comment by D4nte** [comment]
LGTM 👍

**Comment by staheri14** [comment]
Closing this issue as all the subtasks are done.
