### ISSUE TITLE
Node / chat2 store flags unclear semantics

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#494]
# Problem

Currently:
1) For chat2 we use --store to indicate that we fetch history
2) When --store flag is set store protocol is mounted we have a handler for loading data, and we also persist messages

As a light node (client, basically), I'd want to default to only fetching history, not also saving it.

## Proposed solution

Maybe:
`--store` could indicate server mode, `storenode` indicates client node. (h/t Hanno)

## Future enhancements

One should be able to specify which pubsub topics are persisted,
as well as (more advanced) for how long (retention policy).

wdyt @staheri14 @jm-clius

**Comment by jm-clius** [comment]
I like the proposed solution. For `chat2` config we may have to clarify that `--storenode` does not necessarily require an explicit node allocation since one can be automatically selected by the app. This may extend to `wakunode2` config if we add some `storenode` discovery mechanism in future.

In other words,
``` 
./build/chat2 --storenode
```
and
```
./build/chat2 --storenode=/ip4/134.209.139.210/tcp/30303/p2p/16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ
```
should both be valid `chat2` config options.

**Comment by oskarth** [comment]
See https://github.com/status-im/nim-waku/issues/481 partial duplicate

**Comment by oskarth** [comment]
> Alternatively, we can mount the store protocol through --store flag and specify the mode using --mode = client / server.

A protocol can be in both client and server mode at the same time though, for example for syncing messages

**Comment by oskarth** [comment]
Also see https://github.com/vacp2p/rfc/issues/355 which is more about protocol side of things, not node flags.

**Comment by staheri14** [comment]
I think what you proposed makes sense! knowing that being server/client is not an xor choice.
Also, the ` --persist-messages` is quite self-descriptive!

**Comment by jm-clius** [comment]
Good idea. Assuming "persist" here indicate any server-like capabilities (i.e. storing messages in-mem or on disk or both)?

**Comment by staheri14** [comment]
Given that the `persist-messages` flag is enabled, are we going to keep issue open to handle the future enhancements? or should it be closed? @oskarth

**Comment by oskarth** [comment]
Seems like your PR closes the issue :)
