### ISSUE TITLE
Waku filter protocol: Redundant use of repeated ContentTopic inside ContentFilter 

### ISSUE THREAD

**Issue by staheri14** [status-im/nim-waku#496]
## Problem
In the filter protocol, the `FilterRequest ` message contains a sequence of `ContentFilter`s. This is while the `ContentFilter`  itself embodies a sequence of `ContentTopic`s. 
`FilterRequest`: https://github.com/status-im/nim-waku/blob/fb2ea06a4fdfaee91aa081be2592eb79349ed6c2/waku/v2/protocol/waku_filter/waku_filter_types.nim#L24
`ContentFilter`:
https://github.com/status-im/nim-waku/blob/fb2ea06a4fdfaee91aa081be2592eb79349ed6c2/waku/v2/protocol/waku_filter/waku_filter_types.nim#L12
This nested use of sequence is unnecessary and in fact the second use of sequence inside the `ContentTopic` must be omitted.

The rationale behind this change: Conceptually, a  `ContentFilter` encapsulates a single boolean query targeting AND of attributes of a waku message. Currently, it only targets the content topic field of waku message, but later can be extended to more fields. As such, each `ContentFilter` shall contain one single `ContentTopic`. This also complies with the waku message structure where each message is associated with one conte topic. 

## Acceptance Criteria
- [ ] Update  the  `ContentFilter`   structure by replacing sequence of  `ContentTopic`s  with a single `ContentTopic`
- [ ] Update the filter protocol specs as well (corresponding issue https://github.com/vacp2p/rfc/issues/348)

**Comment by oskarth** [comment]
fyi @jm-clius

**Comment by oskarth** [comment]
@EbubeUd in the future, please assign yourself and move the issue to "in progress" on the board

**Comment by EbubeUd** [comment]
> @EbubeUd in the future, please assign yourself and (move the issue to next/in progress on board)

Alright thanks I will.
