### ISSUE TITLE
Issue: `WakuFilter` requires `WakuRelay`

### ISSUE THREAD

**Issue by jm-clius** [status-im/nim-waku#498]
## Background
Currently the `WakuFilter` protocol requires `WakuRelay` to be mounted on a light node. This is because `WakuFilter` itself is not a PubSub protocol but in its current form requires PubSub functionality on at least three counts:
1. **In order to subscribe topic handlers:** this is necessary for `WakuFilter` to be notified of new messages. Currently topic handlers can only be registered via the `WakuRelay` protocol.
2. **In order to publish:** even if the above were not true, a node with only `WakuFilter` mounted would not be able to publish messages without having a PubSub-compatible protocol mounted. `WakuRelay` is currently the only such protocol implemented, though a [`LIGHTPUSH` protocol](https://github.com/vacp2p/rfc/issues/354) is under discussion.
3. **In order to dial the full node:** the full node, where `WakuRelay` is mounted by definition, will [attempt to subscribe](https://github.com/status-im/nim-libp2p/blob/master/libp2p/protocols/pubsub/pubsub.nim#L374-L379) the light node as a pubsub peer when dialed and negotiate a PubSub connection. However, if `WakuRelay` is not mounted on the light node the connection attempt will fail. This currently prohibits light nodes without `WakuRelay` mounted from dialing full nodes at all, including to subscribe to a content filter.

## Why do we not want to mount `WakuRelay` on a light node?
Once a light node with `WakuRelay` mounted has opened a connection to a full node (say, to subscribe a content filter), it will be considered a "normal" PubSub peer in the full node, undergo grafting and pruning and generally behave like a full node.

**Comment by oskarth** [comment]
Possibly candidate for release scope

**Comment by jm-clius** [comment]
The logs show the following is happening. Note that although `RELAY` and `FILTER` protocols are used as example, this seems to be true for any two nodes trying to open a stream for a non-`PubSub` protocol where `PubSub` is mounted on only one of the nodes.

@dryajov @sinkingsugar, it would be great to hear your thoughts! This may be expected behaviour, but that would mean that we're using the `switch` in a naïve way for our non-`PubSub` protocols.

Say we have two Waku nodes, **RF** and **F**. **RF** has both `RELAY` and `FILTER` protocols mounted (full node); **F** has only `FILTER` mounted (light node). `RELAY` closely mirrors `GossipSub 1.1`. `FILTER` is _not_ a `PubSub` protocol.
 
1. **F** dials **RF** on `FILTER` protocol, mounted on both.
2. **F** and **RF** negotiates streams and upgrade the connection as expected, until they have negotiated a stream multiplexer.
3. As soon as the connection is upgraded and [`muxer` is stored](https://github.com/status-im/nim-libp2p/blob/master/libp2p/connmanager.nim#L486), **RF** will [trigger a peer `Joined` event](https://github.com/status-im/nim-libp2p/blob/master/libp2p/connmanager.nim#L268) on `PubSub` that attempts to [subscribe **F** as a `PubSub` peer](https://github.com/status-im/nim-libp2p/blob/master/libp2p/protocols/pubsub/pubsub.nim#L563). This is because **RF** previously [registered a handler](https://github.com/status-im/nim-libp2p/blob/master/libp2p/protocols/pubsub/pubsub.nim#L567) for such events when the `RELAY` protocol was initialised.

```
TRC 2021-04-28 13:10:17.924+02:00 Stored muxer                               topics="libp2p connmanager" tid=1075 file=connmanager.nim:483 muxer=16U*GkREJu:6089429918e8406e32c643ca handle=false connections=1 
TRC 2021-04-28 13:10:17.924+02:00 Triggering connect events                  topics="libp2p connmanager" tid=1075 file=connmanager.nim:264 conn=16U*GkREJu:6089429918e8406e32c643ca
TRC 2021-04-28 13:10:17.924+02:00 About to trigger peer events               topics="libp2p connmanager" tid=1075 file=connmanager.nim:156 peer=16U*GkREJu
TRC 2021-04-28 13:10:17.924+02:00 triggering peer events                     topics="libp2p connmanager" tid=1075 file=connmanager.nim:169 peerId=16U*GkREJu event="(kind: Joined, initiator: false)"
DBG 2021-04-28 13:10:17.925+02:00 subscribePeer                              topics="libp2p pubsub" tid=1075 file=pubsub.nim:368 peer=16U*GkREJu                                                                
DBG 2021-04-28 13:10:17.925+02:00 created new pubsub peer                    topics="libp2p pubsub" tid=1075 file=pubsub.nim:291 peer=16U*GkREJu
DBG 2021-04-28 13:10:17.925+02:00 Calling connect on PubSubPeer              topics="libp2p pubsubpeer" tid=1075 file=pubsubpeer.nim:208 p=16U*GkREJu 
DBG 2021-04-28 13:10:17.925+02:00 connectOnce                                topics="libp2p pubsubpeer" tid=1075 file=pubsubpeer.nim:199 p=16U*GkREJu
TRC 2021-04-28 13:10:17.925+02:00 Dialing (existing)                         topics="libp2p switch" tid=1075 file=switch.nim:228 peerId=16U*GkREJu protos="@[\"/vac/waku/relay/2.0.0-beta2\", \"/vac/waku/relay/
```

4. This process fails, as expected, during stream negotiation as **F** does not support `RELAY`.
```
DBG 2021-04-28 13:10:18.199+02:00 Could not establish send connection        topics="libp2p pubsubpeer" tid=1075 file=pubsubpeer.nim:202 msg="Unable to select sub-protocol @[\"/vac/waku/relay/2.0.0-beta2\", \"/vac/waku/relay/2.0.0-beta2\"]"
```
5. However, on failure the `PubSubPeer` ["drops the connection"](https://github.com/status-im/nim-libp2p/blob/master/libp2p/protocols/pubsub/pubsubpeer.nim#L202) which in its current implementation will [disconnect the peer from the switch](https://github.com/status-im/nim-libp2p/blob/master/libp2p/protocols/pubsub/pubsub.nim#L293) and drop all its connections.
6. This disconnection includes the one established earlier (2) for **F**. It does so before a stream can be negotiated for `FILTER` protocol, which both nodes support. Protocol negotiation therefore fails.

**Comment by sinkingsugar** [comment]
> However, on failure the PubSubPeer "drops the connection" which in its current implementation will disconnect the peer from the switch and drop all its connections.

Ok this was a fix specifically for nimbus-eth2...
It's definitely not working in your case, where you have better peer management.
nimbus was leaking zombie peers so I had to do this. In your case I suggest doing manual management properly and fork libp2p for now. (or add a compile time flag in order not to break nimbus)

**Comment by jm-clius** [comment]
Thanks for clarifying, @sinkingsugar. Do you then foresee that this is going to change in `nim-libp2p`, especially when [peer management](https://github.com/status-im/nim-libp2p/issues/537) is introduced?

**Comment by sinkingsugar** [comment]
> Thanks for clarifying, @sinkingsugar. Do you then foresee that this is going to change in `nim-libp2p`, especially when [peer management](https://github.com/status-im/nim-libp2p/issues/537) is introduced?

Well, Ideally yes, for now nimbus was a priority so we patched it up. 
It would be in fact up to nimbus to use peer management somehow indeed.
