### ISSUE TITLE
Making contentFilters an optional argument for the store json rpc api

### ISSUE THREAD

**Issue by staheri14** [status-im/nim-waku#505]
## Problem
The  `contentFilters` argument of the store json rpc api is currently mandatory. This is to relax this requirement and make it optional.
The specs should also be updated accordingly.

**Comment by oskarth** [comment]
This might a good starter issue for Ebube

**Comment by staheri14** [comment]
> This might a good starter issue for Ebube

I think it is an easy fix. Today I was examining the json rpc api and I think I found the issue re the optional argument. 
While passing arguments using curl, the arguments that are defined using `Option` in the underlying proc  can be left out, however, while trying to develop a unit test in nim  for optional arguments, weird errors show up. Here is the detailed problem:
In the store json rpc API unit tests https://github.com/status-im/nim-waku/blob/f1a60271587072ca5db5b9aa6173ec56bbfc491d/tests/v2/test_jsonrpc_waku.nim#L209, there is no test for sending requests with empty `StorePagingOptions` i.e., `none(StorePagingOptions)`
I tried to do so by replacing this line
https://github.com/status-im/nim-waku/blob/f1a60271587072ca5db5b9aa6173ec56bbfc491d/tests/v2/test_jsonrpc_waku.nim#L262
with 
```nim
    let response = await client.get_waku_v2_store_v1_messages(@[defaultContentTopic], none(StorePagingOptions))

```
 but this error showed up:
```
Unhandled exception: {"code":-32000,"message":"get_waku_v2_store_v1_messages raised an exception","data":"Parameter [pagingOptions] expected JObject but got JNull"} [ValueError]
```
Here is the response from Hanno re this in Discord
> the problem here seems to be with how the Nim object is marshalled to JSON when you call that method on the  RpcHttpClient. In other words, using Option allows you to omit pagingOptions on an exposed JSON-RPC API (you can use curl or whichever tool to test this). The RpcHttpClient with Nim-ified callsigs does not allow this (could be a bug?). The easiest way I see around this is to execute a "curl" command locally as part of the test - i.e. you start up the RPC server and use execCmd() to perform the RPC request.

I can address this issue by wrapping arguments inside `Option` and I guess that would work just fine while interacting using `curl`, however the problem with   RpcHttpClient with Nim-ified callsigs will still remain.

@oskarth since you marked the issue as a starter task for Ebube, wanted to give you more details. Please let me know if you want to keep it as a starter task or shall I address it.

**Comment by oskarth** [comment]
@staheri14 if you've already started addressing it feel free to finish it up :)

**Comment by oskarth** [comment]
> RpcHttpClient with Nim-ified callsigs does not allow this (could be a bug?).

I'd probably report this upstream to JSON RPC library

Not sure if we need a dedicated tests for this case if it means shelling out with execCmd, if it works locally and we update code+specs that seems good enough to me.

**Comment by staheri14** [comment]
> @staheri14 if you've already started addressing it feel free to finish it up :)

@oskarth 
Sure! will do it.
