### ISSUE TITLE
SWAP - Accounting soft mode

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#524]
See https://github.com/vacp2p/research/discussions/61 for context.

# Problem

Keep track of accounting state for STORE protocol with SWAP. This is already partially done, but it isn't something that is visible for end users of e.g. chat2 chat and used by default in cluster. This makes it harder for other people to grasp and get an intuition for, and to build together on as a team.

This also allows us to see how general this design is, e.g. for using it in combination with other protocols.

# Acceptance criteria

- Show imbalance in accounting for swapStore
- Print logs when a peer is "out of bounds" in either direction
- Add a tagged metrics for Grafana dashboard
- Enable storeSwap by default so we can see this for cluster nodes

NOTE: This issue can probably be cut up into several issues

**Comment by oskarth** [comment]
For metrics, we can probably do something similar to what Nimbus is doing https://metrics.status.im/d/pgeNfj2Wz23/nimbus-fleet-testnets?orgId=1&var-instance=testing-small-02.aws-eu-central-1a.nimbus.pyrmont

I'm imagining some form of graph with with a number showing total imbalance, and then doing this per peer (stacked as columns, or lines) per peer. One issue with this would be if a store node has many peers it might be hard to visualize all of these accounting states, but there ought to be some Grafana view which can accommodate this.

**Comment by EbubeUd** [comment]
I guess we can close this  issue. The acceptance  criteria have been achieved with these PRs:

[Improve Waku Swap Logging and Enable by Default #549 ](https://github.com/status-im/nim-waku/pulls/549)
[Add Swap Account Metrics to Grafana Dashboard #585 ](https://github.com/status-im/nim-waku/pulls/585)

**Comment by oskarth** [comment]
Where can I see the Grafana in cluster? Would be good to add a link to this in docs folder.

**Comment by oskarth** [comment]
@EbubeUd is this done now?

**Comment by EbubeUd** [comment]
Yea it's been added to Grafana in [Cluster](https://grafana.infra.status.im/d/qrp_ZCTGz/nim-waku-v2?orgId=1&refresh=5m), but not yet updated in the docs folder yet. Currently working on that.
