### ISSUE TITLE
Implementing named arguments in the store json-rpc API

### ISSUE THREAD

**Issue by staheri14** [status-im/nim-waku#533]
# Problem
The parameters passed to the current store json-rpc api is position based. This means optional parameters has to be explicitly set to null while being send to the api. Only parameters towards the end of the arguments list can be left unspecified but not the middle ones. What we are looking for is to be able to use named-argument passing so that optional arguments can be entirely omitted. 
This feature must be normally supported by nim-json-rpc lib (As also indicated in the json-rpc specs https://www.jsonrpc.org/specification under sec 4.2), which is not the case yet. Here is the issue re this https://github.com/status-im/nim-json-rpc/issues/90.

Till this feature gets integrated in  nim-json-rpc, the workaround would be to define a Nim object data type wrapping all the arguments inside. The inputs to the rpc procs will be replaced by that Nim object. This means rpc call optional arguments which are now the data members of the Nim object can be omitted with no error.

**Comment by oskarth** [comment]
Duplicate, upstream
