### ISSUE TITLE
Mount `/ipfs/ping/1.0.0` protocol in wakunode2

### ISSUE THREAD

**Issue by D4nte** [status-im/nim-waku#534]
To avoid some errors over websocket connections (see #123), js-waku needs to implement a keep alive.
The most appropriate protocol for this would be the ping one.

Could you mount it by default? I understand it is not currently the case.

**Comment by jm-clius** [comment]
Note that ping protocol is not yet supported by libp2p - open issue [here](https://github.com/status-im/nim-libp2p/issues/567)

**Comment by jm-clius** [comment]
Ping protocol now supported in the `unstable` branch of libp2p (https://github.com/status-im/nim-libp2p/commit/55a3606ecbeff5079c58f196a26343c1dd8002e6). Waku support can go ahead.
