### ISSUE TITLE
Add basic example usage for Waku v1

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#54]
# Problem

As a consumer of this library it isn't clear how to use it.

## Solution

Add an example usage that shows how to use it.

**Comment by oskarth** [comment]
FYI @siphiuel @Samyoul @kdeme

**Comment by oskarth** [comment]
@kdeme would you be able to timebox say 30m before you go on vacation to write down some quick notes on how to use Waku v1? I think this would be useful for @iurimatias and Stimbus team once they start integrating nim-waku v1 (assuming this will start to happen before you get back).

**Comment by kdeme** [comment]
Sorry, I seem to have missed this comment. Anyhow, the waku_protocol.nim code has reasonable documentation on how to use. And the wakunode.nim can be used as an (more extensive) example. This was also explained to those looking into the code.
