### ISSUE TITLE
Display Swap Account Logs 

### ISSUE THREAD

**Issue by EbubeUd** [status-im/nim-waku#541]
**Sub task of the issue at #524** 

[Read more on this here](https://github.com/vacp2p/research/discussions/61)

**Issue:**
Currently, the account state is not visible for end users making it hard to keep proper track of accounting and indicate an imbalance where necessary. 

**Suggested Approach:**
- Enable Swap by default. This will be activated in the wakunode2 conf. 
- Create a Policy Method in the swap protocol to handle events that occur when a peer is out of bounds. 
- Log the Peer Id together with the accounting state when a credit / debit has been processed. 
- Change the log messages when the peer is out of bounds. It should be more of a warning than an action that has been executed.

**Comment by oskarth** [comment]
What is the status of this issue @EbubeUd? Any work in progress?
