### ISSUE TITLE
Macbook M1 issue with rln package

### ISSUE THREAD

**Issue by EbubeUd** [status-im/nim-waku#546]
Device:
Apple Macbook M1 Air

Architecture:
Arm64

Command:
`arch -x86_64 make test2`

Expected result:
run waku v2 tests successfully.

Actual result:
```
[NimScript] exec: build/all_tests_v2
dlopen(libpcre.3.dylib, 2): image not found
dlopen(vendor/rln/target/debug/librln.dylib, 2): no suitable image found.  Did find:
	vendor/rln/target/debug/librln.dylib: mach-o, but wrong architecture
	/Users/ebube/Documents/Web/Status/nim-waku/vendor/rln/target/debug/librln.dylib: mach-o, but wrong architecture
could not load: vendor/rln/target/debug/librln.dylib
stack trace: (most recent call last)
/Users/ebube/Documents/Web/Status/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/nimscript.nim(416, 18)
/Users/ebube/Documents/Web/Status/nim-waku/waku.nimble(72, 8) test2Task
/Users/ebube/Documents/Web/Status/nim-waku/waku.nimble(43, 8) test
/Users/ebube/Documents/Web/Status/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/nimscript.nim(260, 7) exec
```

**Comment by EbubeUd** [comment]
I used arch x86_64 because I learnt arm64 architecture is not fully supported by most of the libraries, including nim compiler

**Comment by EbubeUd** [comment]
So I am guessing some libraries where still built using x86_64 but some others where still built using the default arm64 architecture and hence causing incompatibility issues.

**Comment by oskarth** [comment]
This is one reason why it'd be good if we could isolate RLN as a dependency and optionally not include that (compiler flag, etc) when doing work unrelated to RLN. @staheri14

**Comment by staheri14** [comment]
> This is one reason why it'd be good if we could isolate RLN as a dependency and optionally not include that (compiler flag, etc) when doing work unrelated to RLN. @staheri14

Sue @oskarth, will be working on it.

**Comment by oskarth** [comment]
don't sue me pls

**Comment by staheri14** [comment]
A short-term fix for this issue is now available due to this PR https://github.com/status-im/nim-waku/pull/602
Moving to the icebox, for now. I Will get back to it with a long-term solution.

**Comment by EbubeUd** [comment]
Nice. Thanks

**Comment by oskarth** [comment]
Done
