### ISSUE TITLE
Add option to isolate rln dependency upon compilation

### ISSUE THREAD

**Issue by EbubeUd** [status-im/nim-waku#550]
There should be an option to ignore the rln dependency upon compilation. It currently has issues with the MacBook M1, but I think in general this is should be a good way to handle this.
This is a follow up issue to [#546.](https://github.com/status-im/nim-waku/issues/546)

**Comment by oskarth** [comment]
@EbubeUd please don't assign people unless it has been specifically discussed beforehand. Also having more than one person assigned to an issue, unless a specific good reason, is usually a bad idea

**Comment by EbubeUd** [comment]
> @EbubeUd please don't assign people unless it has been specifically discussed beforehand (in general, people should assign themselves to things they commit to working on). Also having more than one person assigned to an issue, unless a specific good reason, is usually a bad idea

Alright @oskarth Well noted
