### ISSUE TITLE
Reliable Store Protocol: Enforcing view consistency across store nodes

### ISSUE THREAD

**Issue by staheri14** [status-im/nim-waku#561]
Currently, store nodes work independently without synchronizing the state of their persisted messages. As such, there might be situations that they may have different views of the historical messages. This view inconsistency also means that light nodes cannot rely on the completeness of the history provided by a single store node.

This issue is to provide a mechanism to synchronize the state of store nodes and enable them to exchange their views and converge to a consistent and complete state. This will add reliability to the overall store protocol service. Moreover, any single full store node becomes a reliable source of message history.

**Comment by staheri14** [comment]
See this GH discussion for some initial solution ideas.
https://github.com/status-im/nim-waku/issues/561

**Comment by oskarth** [comment]
@staheri14 Can we link this to spec/research issue? Moving to icebox for now

**Comment by staheri14** [comment]
> @staheri14 Can we link this to spec/research issue? Moving to icebox for now
Indeed, that is a spec/research issue. Is there a way to link it to spec? 


> Also above issue is a loop :D
Oh, right! fixed it :p https://github.com/vacp2p/rfc/discussions/384

**Comment by oskarth** [comment]
Usually just pasting the issue link will link it. In this case it is a discussion and for some reason it isn't linked automatically. It could be its own issue in research repo instead of discussion I suppose, but let's leave it for now :)

**Comment by staheri14** [comment]
Created a new issue under research repo https://github.com/vacp2p/research/issues/74
