### ISSUE TITLE
Only bridge toy-chat content topic to Discord

### ISSUE THREAD

**Issue by D4nte** [status-im/nim-waku#589]
It seems that the Waku v2 <> Discord bridge does not filter by content topic. This makes noise in the Discord channel which makes it harder to see whether Discord and Waku v2 are sync'd (and hence, confirm things work).

I suggest to only publish messages on Discord that have the current toy-chat content topic.

**Comment by jm-clius** [comment]
Done in https://github.com/status-im/nim-waku/pull/591
