### ISSUE TITLE
Waku v2 Node API: Revise and improve Waku v2 API

### ISSUE THREAD

**Issue by kdeme** [status-im/nim-waku#61]
Waku v2 had a first go as to how to API could look like, see: https://github.com/status-im/nim-waku/blob/master/docs/api/v2/node.md

There are several TODO items to look at there + more API calls might be required.
This issue is there to handle the TODOs and revise the API once the Waku v2 protocol is better layed out.

**Comment by oskarth** [comment]
Here's my current thinking of what the API should roughly look like:

```
# 1. Init and start node
method init*(conf: WakuNodeConf): WakuNode
method start*(w: WakuNode)

# 2. PubSub Publish and subscribe - basically vanilla Flood/GossipSub here
# Here `topic` is a PubSub topic
method publish*(node: WakuNode, topic: string, data: seq[byte])
method subscribe*(node: WakuNode, topic: string, handler: TopicHandler)
method unsubscribe*(node: WakuNode, topics: seq[Topics])
# Here data is `Message` protobuf
method TopicHandler*(topic: string, message: seq[byte])

# 3. Waku topic content subscription
# (better name here?)
# (Replaces need for "light node", just do this and subscribe)
method subscribeWakuTopic*(node: WakuNode, wakuTopic: string, handler: WakuTopicHandler)
# Here data is `data` payload inside `Message`
method WakuTopicHandler*(wakuTopic: string, data: seq[byte])

# 4. Historical messages
# Query here includes things like waku topic, time range, request id
method getHistoricalMessages*(node: WakuNode, query: Query, handler: WakuHistoricalHandler)
# Response here is a protobuf including response, possibly query, cursor, etc
# This may recursively call e.g. getHistoricalMessages again
# Possibly replace wakuTopic with Query here
method WakuHistoricalHandler*(wakuTopic: string, resp: seq[byte])

# 5. Message construction
# (... is other things needed to create message)
method newWakuMessage*(wakuTopic: string, data: payload, ...): WakuMessage

# 6. Publish Waku messages
# (calls publish with a modified Message, etc)
method publishWaku*(node: WakuNode, wakuTopic: string, message: WakuMessage)
```

**Comment by kdeme** [comment]
I think I understand the confusion created here https://github.com/status-im/nim-waku/pull/63 better now.
I was thinking of the API in a slightly different way. In my proposal there would be no `subscribeWakuTopic` AND `subscribe`.
There would only be `subscribe`, which practically does what your `subscribeWakuTopic` does, in case of a light node. And in the other case, it would forward messages from the `TopicHandler` to the `WakuTopicHandler`, and filter them based on those Waku topics.

**Comment by oskarth** [comment]
How would that work for adaptive nodes? Hiding "full node functionality" like this sounds a bit off to me, like we are only designing for light nodes. It would make sense if it is just an implementation detail, but I am not sure it will be as we push the adaptive node concept and improve scaling etc.

I see the point regarding `subscribeWakuTopic` calling `subscribe`, so it'd be tiered anyway in that sense. It seems to me like they can still be part of the same API (init node, etc). Possibly different namespace?

**Comment by decanus** [comment]
```
# Here data is `Message` protobuf
method TopicHandler*(topic: string, message: seq[byte])
```

@oskarth I am not sure this is correct. If you are talking about libp2p-pubsub msg anyway. When talking to @dryajov I realized that the message receiving filters from nim-libp2p return the data field from the `Message`. So we need to determine what that `Message` is within the data field. Is it a status message? MVDS? something else? this also needs to be known so we can continue on the historic messages api imo.

**Comment by dryajov** [comment]
If you want access to the all the messages as they come in, you would need to extend `rpcHandler` method in `PubSub`, this is also done by both `FloodSub` and `GossipSub`. It gets an `RPCMsg` which contains all message types for pubsub, `Message`, `Subscriptions` and `Control`.

**Comment by oskarth** [comment]
Yeah, /s/is/should. When I looked at it before it seemed straightforward to extend to get Message payload. I can look at it it next week probably.

There are no blockers for historic message API basics, see other issues and PRs for comments there.

**Comment by oskarth** [comment]
Replaced by https://github.com/status-im/nim-waku/pull/77 and https://github.com/status-im/nim-waku/issues/78
