### ISSUE TITLE
Module for determining currency value of messages Received.

### ISSUE THREAD

**Issue by EbubeUd** [status-im/nim-waku#612]
Further break down of #604 

**Problem**
After a peer (`p1`) has received a couple of messages from a different peer (`p2`),  such that the messages have accumulated and the payment threshold is reached, there is currently no way of determining the total amount of an ERC20 token to be sent to `p2` since there is no record of what the currency value for each message should be. In essence, there is no exchange rate for the message and the erc20 token.

**Suggestion**
In a bid to abstract the future complexity of this module and keep it simple for now , we can have a module that provides a fixed conversion rate. eg: `1 msg` to `1 token` (ERC20). An improvement to this will be to estimate the value based on the `text size` of the messages or the average density of the `content-topic`. 

**Side Note**
As a follow up to this, we will only permit chequebooks to make use of one currency, by allowing them to input a particular ERC20 token [here](https://github.com/vacp2p/swap-contracts-module/blob/79c678da2e3894dac6d31347702de4bdace2f7d2/contracts/SimpleSwapFactory.sol#L30) or simply removing that param from the function and having a fixed address for the currency. This is to prevent us from running into problems of dealing with multiple exchange rates at an early stage.  This should probably be an issue Of its own, but it is worth noting here.

**Comment by oskarth** [comment]
Assuming that WakuMessages are of equal value seems good enough for now. Then have a constant for how much this is. This it'd be similar to gas price. That should basically be a few lines of code.

Later on we can extend this based on message size, but this can be done later.

**Comment by jm-clius** [comment]
@oskarth I believe we can close this issue? If something similar is required for planned incentivisation, I'm sure we can track it there.
