### ISSUE TITLE
DNS-based Discovery: DNS Resolver

### ISSUE THREAD

**Issue by jm-clius** [status-im/nim-waku#615]
Subtask of https://github.com/status-im/nim-waku/issues/452
Created as partial fulfilment of https://github.com/status-im/nim-waku/issues/552

### Problem

https://github.com/vacp2p/rfc/discussions/385 proposes a method to discover a bootstrap list of Waku v2 peers via DNS. This list is encoded in TXT records, stored in a domain. A `DNS Resolver` component must be created that can look up TXT records from a given subdomain.

**_NOTE:_** Since this component is easy to stub, it can be developed last.

**Comment by Menduist** [comment]
Hey, just stumbled into this issue.
FIY, we also have to resolve TXT dns as part of the `dnsaddr` resolving in libp2p, so for https://github.com/status-im/nim-libp2p/pull/580 we added the `dnsclient` library, and integrated it in chronos.

Once this is merged (currently finishing up), you will be able to just do:
`let record = await switch.nameResolver.resolveTxt("status.im")` (or something like that)

We also plan to integrate other resolvers in the future (eg, Dns-Over-Https), which you could also benefit from using our resolver :)

**Comment by jm-clius** [comment]
Oh, dope! Thanks a lot, @Menduist. This will make my task significantly easier :)
