### ISSUE TITLE
Metric Labels for Swap Account Balance are at high risks of being overpopulated

### ISSUE THREAD

**Issue by EbubeUd** [status-im/nim-waku#625]
Currently, the `peer` label in the swap account Metrics keeps track of each peer id with an account balance. 

**Problem**
The problem with this is that there is a very high chance of the peer ids being so numerous that they cause negative effects On the dashboard.

**Solution**
A possible solution to this to change the way the metrics are being accounted for. For now, we can have a counter indicating how many Peers have exceeded the thresholds. (Payment threshold and disconnect threshold).

**Comment by oskarth** [comment]
This will probably be a problem in the future indeed. For now unlikely to be a problem - I'd leave this alone and wait until we notice it is a problem, then figure it out :D (e.g. it can be a rolling buffer, different metric, etc)

**Comment by jakubgs** [comment]
Thanks. And correct, a label that has unbounded possible values is problematic for Prometheus and Cortrex:

![image](https://user-images.githubusercontent.com/2212681/122048091-252d6600-cde1-11eb-9896-424cc9a86f18.png)

https://prometheus.io/docs/practices/naming/#labels

**Comment by jakubgs** [comment]
>I'd leave this alone and wait until we notice it is a problem, then figure it out :D

@oskarth are we sure? It's currently not possible to clean up individual metrics from Cortex, so if it does explode it will affect querying performance for ALL metrics. Could we at last put in a limiter in the code that trims the list of peers we export in the metrics at 100 or something?

**Comment by arnetheduck** [comment]
it becomes a problem very quickly - libp2p already guards against these explosive metrics in the protocols it implements by grouping things.

this is also a security issue: it allows a remote to stuff the tables with ephemeral id:s

**Comment by oskarth** [comment]
Fair, good points.

> Could we at last put in a limiter in the code that trims the list of peers we export in the metrics at 100 or something?

Sure. How would this be enforced?

**Comment by jakubgs** [comment]
Truth be told a limiter like I proposed is something, but it's definitely not a perfect solution, since if someone just changes peer IDs over time they can still stuff the database with garbage, 100 unique peers ID's every 30 seconds, which can grow quite fast.

A proper solution involves re-designing the metric.

**Comment by oskarth** [comment]
To clarify - this is not something we'd use in production, it is to get SWAP working end to end quickly. It is indeed not the best way to capture that metric.

**Comment by jakubgs** [comment]
A proper solution would be making a metric that represents groups. Here's an example from Cortex metrics:
```
prometheus_tsdb_compaction_duration_seconds_bucket{le="1"} 0
prometheus_tsdb_compaction_duration_seconds_bucket{le="2"} 0
prometheus_tsdb_compaction_duration_seconds_bucket{le="4"} 0
prometheus_tsdb_compaction_duration_seconds_bucket{le="8"} 0
prometheus_tsdb_compaction_duration_seconds_bucket{le="16"} 49
prometheus_tsdb_compaction_duration_seconds_bucket{le="32"} 60
prometheus_tsdb_compaction_duration_seconds_bucket{le="64"} 61
prometheus_tsdb_compaction_duration_seconds_bucket{le="128"} 61
prometheus_tsdb_compaction_duration_seconds_bucket{le="256"} 61
prometheus_tsdb_compaction_duration_seconds_bucket{le="512"} 61
prometheus_tsdb_compaction_duration_seconds_bucket{le="1024"} 61
prometheus_tsdb_compaction_duration_seconds_bucket{le="2048"} 61
prometheus_tsdb_compaction_duration_seconds_bucket{le="4096"} 61
prometheus_tsdb_compaction_duration_seconds_bucket{le="8192"} 61
prometheus_tsdb_compaction_duration_seconds_bucket{le="+Inf"} 61
```
Which uses buckets that then can be graphed as a heatmap or something like that.

**Comment by jakubgs** [comment]
>this is not something we'd use in production

As long as the peer IDs can explode and the metrics end up in the same place as all other metrics this is a problem, prod or test.

**Comment by jakubgs** [comment]
https://prometheus.io/docs/concepts/metric_types/#histogram

**Comment by jakubgs** [comment]
Here are some exmaples of histograms with pre-defined buckets from `nimbus-eth2`:
```nim
const delayBuckets = [2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, Inf]

declareHistogram beacon_attestation_delay,
  "Time(s) between slot start and attestation reception", buckets = delayBuckets

declareHistogram beacon_aggregate_delay,
  "Time(s) between slot start and aggregate reception", buckets = delayBuckets

declareHistogram beacon_block_delay,
  "Time(s) between slot start and beacon block reception", buckets = delayBuckets
```
https://github.com/status-im/nimbus-eth2/blob/eb55fe241908b35db179aea04ae1db37a7d18b9e/beacon_chain/gossip_processing/eth2_processor.nim#L36-L45
