### ISSUE TITLE
Some nodes in prod fleet seem to not relay messages

### ISSUE THREAD

**Issue by michaelsbradleyjr** [status-im/nim-waku#637]
As mentioned in the Vac PM call earlier today, when I launch `chat2` and connect to a random node in the prod fleet, it sometimes happens that messages sent from that client don't get relayed, e.g. I don't receive them in `chat2` running in another terminal (also connected to a node in the prod fleet).

Since this behavior is only experienced sometimes, and since the prod fleet node is randomly selected, it seems like it's a problem affecting only some of the nodes.

**Comment by richard-ramos** [comment]
The same behavior can be observed in status-desktop. A desktop client will attempt to dial to any of these nodes:
- "/ip4/8.210.222.231/tcp/30303/p2p/16Uiu2HAm4v86W3bmT1BiH6oSPzcsSr24iDQpSN5Qa992BCjjwgrD"
- "/ip4/188.166.135.145/tcp/30303/p2p/16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e"
- "/ip4/34.121.100.108/tcp/30303/p2p/16Uiu2HAmVkKntsECaYfefR1V2yCR79CegLATuTPE6B9TxgxBiiiA"
and sometimes, when sending a message from one desktop client to another, the message is not received. 

However, if I manually set a the samen node in both desktop clients, the message will arrive with no issues.

**Comment by staheri14** [comment]
@jm-clius What are your thoughts?

**Comment by jm-clius** [comment]
This should now be fixed with the latest release being installed on both `prod` and `test` fleets. Closing issue, as local tests confirm that this has been fixed. Feel free to re-open if any issues still persist.
