### ISSUE TITLE
Disconnect Peer when Disconnect Threshold has been reached

### ISSUE THREAD

**Issue by EbubeUd** [status-im/nim-waku#640]
**Problem**
Currently, when the disconnect threshold has been reached, there is a warning log indicating that the disconnect threshold is reached, but the peer is not actually disconnected so messages will still be received. 
There should be a way of ensuring that messages are not received by the peer in debit after the disconnect threshold has been reached or exceeded.

**Suggested approach**
I feel it will be nice to leave the connection open, but perform a check [here](https://github.com/status-im/nim-waku/blob/82bad26e0287234fe55f6a5318209634d4350e12/waku/v2/protocol/waku_store/waku_store.nim#L345) before the messages are received. 
Essence of leaving the connection open is to allow the peer to still  send out a cheque to the store node, and also be able to perform a handshake successfully during payment.

**Comment by jm-clius** [comment]
Closing, as related PR (#643) has been closed without merging.
