### ISSUE TITLE
Prod Fleet doesn't match released version, `/vac/waku/relay/2.0.0` deployed

### ISSUE THREAD

**Issue by D4nte** [status-im/nim-waku#661]
Status waku v2 prod fleet is supposed to have latest wakunode2 release deployed, v0.4.

nim-waku [v0.4](https://github.com/status-im/nim-waku/releases/tag/v0.4) supports `/vac/waku/relay/2.0.0-beta2`.

However, when connecting to the prod fleet, `/vac/waku/relay/2.0.0` is returned during the identify protocol:

```
mss:handle read "/vac/waku/relay/2.0.0" +4ms common.js:111:9
mss:handle respond with "na" for "/vac/waku/relay/2.0.0" +0ms
```

You can just test with https://status-im.github.io/js-waku/ or https://status-im.github.io/js-waku/eth-dm by setting in the local storage: `DEBUG=libp2p*`

**Comment by jm-clius** [comment]
This has now been fixed with the new release (https://github.com/status-im/nim-waku/issues/672). Closing. Feel free to reopen if you notice any further issues.
