### ISSUE TITLE
Improvements to `store` memory and disk management

### ISSUE THREAD

**Issue by jm-clius** [status-im/nim-waku#702]
Relates to https://github.com/status-im/nim-waku/issues/695

## Background

The `store` protocol currently has no upper limit for the number of messages it will attempt to store (both in-memory and on-disk). This could lead to out-of-memory issues, long IO pauses and `HistoryResponse` messages that exceed the maximum length.

Furthermore, for each message received, the `store` will:
- write that message to persistent storage
- if it fails to do the above, log at `warn` level that it failed to do so.

Writing to persistent storage is relatively slow, so we may do better by inserting bundles (rather than individual messages) in the SQLite DB. This may, of course, lead to some in-memory message losses after a restart, but with a FT store protocol the risks are likely acceptable.

Moreover, it seems as if the `store` often gets into a state where it fails to store multiple messages (see #695). Logging each of these at `warn` level further exacerbates the problem at high message rates and clutters the logs. I'd suggest lowering the log level, or also only logging bundled write operations.

## Acceptance criteria

- [ ] A configurable maximum number of messages that can be stored, with the oldest elements removed first (e.g. a circular FIFO buffer).

## Further suggested improvements

- [ ] Bundled writes to persistent storage. I'd suggest writing bundled messages every, say, 10 seconds or so. That way we only have ~6 DB operations per minute.
- [ ] Per-message logs should preferably not exceed `trace` level (even if logging an error condition).

cc @staheri14 @oskarth

**Comment by oskarth** [comment]
Perhaps this is something Desktop/Stimbus team would like to look at? Could be a good task to become more familiar with code base etc and perf issues. Maybe something that could be paired on?

**Comment by jm-clius** [comment]
cc @michaelsbradleyjr @richard-ramos @siphiuel as discussed in PM call

**Comment by jm-clius** [comment]
> From my experience, store queries can be quite slow. Is it realistic to expect that a smaller page size can lead to faster result?

Well, I believe a smaller `store` size (and some other suggested improvements above) will lead to faster results. Not sure how large a role page size will play, but it could definitely be a factor. Would have to examine this a bit closer though, as smaller pages won't necessarily be faster if they imply _more_ pages (there's a non-negligible computation for each page).

**Comment by staheri14** [comment]
One major running time improvement is to avoid sorting messages per history query (and per page) and instead keep the messages sorted by default.
