### ISSUE TITLE
Waku 2: Topic Handlers in Waku RPC

### ISSUE THREAD

**Issue by decanus** [status-im/nim-waku#72]
# Problem

Currently there is no way for me to listen to a message topic with a callback.

# Possible Solution

As discussed with @kdeme, the way this could work is quite simple. Making this work in the `json-rpc` manner is probably a lot of engineering work. There is another option however, we add middleware. What does this mean?

There is a native wrapper around waku nodes, that clients can use to interact with node in `nim`, this wrapper is then also used to build the json-rpc api.

It would look like this roughly: `rpc -> node api -> node`

RPC does almost nothing other than call this. It would expose functions like subscribing with a specific topic handler.

**Comment by kdeme** [comment]
Just to be clear, this is not optional middleware, this would be the Waku API proposal that was started here: https://github.com/status-im/nim-waku/blob/master/docs/api/v2/node.md#waku-api . It would make use of `WakuSub` (which is really doing not much more than just being a wrapper around the selection of `FloodSub`, `GossipSub`, or any future sub). 

I've explained how it could work here: https://github.com/status-im/nim-waku/pull/63#discussion_r458718034

If we would end up using the topics libp2p pubsub however (for full nodes, light nodes, everything), then that layer would currently not do anything more than remapping handlers for the same topics, so then the `WakuSub` API could be used directly.

The Json RPC would only be a small layer on top of this as you mention.

RPC -> Waku API -> WakuSub API (aka GossibSup or FloodSub)

**Comment by oskarth** [comment]
What is the advantage of having another layer of API, as opposed to compacting Waku and WakuSub API? It isn't obvious to me that this is actually needed.

**Comment by oskarth** [comment]
https://github.com/status-im/nim-waku/issues/53#issuecomment-662797790

**Comment by oskarth** [comment]
With https://github.com/status-im/nim-waku/pull/89 can you solve the problem for now?

Once we have it based on Message instead of data we can address that. Seems like a slightly different issue though.

**Comment by oskarth** [comment]
Is this addressed with the current Node API? @decanus @kdeme

**Comment by kdeme** [comment]
I believe so yes.
