### ISSUE TITLE
CI failures on `nim-waku`

### ISSUE THREAD

**Issue by jm-clius** [status-im/nim-waku#738]
## Problem

Currently CI on `nim-waku` `master` (or any PRs based on the latest `master`, e.g. [this one](https://github.com/status-im/nim-waku/pull/731)) fails in two places:

1. [`Test / windows` fails](https://github.com/status-im/nim-waku/pull/731/checks?check_run_id=3837227777) with `mingw32-make: *** [vendor/nimbus-build-system/makefiles/targets.mk:116: libminiupnpc.a] Error 2`. Perhaps an issue related to the state of `mingw32-make` on the `windows-latest` platform?
2. `jenkins/prs/linux` fails with:
```
12:02:25  + make V=0 update
 > git submodule update --init --recursive vendor/dnsclient.nim # timeout=10
12:02:27  make: *** [vendor/nimbus-build-system/makefiles/targets.mk:95: update-common] Error 1
```
This is likely because the `vendor/dnsclient.nim` submodule's URL changed in https://github.com/status-im/nim-waku/commit/50189a21a95760ae389c313b516fff6960c0384b.

@jakubgs, since we want to deprecate GH workflow CI I'm not too worried about `Test / windows` CI failure (as windows CI passes on jenkins), but I'm a bit at a loss why the submodule update for `vendor/dnsclient.nim` would fail on `jenkins/prs/linux`, and only there. Perhaps you have an intuition?

**Comment by jakubgs** [comment]
I think this issue is related to Jenkins Git cache:
```
admin@master-01.do-ams3.jenkins.ci:/data/jenkins/data/caches % grep url ./git-*/.git/config | grep -C2 nim-waku
./git-97d59124b97de0e6118436d9a0ca4d38/.git/config:	url = https://github.com/status-im/status-tutorials/
./git-9b8f97482f6bb00e90af5e0c2f88ce25/.git/config:	url = https://github.com/status-im/cn.status.im.git
./git-9e49b492a9961cbc97beb5fa52b5e25e/.git/config:	url = https://github.com/status-im/nim-waku
./git-a08f1c03ddfe3710a7af478b9e3df0f7/.git/config:	url = git@github.com:status-im/handbook.status.im.git
./git-a56b29c6465e3dbb8f358967b81a072c/.git/config:	url = https://github.com/status-im/referral-service.git
```
So I've removed the `git-9e49b492a9961cbc97beb5fa52b5e25e` folder and re-ran the job but that didn't do it.

**Comment by jm-clius** [comment]
This issue still occurs, e.g. https://github.com/status-im/nim-waku/pull/777. Since we foresee that Github CI, and therefore the failing `Test / windows`, will be shut down in future that is less urgent, but the Jenkins-based Linux CI still fails frequently in the `deps` phase.
 This seems to happen inconsistently, with no clear observable pattern.

**Comment by jakubgs** [comment]
```
[2021-11-22T11:49:21.252Z] + make V=0 update
[2021-11-22T11:49:23.809Z] make: *** [vendor/nimbus-build-system/makefiles/targets.mk:95: update-common] Error 1
```
That's not very useful... we need a higher `V` to get anything that makes sense.

**Comment by jm-clius** [comment]
> That's not very useful... we need a higher `V` to get anything that makes sense.

Right - upped to 1 in https://github.com/status-im/nim-waku/pull/785

**Comment by jakubgs** [comment]
If we want to change that for all builds that's fine, but you can do that manually for a specific build too:

![image](https://user-images.githubusercontent.com/2212681/143295261-09f4e519-f62a-4a89-ac9b-f6f4dc485dce.png)

![image](https://user-images.githubusercontent.com/2212681/143295304-56d2a56b-143d-427a-9717-f0135ce07900.png)

Not sure if we want to flood build logs for ALL builds. But up to you guys.

**Comment by jm-clius** [comment]
I have no strong feelings about this, but imagined it better to have all CI builds be verbose for now, since we're having trouble predicting when/where the CI is going to fail.
The GH CI [seems to always run `make update` with `V=1`](https://github.com/status-im/nim-waku/blob/master/.github/workflows/test.yml#L42), although that won't affect the other make tasks.

@oskarth, any clear reasons from your side not to up Jenkins CI logs to higher verbosity? If it becomes difficult to debug later, we can always lower verbosity again.

**Comment by jakubgs** [comment]
I guess `1` isn't as bad as `2`, and that's still available via the parameter.

**Comment by oskarth** [comment]
Seems fine for me. The only historical reason I can think of is that Jenkins PR log output was public in the past, and increasing verbosity might reveal some secrets (not saying it would, but at some point in time this was a concern for e.g. status-react app).

**Comment by jm-clius** [comment]
Interestingly `jenkins/macos` has also started failing with:
```

[2021-12-02T14:40:23.058Z] clang: error: the clang compiler does not support '-march=native'

[2021-12-02T14:40:23.058Z] clang: error: the clang compiler does not support '-march=native'

[2021-12-02T14:40:23.059Z] Error: execution of an external compiler program 'clang -c  -w -pthread -I/Users/jenkins/workspace/nim-waku_prs_macos_PR-790/vendor/nim-dnsdisc/vendor/nim-bearssl/bearssl/csources/src -I/Users/jenkins/workspace/nim-waku_prs_macos_PR-790/vendor/nim-dnsdisc/vendor/nim-bearssl/bearssl/csources/inc -I/Users/jenkins/workspace/nim-waku_prs_macos_PR-790/vendor/nim-dnsdisc/vendor/nim-bearssl/bearssl/csources/tools -DBR_USE_UNIX_TIME=1 -DBR_USE_URANDOM=1 -DBR_LE_UNALIGNED=1 -DBR_64=1 -DBR_INT128=1 -I/Users/jenkins/workspace/nim-waku_prs_macos_PR-790/vendor/nim-dnsdisc/vendor/nim-bearssl/bearssl/certs -I/Users/jenkins/workspace/nim-waku_prs_macos_PR-790/vendor/nim-zlib/zlib/csources -I/Users/jenkins/workspace/nim-waku_prs_macos_PR-790/vendor/nim-secp256k1/secp256k1_wrapper -I/Users/jenkins/workspace/nim-waku_prs_macos_PR-790/vendor/nim-secp256k1/secp256k1_wrapper/secp256k1 -I/Users/jenkins/workspace/nim-waku_prs_macos_PR-790/vendor/nim-secp256k1/secp256k1_wrapper/secp256k1/src -DHAVE_CONFIG_H -DHAVE_BUILTIN_EXPECT -I/Users/jenkins/workspace/nim-waku_prs_macos_PR-790/vendor/nim-nat-traversal/vendor/miniupnp/miniupnpc -I/Users/jenkins/workspace/nim-waku_prs_macos_PR-790/vendor/nim-nat-traversal/vendor/libnatpmp-upstream -DENABLE_STRNATPMPERR -march=native -O3  -I/Users/jenkins/workspace/nim-waku_prs_macos_PR-790/vendor/nimbus-build-system/vendor/Nim/lib -I/Users/jenkins/workspace/nim-waku_prs_macos_PR-790/examples/v2/matterbridge -o nimcache/release/chat2bridge/ccopy.c.o /Users/jenkins/workspace/nim-waku_prs_macos_PR-790/vendor/nim-dnsdisc/vendor/nim-bearssl/bearssl/csources/src/codec/ccopy.c' failed with exit code: 1
```

With verbosity now higher it's also possible to get a better read on the `jenkins/linux` issue, though I'm not sure it's of much help:
```
15:39:27  + make V=1 update
15:39:27  which gcc &>/dev/null || { echo "C compiler (gcc) not installed. Aborting."; exit 1; }
15:39:27  git submodule foreach --quiet 'git ls-files --exclude-standard --recurse-submodules -z -- ":!:.*" | xargs -0 rm -rf'
15:39:34  git submodule update --init --recursive || true
15:39:49  # changing URLs in a submodule's submodule means we have to sync and update twice
15:39:49  make: *** [vendor/nimbus-build-system/makefiles/targets.mk:95: update-common] Error 1
[Pipeline] }
```

Links to full logs:
https://ci.status.im/job/nim-waku/job/prs/job/linux/job/PR-790/2/console
https://ci.status.im/job/nim-waku/job/prs/job/macos/job/PR-790/2/console

**Comment by jakubgs** [comment]
Hmmm, this time it worked fine:
https://ci.status.im/job/nim-waku/job/prs/job/linux/job/PR-790/3/

**Comment by jm-clius** [comment]
> Hmmm, this time it worked fine: https://ci.status.im/job/nim-waku/job/prs/job/linux/job/PR-790/3/

Urgh, yeah, it's very inconsistent - sometimes it just starts working. On the other PR a rerun didn't work: https://ci.status.im/job/nim-waku/job/prs/job/linux/job/PR-789/3/

The macos job seems to be failing pretty consistently now across all PRs, e.g. https://ci.status.im/job/nim-waku/job/prs/job/macos/job/PR-789/3/. It works fine in GH actions.

**Comment by oskarth** [comment]
What's different between our setup and Nimbus?

**Comment by jakubgs** [comment]
This might just be corrupted jenkins cache. I'll try clearing that.

**Comment by jakubgs** [comment]
Eeeeeee, `V=2` doesn't say much more...
```
16:50:12  + make V=2 update
16:50:12  which gcc &>/dev/null || { echo "C compiler (gcc) not installed. Aborting."; exit 1; }
16:50:12  git submodule foreach --quiet 'git ls-files --exclude-standard --recurse-submodules -z -- ":!:.*" | xargs -0 rm -rf'
16:50:13  git submodule update --init --recursive || true
16:50:14  # changing URLs in a submodule's submodule means we have to sync and update twice
16:50:14  make: *** [vendor/nimbus-build-system/makefiles/targets.mk:95: update-common] Error 
```
https://ci.status.im/job/nim-waku/job/prs/job/linux/view/change-requests/job/PR-789/4/console

**Comment by jm-clius** [comment]
Hi @jakubgs, the nim-waku CI failures seem to have deteriorated more. I've extracted the below examples from https://github.com/status-im/nim-waku/pull/815, but most CI runs will exhibit one or all of these:
1. `jenkins/prs/linux` fails as before in the `deps` phase (from time to time it mysteriously passes): https://ci.status.im/blue/organizations/jenkins/nim-waku%2Fprs%2Flinux/detail/PR-815/1/pipeline
2. `jenkins/prs/macos` also now fail, inconsistently, in the V2 phase, with clang error `clang: error: the clang compiler does not support '-march=native': https://ci.status.im/blue/organizations/jenkins/nim-waku%2Fprs%2Fmacos/detail/PR-815/1/pipeline
3. `jenkins/prs/windows` also fail from time to time in `deps` phase with several CMAKE errors: https://ci.status.im/blue/organizations/jenkins/nim-waku%2Fprs%2Fwindows/detail/PR-815/1/pipeline

In the old GH CI tests, the Windows-based tests fail: https://github.com/status-im/nim-waku/runs/4817793967?check_suite_focus=true
The GH workflow CI tests for `ubuntu-lates`t and `macos-latest` seem, by far, to be the most stable. Perhaps we should try to get the GH `Test / Windows` action working again if the Jenkins CI is too unstable in the long run? I've spend some time looking into the Windows error before, but didn't make much headway:
```
mingw32-make: *** [vendor/nimbus-build-system/makefiles/targets.mk:126: libminiupnpc.a] Error 2
```
WDYT?

**Comment by jakubgs** [comment]
The `macos` failures are obviously because we have an M1 machine and the `Jenkinsfile.macos` does not specify labels for architecture like other projects do, which is easy to fix: https://github.com/status-im/nim-waku/pull/817

**Comment by jakubgs** [comment]
All failures on Linux hosts appear to be happening on `linux-02`:

* https://ci.status.im/job/nim-waku/job/prs/job/linux/job/PR-815/1/console
* https://ci.status.im/job/nim-waku/job/prs/job/linux/job/PR-815/2/console
* https://ci.status.im/job/nim-waku/job/prs/job/linux/job/PR-815/3/console

Maybe you can find an outlier from this, but it seems to be host specific.

**Comment by jakubgs** [comment]
My best guess for Windows is that something went wrong when I replaced the GC hosts with Hetzner ones. Either some versions changed in Scoop, so what I installed on the new host was different in some way, or I'm missing some part of the setup in Ansible.

Anyway, simplest thing would be to set the `CMAKE_MAKE_PROGRAM` env var, but I'm going to try some other things first.

**Comment by jm-clius** [comment]
Thanks

**Comment by jakubgs** [comment]
Looks like just installing the [`mingw`](https://github.com/ScoopInstaller/Main/blob/master/bucket/mingw.json) package explicitly has fixed the issue with the `Deps` stage on Windows.
Other possibilities include [`mingw-nuwen`](https://github.com/ScoopInstaller/Main/blob/master/bucket/mingw-nuwen.json) and [`mingw-winlibs`](https://github.com/ScoopInstaller/Main/blob/master/bucket/mingw-winlibs.json), but I opted to use the most standard - if outdated - option.

Fix: https://github.com/status-im/infra-ci/commit/21f94970

**Comment by jakubgs** [comment]
That solves the MacOS and Windows issues, I need to investigate `linux-02` to see what's its problem.

**Comment by jakubgs** [comment]
I don't get it, if I run the Git commands separately without all the `make` garbage it works fine:
```
21:24:36  + git status
 > git submodule update --init --recursive vendor/dnsclient.nim # timeout=10
21:24:36  HEAD detached at 951b87c
21:24:36  nothing to commit, working tree clean
[Pipeline] sh
21:24:37  + git submodule foreach --quiet git ls-files --exclude-standard --recurse-submodules -z -- ':!:.*' | xargs -0 rm -rf
[Pipeline] sh
21:24:38  + git submodule update --init --recursive
```
https://ci.status.im/job/nim-waku/job/prs/job/linux/job/PR-816/11/console

So it's something else that's failing in `make update`.

**Comment by jakubgs** [comment]
What I don't get is why `make` appears to fail on a comment line:
```
12:34:43  git submodule foreach --quiet 'git ls-files --exclude-standard --recurse-submodules -z -- ":!:.*" | xargs -0 rm -rf'
12:34:45  git submodule update --init --recursive || true
12:34:46  # changing URLs in a submodule's submodule means we have to sync and update twice
12:34:46  make: *** [vendor/nimbus-build-system/makefiles/targets.mk:105: update-common] Error 1
```
The line numbre `105` is this comment:
```Makefile
	git submodule update --init --recursive || true
	# changing URLs in a submodule's submodule means we have to sync and update twice
	git submodule sync --quiet --recursive
```
https://github.com/status-im/nimbus-build-system/blob/25a4c270/makefiles/targets.mk#L104-L106
How does it fail? And why only on `linux-02`? Makes no sense to me.

**Comment by jakubgs** [comment]
If I just test this with a simple `Makefile` it correctly reports the failure on the command line and not the comment:
```Makefile
test:
	ls nothing
	# test comment
	ls
```
```sh
admin@linux-02.do-ams3.ci.misc:~ % make test
ls nothing
ls: cannot access 'nothing': No such file or directory
make: *** [Makefile:2: test] Error 2
```
What the hell...

**Comment by jakubgs** [comment]
Also, I'm fascinated by the ability of `nim-waku` builds to consistently hit `linux-02` while all the other ones are available...

**Comment by jakubgs** [comment]
I used [`debsums`](https://manpages.ubuntu.com/manpages/trusty/man1/debsums.1.html) to check binaries on `linux-02` but found no issues:
```
admin@linux-02.do-ams3.ci.misc:/ % sudo debsums -s     
debsums: missing file /usr/bin/pip (from python3-pip package)
debsums: missing file /usr/bin/pip3 (from python3-pip package)
debsums: missing file /usr/lib/android-sdk/build-tools/debian/split-select (from split-select package)
debsums: missing file /usr/lib/android-sdk/build-tools/debian/zipalign (from zipalign package)
```

**Comment by jakubgs** [comment]
I think I might as well just connect this with something else I wanted to do, which is to replace our Digital Ocean hosts with Hetzner AX41-NVMe machines, which should be much more powerful.

**Comment by jakubgs** [comment]
Looks like the installation of `mingw` on Windows hosts has broken Status Desktop builds:
https://github.com/status-im/status-desktop/issues/4492#issuecomment-1016828849

Which is just lovely. I tried installing `mingw-winlibs` instead as its newer, but we get back the same failure as before:
```
CMake Error: CMake was unable to find a build program corresponding to "MinGW Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
```
https://ci.status.im/job/nim-waku/job/prs/job/windows/view/change-requests/job/PR-821/3/

One step forward, two steps back...

**Comment by jakubgs** [comment]
Actually, after restarting the host this build didn't fail with the `CMake Error`:
https://ci.status.im/job/nim-waku/job/prs/job/windows/view/change-requests/job/PR-821/5/console

So possibly the previous failure was just a red herring due to change in `PATH` not taking effect.

I will test with the second host.

**Comment by jakubgs** [comment]
I had to switch to use `mingw-nuwen` instead of `mingw-winlibs` because it was causing issues with `status-go` builds for Desktop due to how `make` handles paths: https://github.com/status-im/status-desktop/issues/4492#issuecomment-1017490963

- [78859767](https://github.com/status-im/infra-ci/commit/78859767) - ci-slave-windows: use mingw-nuwen instead of mingw

**Comment by jakubgs** [comment]
I think this is solved. Feel free to reopen if you see the same issue. Or make a new issue if something new comes up.

Which it inevitably will...
