### ISSUE TITLE
Waku v2: History implement basic Query and Response

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#74]
Implement https://github.com/status-im/nim-waku/issues/38

This can be a sketch and explicitly doesn't:

1) Need the whole query/response interace figured out (cursor specifics, etc)
2) Persist guarantees

E.g. a simple test (e.g. like quicksim) would be:

1. Publish `foo` on `bartopic`
2. Query(`bartopic`)
3. Response(`bartopic`) with `foo` in it (all in memory)

This can then easily be enhanced with logic and persistence, and it would shape up the code in a basic way.

cc @decanus 

---

Part of https://github.com/status-im/nim-waku/issues/78

Acceptance criteria: according to docs https://github.com/status-im/nim-waku/blob/master/docs/api/v2/node.md

**Comment by oskarth** [comment]
@decanus can you take a look at this one?

**Comment by decanus** [comment]
Yup @oskarth

**Comment by oskarth** [comment]
I'm not sure this was done.
