### ISSUE TITLE
Json rpc api tests fail when `WakuMessage`'s `proof` is a custom object type

### ISSUE THREAD

**Issue by staheri14** [status-im/nim-waku#750]
# Problem
When we change the type of `proof` field of `WakuMessage` from `seq[byte]` to  the object type`RateLimitProof`, the json rpc tests begin to fail on `Jenkins/windows/prs`.  Link to the [error log](https://github.com/status-im/nim-waku/files/7377290/log.2.txt).
As a workaround, the type of `proof` is defaulted to `seq[byte]`  unless the rln flag is passed in which case the proof would be of type `RateLimitProof`. 

This is a blocker for https://github.com/status-im/nim-waku/issues/714

**Comment by jm-clius** [comment]
Mmm, so it's not easy to see why this may be happening. My guess is that [this function](https://github.com/status-im/nim-json-rpc/blob/2307dbec579ceaf60aa3afd5f338ecfba127f104/json_rpc/clients/httpclient.nim#L80-L157) in `httpclient.nim` returns the empty string `""` for some reason. But afaics that should be visible in the logs, and it's not.
The store node logs that it returns a response with 8 messages:

> INF 2021-10-19 00:49:02.910+00:00 sending response                           topics="wakustore" tid=3040 messages=8

the client API interfaces logs that it has received that response:

> DBG 2021-10-19 00:49:02.910+00:00 get_waku_v2_store_v1_messages response     topics="store api" tid=3040

but then the client still fails to read a response from the server [here](https://github.com/status-im/nim-json-rpc/blob/2307dbec579ceaf60aa3afd5f338ecfba127f104/json_rpc/clients/httpclient.nim#L195)

🤷‍♂️ Perhaps a good strategy would be to add more debug logging.

**Comment by staheri14** [comment]
The problem is resolved.
