### ISSUE TITLE
Store node: limit size of `HistoryResponse` messages

### ISSUE THREAD

**Issue by jm-clius** [status-im/nim-waku#787]
Many `store` clients assumes a hard limit of 64kb when reading a `HistoryResponse` from the wire, including `go-waku` and `nim-waku` (for example, [here](https://github.com/status-im/nim-waku/blob/master/waku/v2/protocol/waku_store/waku_store.nim#L526) and [here](https://github.com/status-im/nim-waku/blob/master/waku/v2/protocol/waku_store/waku_store.nim#L551)).

However, a store node does not similarly limit the size of `HistoryResponse` messages and, particularly for open history requests with no pagination, this results in various RPC/buffer errors if the response message size exceeds this maximum.

One solution may be to keep track of history size and to "auto-paginate" once a history response nears 64kb.

cc @staheri14 @richard-ramos

**Comment by staheri14** [comment]
Thanks @jm-clius for opening the issue!

I also agree with the auto pagination idea, I think default pagination should be always enforced for all the queries regardless. 

In addition,  I suggest adding an additional field to the page request indicating the max page size in bytes, then the returned response should meet both limits (message number and the overall size). This way, the querying node can also control the amount of fetched data and is also aware of such limits.

**Comment by D4nte** [comment]
I assume that the auto pagination would override the page size in the history request?

**Comment by jm-clius** [comment]
> I assume that the auto pagination would override the page size in the history request?

I think so (we still have to design this feature, if this is the way we go), but we'll have to very explicitly specify so it's clear to the client what's happening. I.e. it should be clear in the spec that if a client specifies a paging size (or open query), it should know to expect a smaller page than requested under some conditions, either because:
a) stored history is so small that the `store` node can't fill a page in its response
b) stored messages are so large that the `store` node can't fill a page due to response size limit

In (b) the client would also receive the PagingInfo to request the next page.
