### ISSUE TITLE
Store implementation improvements

### ISSUE THREAD

**Issue by jm-clius** [status-im/nim-waku#805]
### Background

A couple of changes in the `store` implementation could improve query performance and lower `store` resource usage.

This is important, as there are currently [some unexplained CPU spikes on the `prod` fleet](https://grafana.infra.status.im/d/qrp_ZCTGz/nim-waku-v2?orgId=1&from=1640217600000&to=1640303999000) that results in high relay latency (tracked in https://github.com/status-im/nim-waku/issues/736).

### Suggested improvements

- [ ] Change underlying `messages` cache implementation to an [`OrderedSet`](https://nim-lang.org/docs/sets.html#OrderedSet). This removes the need for deduplication, which was also raised in https://github.com/status-im/nim-waku/issues/729.
- [ ] Rather than using procs that copies the `messages` cache multiple times (e.g. [here](https://github.com/status-im/nim-waku/blob/b2273fff9a98a8918e0e8b5012aee1754ba3e943/waku/v2/protocol/waku_store/waku_store.nim#L389), [here](https://github.com/status-im/nim-waku/blob/b2273fff9a98a8918e0e8b5012aee1754ba3e943/waku/v2/protocol/waku_store/waku_store.nim#L394) and [here](https://github.com/status-im/nim-waku/blob/b2273fff9a98a8918e0e8b5012aee1754ba3e943/waku/v2/protocol/waku_store/waku_store.nim#L400)) when filtering for queried messages, filter on a single, mutable copy (by using `keepItIf` or similar procs)#800 

cc @staheri14

**Comment by D4nte** [comment]
We are noticing slow store queries time to time as discussed on Discord.
Do you need more information or do you prefer to tackle this issue first and see the impact?

**Comment by jm-clius** [comment]
> We are noticing slow store queries time to time as discussed on Discord. Do you need more information or do you prefer to tackle this issue first and see the impact?

I think it's worth starting to implement some of these fixes. Did my own tests yesterday and confirmed that at least some of the performance issues are caused by buggy store queries.
