### ISSUE TITLE
Result aggregation in resume API

### ISSUE THREAD

**Issue by staheri14** [status-im/nim-waku#809]
# Problem
The current implementation of [resume](https://github.com/status-im/nim-waku/blob/b2273fff9a98a8918e0e8b5012aee1754ba3e943/waku/v2/protocol/waku_store/waku_store.nim#L623) stops fetching messages when one of the peers returns a result. This issue is to enhance the logic i.e., to query all the peers return the aggregate of their results with no duplicates. 

This update is also inline with the Waku v2 MVP  solution for community history.

# Acceptance criteria
- [ ] The logic is fully implemented.
- [ ] The implementation has proper tests.
- [ ] The [changelog](https://github.com/status-im/nim-waku/blob/master/CHANGELOG.md) reflects the updated logic of resume API.
- [ ] The waku v2 API [description](https://github.com/status-im/nim-waku/blob/master/docs/api/v2/node.md) is updated.

**Comment by staheri14** [comment]
@kaiserd it seems all the items in this issue are addressed, right? then you can close the issue

**Comment by kaiserd** [comment]
@staheri14 Yes :). Closing it now.
