### ISSUE TITLE
Node API: Implement init

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#81]
Part of https://github.com/status-im/nim-waku/issues/78

Acceptance criteria: according to docs https://github.com/status-im/nim-waku/blob/master/docs/api/v2/node.md

**Comment by decanus** [comment]
Btw, I think the signature should probably be changed to

```nim
proc init*(T: type WakuNode, conf: WakuNodeConf): Future[T]
```

That way it is more aligned with nim usage elsewhere @oskarth. I am not sure if `Future[T]` works however.

**Comment by oskarth** [comment]
Wouldn't that assume you've created the WakuNode already?

**Comment by decanus** [comment]
Nope, it means that you init like this:

```nim
WakuNode.init(conf)
```

Means that the init function is scoped under the type.

**Comment by oskarth** [comment]
Ah yes misread, cause of the `type`. Do you want to amend that + docs + example? I'm done coding for the day

**Comment by decanus** [comment]
yeah will do.

**Comment by oskarth** [comment]
Nevermind I can do look at it if it is a quickfix, fixing rebases quickly
