### ISSUE TITLE
WakuMessage index fails to match paging info in store query

### ISSUE THREAD

**Issue by jm-clius** [status-im/nim-waku#813]
## Problem

Using the JSON-RPC API to query for a specific page of historical messages, starting from a specific cursor, will sometimes fail to find a matching starting index of the page, even if it exists in the `store`.

## How to reproduce

1. Start a nim-waku node, configured with any available `--storenode:`, and the JSON-RPC API enabled
2. Use the JSON-RPC API to query for historical messages (method: `get_waku_v2_store_v1_messages`). The initial query will succeed, since no cursor is required yet. The response will be a page of historical messages with a `cursor` pointing to the starting index of the next page of messages. The `cursor` consists of a `digest`, floating precision `receiverTime` and floating precision `senderTime`.
3. Use this cursor as input to a subsequent "next page" query via the JSON-RPC API. In most cases the store node will respond with an empty list. Internal to the store node this is caused by a failure to match the cursor to any message [using the `findIndex` proc](https://github.com/status-im/nim-waku/blob/c422866a4931a636777a947ec2258a783b38519b/waku/v2/protocol/waku_store/waku_store.nim#L273) even though the index does exist.

## Why is this happening?

It happens because the `receiverTime` portion of the message index fails to match that received in the query, even though they "look" the same. This is likely due to floating point precision differences:
1. `receiverTime` is generated using [`epochTime()`](https://nim-lang.org/docs/times.html#epochTime), which has an indeterminate resolution that depends on hardware/OS.
2. In the JSON-RPC response, this floating point timestamp is converted to string in the response and
3. again converted from string when populating the `cursor` part of a historical query.
4. In the process the precision will now be different from the internal representation of `receiverTime` in the `storenode` and the cursor will fail to match the message index.

## How do we fix this?

My proposal:
1. **Minimal solution now**: round `receiverTime` (both when generated _and_ when comparing indices) to 3 decimal places. This implies millisecond resolution, which is more than enough for our purposes.
2. **Longer term solution**: simplify message index to hash the `digest`, `receiverTime` and `senderTime` together into a single, simple hash value that maintains the time order properties we need for indices. Use this value as cursor, which avoids ambiguity due to precision differences.

@staheri14 what do you think?

cc @kaiserd

**Comment by staheri14** [comment]
Thanks @jm-clius  for your comprehensive description of the issue and possible fixes!

I'd suggest using solution one, and additionally, changing the timestamp type to integer (instead of float) with milliseconds resolution. It was something that we had in mind since long ago and now might be a good time to make the change (though no rush)! 
Assuming that the problem is with the type conversion of the time values, then from my pov, solution one is not a minimal solution, it is the exact solution! :)

I do not recommend the second solution i.e., changing the structure of `Index` (it only complicates things ). An immediate problem with that solution is when we want to support more query criteria or change the existing ones e.g, change their types (like in solution 1), then we need to re-compute all the indices because previous hashes become obsolete.

**Comment by staheri14** [comment]
@jm-clius I did not get to replicate the problem, I'll do it and I'll post it here if I find any other causes.

**Comment by jm-clius** [comment]
> @jm-clius I did not get to replicate the problem, I'll do it and I'll post it here if I find any other causes.

It's not always consistent, and may depend on your OS/hardware (which determines how `epochTime()` works). The following snippet of code demonstrates the issue on my machine:

```Nim
import
  std/times,
  strutils

var
  timestamp, convertedTimestamp: float
  printedTimestamp: string
  timestampsMatch: bool

timestamp = epochTime() # Generate timestamp from epochTime()
printedTimestamp = $timestamp # Convert to string
convertedTimestamp = parseFloat(printedTimestamp) # Convert back from string
timestampsMatch = timestamp == convertedTimestamp # Do they still match?

echo "Timestamp before conversion: " & $timestamp
echo "Timestamp after conversion: " & $convertedTimestamp
echo "Timestamps still match:  " & $timestampsMatch
```

This returns the following output on my machine:
```
Timestamp before conversion: 1642152516.283494
Timestamp after conversion: 1642152516.283494
Timestamps still match:  false
```

As you can see, even though the timestamps appear exactly the same, they fail to match when compared. Would be interesting to know if you get a similar result on your machine.

**Comment by kaiserd** [comment]
I could reproduce the error on my system using the snippet @jm-clius provided.
