### ISSUE TITLE
Charging fee in waku-rln-relay

### ISSUE THREAD

**Issue by staheri14** [status-im/nim-waku#840]
# Background
We held a sustainability workshop last year and we came to the conclusion that protocol fees are vital to ensure the sustainability of waku. The simplest mechanism is to capture this directly as a form of commission / non-refundable fee as in ENS, Uniswap protocol fee, Zcash dev fund, etc. This can start off in a simple multi-sig and later be transferred into a DAO mechanism.

## Fee in waku-rln-relay
An immediate use-case of the fee is in the waku-rln-relay protocol in which a portion of users' staked funds can be taken as the fee to use a private spam-protected gossips-sub network. 

This gives a pay-for-use option to platforms that want to use waku-rln-relay for their users. 
This can also be seen as an incentive mechanism for waku operators (where the collected funds are distributed among the operators like in DAOs) 
Providing better incentivization means attracting more platforms/operators/users, therefore getting wider adoption of waku-rln-relay, hence achieving better network robustness, censorship-resistant, and anonymity as well as protocol sustainability.

# Problem
Considering all the said benefits, we need to make sure rln contract supports an option for a fee out of the box which is not the case in the current rln contract. 
Charging fee would not be mandatory rather an option that can be turned on and off. 
The fee percentage can be statically set at the deployment time or dynamically through a contract function call e.g., from some authorized account. 

By this GH issue, we aim to better understand the technical aspects of integration of this feature into the rln contract and to make sure provisions are made to support this capability. 

cc: @oskarth

**Comment by bdim1** [comment]
I think this is a great idea, and incentives and fee mechanisms are certainly an important part of many protocols when sustainability is considered. 
Regarding the actual fee implementation, I think it is very much straight forward and can be easily implemented into the existing RLN contracts. Based on this usecase the model would be very similar to how fees are implemented on the Uniswapv2 platform. Having an admin functions for turning on/off fee, setting a fee recipient, etc would be quite helpful too.

In broader terms I think abstracting the fee component away makes more sense, i.e not making it mandatory and hardcoded in a certain way. For example we can have an abstract RLN contract with a chargeFee(...) function. Then contract implementations can inherit the abstract RLN contract and implement the chargeFee function as they see fit for their protocol (i.e change params, do different types of math formulas, etc). This is not an exact suggestion but just thoughts for having a modular architecture which adds optionality and allows many use cases.

Obviously there are many ways in how this could be implemented. My suggestion would be an abstract contract or maybe not abstract but with virtual functions that can be implemented by concrete implementations later.

Having an option to charge protocol fee is a great feature, and I support your idea.

**Comment by staheri14** [comment]
Closing this issue and moving the discussion to https://github.com/vacp2p/rfc/issues/485
