### ISSUE TITLE
`nim-waku` nodes run out of memory

### ISSUE THREAD

**Issue by jm-clius** [status-im/nim-waku#841]
Since #818 was deployed, nim-waku nodes in the `prod` fleet seems to run out of memory once every 30-40 hours. More details reported in https://github.com/status-im/infra-nim-waku/issues/36

This does not seem to affect the `test` fleet, likely because of a much lower message rate.

**Comment by jm-clius** [comment]
Right, no luck yet.

I've been running v0.6 and v0.7 node locally to compare the virtual and resident memory usage. Both nodes underwent the exact same scenario:
1. both nodes are simple relay-store nodes with store capacity set at 50k
2. both nodes started with no p2p connections and at the same message rate
3. at around 2500 seconds the message rate increased
4. at around 3500 seconds 1 peer connected to each node
5. at around 3750 seconds each node received a store query
6. at around 5800 seconds each node was connected to 50 more relay nodes

So far there has been no degradation visible in memory usage from v0.7. In fact, it has performed better than v0.6 throughout, especially where store queries are serviced (which results in huge memory steps in v0.6). Graphs below:

### Release v0.6 (no apparent memory leak on fleet)

![image](https://user-images.githubusercontent.com/68783915/152014722-550479b9-1a8a-4367-ab58-ab75f0422659.png)

### Release v0.7 (apparent memory leak on fleet)

![image](https://user-images.githubusercontent.com/68783915/152015014-bb897ef7-147b-4dae-9fc5-c1220c92df37.png)

**Comment by jakubgs** [comment]
Could our limiting of container memory be the issue? We cap container memory 60%:
```yaml
# resource limits, mem in MB
nim_waku_cpu_limit: 0.60
nim_waku_mem_limit: '{{ (ansible_memtotal_mb * 0.6) | int }}'
nim_waku_cpu_reserve: 0.20
nim_waku_mem_reserve: '{{ (ansible_memtotal_mb * 0.2) | int }}'
```
https://github.com/status-im/infra-nim-waku/blob/0236ab3a/ansible/roles/nim-waku/defaults/main.yml#L43-L47

Which in practice means values like this:
```
 > a all -a 'grep -A2 limits /docker/nim-waku-v2/docker-compose.yml'
node-01.do-ams3.wakuv2.prod | CHANGED | rc=0 >>
        limits:
          cpus: '0.6'
          memory: '588M'
node-01.ac-cn-hongkong-c.wakuv2.prod | CHANGED | rc=0 >>
        limits:
          cpus: '0.6'
          memory: '585M'
node-01.gc-us-central1-a.wakuv2.prod | CHANGED | rc=0 >>
        limits:
          cpus: '0.6'
          memory: '1006M'
```
Not sure if that's relevant, but may be, since once it hits that limit it starts SWAPing, which can be seen clearly here:

![image](https://user-images.githubusercontent.com/2212681/152036801-fe8237c9-60a8-40d6-bd45-03de7c933ec2.png)

In here we see memory usage of node on host `node-01.gc-us-central1-a.wakuv2.prod` hover under its limit, but SWAP usage growing until it hits max available. Seems to me like the issue is more SWAP related.

**Comment by jm-clius** [comment]
Thanks, Jakub. Yes, I think indeed it is a combination of underdimensioning and inefficient store queries.

### Summary of findings:

See below the memory usage stats of running a local nwaku node with `store` capabilities at a constant message rate.

![image](https://user-images.githubusercontent.com/68783915/152324064-94cd7bbf-57ba-4028-9cdb-792a8e8aa687.png)

- The memory (both occupied heap and RSS allocated to the process) grows steadily as the node processes and stores more messages. This is expected.
- At point A the store reaches its capacity of 50k stored historical messages. At this point the occupied memory and allocated RSS reaches a steady state with regular garbage collection visible in the heap. Note that on a local setup with average message sizes, this already requires > 400MB of memory, which would be at the limit of what many of the fleet nodes have a available.
- At point B a single store query is sent to the node. This results in a sharp increase in heap use, because of [known inefficiencies during store queries](https://forum.vac.dev/t/timestamping-and-indexing-in-the-wakustore/118).  The allocated RSS increase correspondingly (to over 1 GB!). Even though the allocated heap eventually gets released, the allocated rss does not get released back to the OS (this is generally expected, as far as I can determine).
- At point C, another store query results in another increase in the rss.

### Conclusions

- Although this shows no evidence of a memory leak, it indicates that our store nodes are not dimensioned to deal with the steady state required to maintain the stored set of historical messages and certainly not to deal with the overhead currently required to service store queries.
- A single store query resulted in a three fold increase in memory usage - this is because we still need to both sort and filter the entire history for every query. Full discussion recorded here: https://forum.vac.dev/t/timestamping-and-indexing-in-the-wakustore/118. The fleet nodes service much more than a single store query at a time, so it's not surprising that they'll be out of memory and into a swap cycle very quickly.


### What next?

- Temporary alleviation by:
a) shrinking the size of the historical message store on each fleet node (I think setting the  number of stored messages to a max of 10k will buy us some time).
b) raising the available memory limits for the fleet nodes

- Longer term solution:
a) fix the store as discussed in [this forum post](https://forum.vac.dev/t/timestamping-and-indexing-in-the-wakustore/118). An issue has already been created, here: https://github.com/status-im/nim-waku/issues/838
b) be more selective about what we store by implementing a "do not store" flag: https://github.com/vacp2p/rfc/issues/441. Most of what we currently store are regular ping messages coming from js and go clients.

**Comment by jakubgs** [comment]
Thanks for investigating, we can go with lowering the store capacity for now, but I can also increase host sizes for prod.

Although at the same time I do not want our nodes to become a centralized service, and the more resources they have the more than can handle and more people will end up using them. But bumping them to reach 2GB-ish should be fine.

**Comment by jakubgs** [comment]
I've bumped 2 out of 3 hosts to 2 GB(the other one already had more): https://github.com/status-im/infra-nim-waku/commit/935b00d2

I also bumped the container limits to 70%: https://github.com/status-im/infra-nim-waku/commit/71982b78

**Comment by jakubgs** [comment]
Nope, the pattern is still there:

![image](https://user-images.githubusercontent.com/2212681/152766294-87575ce4-f130-40d7-a386-59730f48c1a3.png)

It just takes longer for the container to explode.

**Comment by jm-clius** [comment]
Tracking longer term solution here: https://github.com/status-im/nim-waku/issues/838
