### ISSUE TITLE
Waku v2 Node API: Unsubscribe from content filter

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#85]
# Problem

Currently there is no way to unsubscribe from a content filter.

This may require changes to the filter spec.

# Acceptance criteria

According to docs https://github.com/status-im/nim-waku/blob/master/docs/api/v2/node.md

No longer receive messages on content topic.

# Related
 - https://github.com/vacp2p/specs/issues/206

**Comment by oskarth** [comment]
@decanus is this possible with the current filter protocol or would this require a spec change? Not obvious to me how this would be done.

**Comment by decanus** [comment]
Not possible right now, would require a spec change.

**Comment by oskarth** [comment]
@jm-clius can this be closed?
