### ISSUE TITLE
RPC Debug API call that returns version and commit

### ISSUE THREAD

**Issue by jakubgs** [status-im/nim-waku#859]
For debugging purposes it's very useful to be able to verify the current running version of Node via the JSON RPC API.

Something like:
```
 > ./rpc.sh get_waku_v2_debug_v1_version
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "version": "0.1.0-beta",
    "commit": "1234abcd"
  }
}
```
Or possibly just extend the info returned by `get_waku_v2_debug_v1_info`?

**Comment by jm-clius** [comment]
Good idea. Thanks.

**Comment by jakubgs** [comment]
I've made a PR that adds commit to Docker images as a label: https://github.com/status-im/nim-waku/pull/860

**Comment by jakubgs** [comment]
Looks like we are getting nothing on `wakuv2.test`:
```
admin@node-01.do-ams3.wakuv2.test:~ % /docker/nim-waku-v2/rpc.sh get_waku_v2_debug_v1_version
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": "n/a"
}
```
