### ISSUE TITLE
Drop or limit cardinality of waku_node_messages_total metric

### ISSUE THREAD

**Issue by jakubgs** [status-im/nim-waku#890]
Currently the `waku_node_messages_total` metric appears to use topics as labels:
```
admin@node-01.do-ams3.status.prod:~ % c localhost:8008/metrics | grep '^waku_node_messages_total' | wc -l
1102
admin@node-01.do-ams3.status.prod:~ % c localhost:8008/metrics | grep '^waku_node_messages_total' | head -n2
waku_node_messages_total{type="relay",contentTopic="/waku/1/0x19d2ea3d/rfc26"} 91.0
waku_node_messages_total{type="relay",contentTopic="/waku/1/0xa0204a26/rfc26"} 34.0
```
This is not sustainable as Prometheus is NOT designed to handle high cardinality data. If you put strings without sane limits(100-200) on number of possible values you will cripple ability to query metrics by creating too many time series for Prometheus to handle.

* https://prometheus.io/docs/practices/naming/#labels
* https://www.robustperception.io/cardinality-is-key
* https://stackoverflow.com/questions/46373442/how-dangerous-are-high-cardinality-labels-in-prometheus

For now I've disabled collecting of `waku_node_messages_total` in our Prometheus configuration(https://github.com/status-im/infra-hq/commit/3406a3f6).

**Comment by jakubgs** [comment]
Unfortunately deleting time series from block storage via [Cortex] is currently not implemented yet.
Because of that any high-cardinality data is essentially stuck in our metrics storage and will make all other metrics queries in the same time range slower.

* https://cortexmetrics.io/docs/guides/deleting-series/
* https://aws.amazon.com/blogs/opensource/building-a-series-deletion-api-in-cortex/

Hopefully eventually this functionality will get released, but for now we can't even clean up after scraping such metrics.
For this reason it's important to avoid generating such high-cardinality data in the first place.

**Comment by jm-clius** [comment]
Right, thanks for reporting this, Jakub. Yeah, the bridge causes an explosion in number of content topics so it's a bad idea to have this as a metric dimension. Will fix.

**Comment by jakubgs** [comment]
Oh nice, looks like Cortex mitigated the impact of this because it has a default limit of 100k series per metric :
```
ortex[4168]: level=error ts=2022-03-14T19:01:36.349206791Z caller=push.go:51 org_id=fake traceID=1cb0a42e7655c2b9 msg="push error" err="rpc error: code = Code(400) desc = user=fake: per-metric series limit of 100000 exceeded, please contact administrator to raise it (local limit: 100000 global limit: 0 actual local limit: 100000) for series {__name__=\"waku_node_messages_created\", contentTopic=\"/waku/1/0x7dd468bb/rfc26\", datacenter=\"gc-us-central1-a\", fleet=\"status.prod\", group=\",env:status,stage:prod,nim,waku,metrics,\", instance=\"node-02.gc-us-central1-a.status.prod\", job=\"nim-waku-metrics\", source=\"slave-01.gc-us-central1-a.metrics.hq\", type=\"relay\"}"
```
I should probably lower that limit too...

**Comment by jakubgs** [comment]
Lowered to 30k, might need adjusting later: https://github.com/status-im/infra-hq/commit/10a12ba9
