### ISSUE TITLE
ENR is missing the UDP port

### ISSUE THREAD

**Issue by richard-ramos** [status-im/nim-waku#906]
While attempting to use the status.test fleet for DiscV5, go-waku reported that the ENR was not valid due to missing the UDP port
![image](https://user-images.githubusercontent.com/1106587/159733750-7591d06b-b905-498c-9cd5-e4858f832072.png)

```
bad bootstrap node "enr:-Iu4QNUaBXrXvciIzPUgsPgiqXwA9LZgPE2y6B5VSxKFy0klIeYx8lm0xPH8zRM3OAA5aFSuJnHIwfklc0Tzd_AFMywBgmlkgnY0gmlwhMCoARSJc2VjcDI1NmsxoQKhU8PVgaVNi3-fbU-6OiKWdrYVu2fjCPj2Q30HqbAi_IN0Y3CC6mCFd2FrdTID": missing UDP port
```

**Comment by D4nte** [comment]
So is discv5 executed over UDP only? Both TCP and UDP?

**Comment by kaiserd** [comment]
Discv5 only uses UDP. From the [spec](https://github.com/ethereum/devp2p/blob/master/discv5/discv5-theory.md) :

> For the purposes of this protocol, the node must at least provide an IP address ("ip" or "ip6" key) and UDP port ("udp" key) in order to have it's record relayed in the DHT.

**Comment by jm-clius** [comment]
@kaiserd I think this issue can be closed?

**Comment by jm-clius** [comment]
Closing, as the linked fix has been merged.
