### ISSUE TITLE
Waku v2: PubSub Publish Message not data + Modify Message fields

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#92]
# Problem

Currently in Waku v2 we piggyback on GossipSub/FloodSub publish: https://github.com/status-im/nim-waku/blob/master/waku/protocol/v2/waku_protocol2.nim#L132

This means we are publishing `data` as per RPC spec https://github.com/libp2p/specs/blob/master/pubsub/README.md. See https://github.com/status-im/nim-libp2p/blob/master/libp2p/protocols/pubsub/floodsub.nim#L137 for example message construction.

For Waku, we want to control the message type at a more detailed level. This is important to meet the design goals. See spec for more https://specs.vac.dev/specs/waku/waku-v2.html#protobuf

As a concrete example, we want to add fields to Message protobuf. E.g. see https://github.com/vacp2p/specs/pull/163/files

Additionally:
1. We want to reuse existing architecture in nim-libp2p PubSub protocols
2. We want to use and extend Message type for protocol compatibility
3. We don't want to be blocked by having to upstream message fields etc to nim-libp2p, since this added flexibility could impact e.g. NBC stability

## Possible solutions

A) For changing to publishing Messages:
1. Custom publish fn logic that does things like `sent.add(f.peers[p].send(@[RPCMsg(messages: @[msg])]))`
- this might mean not using procCall for publish calls the same way, as we are changing the signature to deal with Messages 
2. ?

B) For modifying Messages format:
1. We can take existing RPC types (pubsub/rpc/messages) and define these in nim-waku
2. We could create a new WakuMessage type that inherits from message
3. We could upstream optional fields to nim-waku
4. ? Some other clean way of modifying fields

None of these seems super clean to me, curious to hear what an idiomatic solution here would look like.

Curious to see what @dryajov thinks here. Also cc @decanus @zah  

## Acceptance criteria

- Message type is used instead of data field in publish.

**Comment by decanus** [comment]
So after a long discussion with @dryajov, nothing here will work. The fact that we are extending the RPC message may be broken. What @dryajov recommends is adding a DHT where one stores all on their node. What we can also do, is redesign the `Data` field to be an encoded `HistoricQuery`, `HistoricResponse` etc that way we would just decode that message and see what it is.

**Comment by dryajov** [comment]
@oskarth can you elaborate on the use case a bit more? Perhaps there is a way of doing this without modifying the RPC messages themself, which can't be done since it would potentially conflict with future extensions coming from the libp2p spec itself. 

There might also be an alternative architecture (maybe similar to what I've already mentioned to @decanus), where gossipsub can be used, with the other requirements being covered by some other mechanism, like a DHT for example. 

That said, I'll list what gossip can and can't do at the moment:

Can:
- Route messages minimizing message amplification (v1.0)
- Do basic discovery through gossip "bootstrap" nodes (v1.1)
- Message filtering/validation using `validators` (v1.0)
  - failing validation would prevent the message from being propagated further and reaching the application level topic handler, but won't prevent unwanted messages from reaching the node, which might be significant in for light nodes.

Can't:
- Persistence
- Sophisticated discovery

In general, a suitable architecture for a chat application from gossipsub stand point would looks something like this:

- A topic per chat (1:1 or 1:N)
- An external discovery mechanism that allows matching both, peers and messages to a topic
- A storage mechanism that persist historic messages and allows retrieving them based on some search criteria, ie the topic string

**Comment by oskarth** [comment]
Guys, this doesn't sound right to me at all. We are making a new protocol. Protobuf is extensible. The requirements in OP and spec are clear. If they aren't, please ask specific questions. There is precedence (e.g. GossipSub is implementing FloodSub and extending it with Control RPC messages, etc) in the code base.

Can someone explain more explicitly what the perceived blockers are?

If the architecture is truly that inflexible, we can just drop the inherit from Flood/Gossip sub bit and re-use code/logic that makes sense for Waku. That'd be less desirable but it is an option.

**Comment by dryajov** [comment]
> Can someone explain more explicitly what the perceived blockers are?

The biggest issue is tweaking the internals of the gossipsub envelope. The `RPC` and its contents are internals of the family of pubsub protocols that libp2p supports natively, tweaking the `RPC`'s protobuf would mean breaking compatibility with libp2p's pubsub protocols and their extensions.

> we want to support content filtering based on fields such as content topic

What does this mean in practice, ie, how does the mechanism work as of now in waku/whisper?

> We also want to have a basic Query/Response RPC for historical messages.

To me this is outside of the scope of pubsub and I would treat it as a separate protocol altogether. Pubsub is just a router meant to propagate messages with minimum amplification and in this context messages are ephemeral.

**Comment by oskarth** [comment]
> The biggest issue is tweaking the internals of the gossipsub envelope. The RPC and its contents are internals of the family of pubsub protocols that libp2p supports natively, tweaking the RPC's protobuf would mean breaking compatibility with libp2p's pubsub protocols and their extensions.

Fair, so it sounds like we might want to move up https://github.com/vacp2p/specs/issues/167 into track 1 (moving to libp2p).

> What does this mean in practice, ie, how does the mechanism work as of now in waku/whisper?

In Whisper, it doesn't really work. In Waku, they are light nodes (mobile phones) and full nodes.

Light nodes identify as such: https://specs.vac.dev/specs/waku/waku.html#light-node then a full node is one that listens to all topics. The nomenclature is a bit confusing, because the topics in Waku v1 aren't used as PubSub topics, i.e. they are more a form of content message filtering (https://en.wikipedia.org/wiki/Publish%E2%80%93subscribe_pattern#Message_filtering). There is thus no 1:1 mapping with topics in libp2p.

**Comment by oskarth** [comment]
https://github.com/vacp2p/specs/issues/169 and PR https://github.com/vacp2p/specs/pull/170

**Comment by dryajov** [comment]
> > What does this mean in practice, ie, how does the mechanism work as of now in waku/whisper?
>
> In Whisper, it doesn't really work. In Waku, they are light nodes (mobile phones) and full nodes.

OK, thanks that makes sense. I then would further separate the protocols into:

- Gossip (ie gossipsub, etc...)
  - pure message routing/broadcast/multicast/etc...
- Light nodes protocol 
  - passively listen on topics by connecting to full nodes, not part of pubsub
- Historical message retrieval

**Comment by dryajov** [comment]
I added some questions and remarks in https://github.com/vacp2p/specs/issues/169#issuecomment-665784441

**Comment by kdeme** [comment]
I didn't have the time to look into the details of this discussion, so perhaps I'm missing something, but it seems the idea was to reuse some of the internals of GossipSub?

That was not what I had I mind, but rather to have a separate protocol, such as suggested by @dryajov . See also this issue https://github.com/vacp2p/specs/issues/160.

And what was written as first API suggestion.

**Comment by oskarth** [comment]
I believe this issue is outdated since since the protocol split into three https://github.com/vacp2p/specs/issues/169. Thanks everyone for contributing.
