### ISSUE TITLE
websocket connect :Stream EOF

### ISSUE THREAD

**Issue by captZhan** [status-im/nim-waku#935]
what can i do for this?

DBG 2022-04-02 16:03:44.859+08:00 Exception in secure handler during incoming upgrade topics="libp2p muxedupgrade" tid=3941090 file=muxedupgrade.nim:136 msg="Stream EOF!" conn=:624803601a1a61c01846612a
DBG 2022-04-02 16:03:56.072+08:00 Accepted an incoming connection            topics="libp2p switch" tid=3941090 file=switch.nim:198 conn=:6248036c1a1a61c01846612b
DBG 2022-04-02 16:03:56.072+08:00 About to accept incoming connection        topics="libp2p switch" tid=3941090 file=switch.nim:172
DBG 2022-04-02 16:03:56.777+08:00 Exception in secure handler during incoming upgrade topics="libp2p muxedupgrade" tid=3941090 file=muxedupgrade.nim:136 msg="Stream EOF!" conn=:6248036c1a1a61c01846612b
DBG 2022-04-02 16:04:09.597+08:00 Accepted an incoming connection            topics="libp2p switch" tid=3941090 file=switch.nim:198 conn=:624803791a1a61c01846612c
DBG 2022-04-02 16:04:09.598+08:00 About to accept incoming connection        topics="libp2p switch" tid=3941090 file=switch.nim:172
DBG 2022-04-02 16:04:09.936+08:00 Exception in secure handler during incoming upgrade topics="libp2p muxedupgrade" tid=3941090 file=muxedupgrade.nim:136 msg="Stream EOF!" conn=:624803791a1a61c01846612c
DBG 2022-04-02 16:04:20.619+08:00 Accepted an incoming connection            topics="libp2p switch" tid=3941090 file=switch.nim:198 conn=:624803841a1a61c01846612d
DBG 2022-04-02 16:04:20.619+08:00 About to accept incoming connection        topics="libp2p switch" tid=3941090 file=switch.nim:172
DBG 2022-04-02 16:04:20.786+08:00 Exception in secure handler during incoming upgrade topics="libp2p muxedupgrade" tid=3941090 file=muxedupgrade.nim:136 msg="Stream EOF!" conn=:624803841a1a61c01846612d
DBG 2022-04-02 16:04:31.723+08:00 Accepted an incoming connection            topics="libp2p switch" tid=3941090 file=switch.nim:198 conn=:6248038f1a1a61c01846612e
DBG 2022-04-02 16:04:31.723+08:00 About to accept incoming connection        topics="libp2p switch" tid=3941090 file=switch.nim:172
DBG 2022-04-02 16:04:31.893+08:00 Exception in secure handler during incoming upgrade topics="libp2p muxedupgrade" tid=3941090 file=muxedupgrade.nim:136 msg="Stream EOF!" conn=:6248038f1a1a61c01846612e
DBG 2022-04-02 16:04:42.795+08:00 Accepted an incoming connection            topics="libp2p switch" tid=3941090 file=switch.nim:198 conn=:6248039a1a1a61c01846612f
DBG 2022-04-02 16:04:42.795+08:00 About to accept incoming connection        topics="libp2p switch" tid=3941090 file=switch.nim:172
DBG 2022-04-02 16:04:42.901+08:00 Exception in secure handler during incoming upgrade topics="libp2p muxedupgrade" tid=3941090 file=muxedupgrade.nim:136 msg="Stream EOF!" conn=:6248039a1a1a61c01846612f
DBG 2022-04-02 16:04:53.736+08:00 Accepted an incoming connection            topics="libp2p switch" tid=3941090 file=switch.nim:198 conn=:624803a51a1a61c018466130
DBG 2022-04-02 16:04:53.736+08:00 About to accept incoming connection        topics="libp2p switch" tid=3941090 file=switch.nim:172
DBG 2022-04-02 16:04:53.972+08:00 Exception in secure handler during incoming upgrade topics="libp2p muxedupgrade" tid=3941090 file=muxedupgrade.nim:136 msg="Stream EOF!" conn=:624803a51a1a61c018466130
DBG 2022-04-02 16:05:04.649+08:00 Accepted an incoming connection            topics="libp2p switch" tid=3941090 file=switch.nim:198 conn=:624803b01a1a61c018466131
DBG 2022-04-02 16:05:04.649+08:00 About to accept incoming connection        topics="libp2p switch" tid=3941090 file=switch.nim:172
DBG 2022-04-02 16:05:04.712+08:00 Exception in secure handler during incoming upgrade topics="libp2p muxedupgrade" tid=3941090 file=muxedupgrade.nim:136 msg="Stream EOF!" conn=:624803b01a1a61c018466131
DBG 2022-04-02 16:05:15.665+08:00 Accepted an incoming connection            topics="libp2p switch" tid=3941090 file=switch.nim:198 conn=:624803bb1a1a61c018466132
DBG 2022-04-02 16:05:15.665+08:00 About to accept incoming connection        topics="libp2p switch" tid=3941090 file=switch.nim:172
DBG 2022-04-02 16:05:15.822+08:00 Exception in secure handler during incoming upgrade topics="libp2p muxedupgrade" tid=3941090 file=muxedupgrade.nim:136 msg="Stream EOF!" conn=:624803bb1a1a61c018466132
DBG 2022-04-02 16:05:26.633+08:00 Accepted an incoming connection            topics="libp2p switch" tid=3941090 file=switch.nim:198 conn=:624803c61a1a61c018466133
DBG 2022-04-02 16:05:26.633+08:00 About to accept incoming connection        topics="libp2p switch" tid=3941090 file=switch.nim:172
DBG 2022-04-02 16:05:26.719+08:00 Exception in secure handler during incoming upgrade topics="libp2p muxedupgrade" tid=3941090 file=muxedupgrade.nim:136 msg="Stream EOF!" conn=:624803c61a1a61c018466133
DBG 2022-04-02 16:05:37.670+08:00 Accepted an incoming connection            topics="libp2p switch" tid=3941090 file=switch.nim:198 conn=:624803d11a1a61c018466134

**Comment by jm-clius** [comment]
Hi @captZhan. Will be happy to help. Somehow the byte stream setting up the websocket connection fails to parse correctly. I've done a quick sanity check on our side and am failing to reproduce. Can you perhaps tell us a bit more about your setup, e.g. what type of waku clients are you running, are you connecting to any existing fleets and how are you setting up the websocket connection?

**Comment by captZhan** [comment]
I'm sorry to reply so late. I use the latest master branch code,and use ' ./build/wakunode2 --relay  --rpc --metrics-server --websocket-support --websocket-port=8004' to start.  and use websockify proxy port . ' websockify  --cert=/data/ssl/6230882__wsunion.cn.pem  --key=/data/ssl/6230882__wsunion.cn.key  0.0.0.0:8000 127.0.0.1:60000--log-file=./websockify.log' .  then use js-waku method  to connect .
waku = await Waku.create({
        bootstrap: {
          peers: [
            '/dns4/nim.wsunion.cn/tcp/8000/wss/p2p/16Uiu2HAmKxRxcySM9bejw73z4Gz25eF9FhTdw6Ufyw3vfHV97ur5',
          ],
        },
      });
Maybe I missed something?

**Comment by jm-clius** [comment]
With the introduction of native websocket support in `nim-waku` you don't have to use `websockify` at all. You can directly set your key and certificate on the `nim-waku` node using the `--websocket-secure-key-path:` and `--websocket-secure-cert-path:` options. More details here: https://github.com/status-im/nim-waku/tree/master/waku/v2#enabling-websocket

You can also set a dns4 domain name for your node matching the domain in the certificate, using `--dns4-domain-name:`:
https://github.com/status-im/nim-waku/tree/master/waku/v2#configuring-a-domain-name

After the above, you can directly connect to the configured websocket address on the `nim-waku` node from js-waku without using websockify.

If for some reason you still want to use `websockify` rather than native websockets, you should not enable or configure `websocket` for `wakunode2` but instead use websockify to bridge to your node's configured "plain" TCP port. This port can be configured using `--tcp-port` on the `nim-waku` node, but defaults to `60000`. It seems like you have set up your websockify to this port already, but the `websocket` logs will hopefully disappear if you don't enable `websocket-support` on the `wakunode2`.

Hope this helps somewhat! Let me know how it goes.

**Comment by captZhan** [comment]
After I set the certificate of the node, I use js-waku connection but have something exception 

`./build/wakunode2 --websocket-secure-support=true --websocket-secure-key-path="/usr/local/nim-v2/ssl_dir/key.pem" --websocket-secure-cert-path="/usr/local/nim-v2/ssl_dir/cert.pem" --websocket-port=8004 --tcp-port=8000
DBG 2022-04-07 10:19:30.733+08:00 1/7 Setting up storage                     topics="wakunode.setup" tid=159153 file=wakunode2.nim:1307
DBG 2022-04-07 10:19:30.733+08:00 2/7 Retrieve dynamic bootstrap nodes       topics="wakunode.setup" tid=159153 file=wakunode2.nim:1320
ERR 2022-04-07 10:19:30.733+08:00 2/7 Retrieving dynamic bootstrap nodes failed. Continuing without dynamic bootstrap nodes. topics="wakunode.setup" tid=159153 file=wakunode2.nim:1325
DBG 2022-04-07 10:19:30.733+08:00 3/7 Initializing node                      topics="wakunode.setup" tid=159153 file=wakunode2.nim:1329
DBG 2022-04-07 10:19:34.736+08:00 UPnP                                       topics="nat" tid=159153 file=nat.nim:67 msg="Internet Gateway Device not found. Giving up."
DBG 2022-04-07 10:19:38.488+08:00 NAT-PMP                                    topics="nat" tid=159153 file=nat.nim:91 msg="the gateway does not support nat-pmp"
INF 2022-04-07 10:19:38.492+08:00 Initializing networking                    topics="wakunode.setup" tid=159153 file=wakunode2.nim:236 addrs="@[/ip4/0.0.0.0/tcp/8000, /ip4/0.0.0.0/tcp/8004/wss]"
DBG 2022-04-07 10:19:38.493+08:00 creating new PeerManager                   topics="wakunode.setup" tid=159153 file=peer_manager.nim:127
DBG 2022-04-07 10:19:38.494+08:00 no peer storage found                      topics="wakunode.setup" tid=159153 file=peer_manager.nim:139
DBG 2022-04-07 10:19:38.494+08:00 4/7 Mounting protocols                     topics="wakunode.setup" tid=159153 file=wakunode2.nim:1339
DBG 2022-04-07 10:19:38.494+08:00 initWakuRelay                              topics="wakurelay" tid=159153 file=waku_relay.nim:48
DBG 2022-04-07 10:19:38.494+08:00 init WakuRelay                             topics="wakurelay" tid=159153 file=waku_relay.nim:25
DBG 2022-04-07 10:19:38.494+08:00 init WakuRelay                             topics="wakurelay" tid=159153 file=waku_relay.nim:25
INF 2022-04-07 10:19:38.494+08:00 mounting relay                             topics="wakunode" tid=159153 file=wakunode2.nim:702 relayMessages=true
INF 2022-04-07 10:19:38.494+08:00 relay mounted successfully                 topics="wakunode" tid=159153 file=wakunode2.nim:723
INF 2022-04-07 10:19:38.494+08:00 mounting libp2p ping protocol              topics="wakunode" tid=159153 file=wakunode2.nim:742
INF 2022-04-07 10:19:38.494+08:00 mounting swap                              topics="wakunode" tid=159153 file=wakunode2.nim:475 mode=Soft
INF 2022-04-07 10:19:38.494+08:00 wakuSwap init 2                            topics="wakunode" tid=159153 file=waku_swap.nim:284
INF 2022-04-07 10:19:38.494+08:00 wakuSwap init 1                            topics="wakuswap" tid=159153 file=waku_swap.nim:216
INF 2022-04-07 10:19:38.494+08:00 mounting store                             topics="wakunode" tid=159153 file=wakunode2.nim:482
DBG 2022-04-07 10:19:38.494+08:00 mounting store with swap                   topics="wakunode" tid=159153 file=wakunode2.nim:488
DBG 2022-04-07 10:19:38.494+08:00 init                                       topics="wakunode" tid=159153 file=waku_store.nim:386
DBG 2022-04-07 10:19:38.494+08:00 5/7 Starting node and mounted protocols    topics="wakunode.setup" tid=159153 file=wakunode2.nim:1346
DBG 2022-04-07 10:19:38.494+08:00 About to accept incoming connection        topics="libp2p switch" tid=159153 file=switch.nim:172
DBG 2022-04-07 10:19:38.494+08:00 About to accept incoming connection        topics="libp2p switch" tid=159153 file=switch.nim:172
DBG 2022-04-07 10:19:38.494+08:00 Started libp2p node                        topics="libp2p switch" tid=159153 file=switch.nim:268 peer="(peerId: \"16Uiu2HAmGKwNPJPZM7neRPjLcm8f5Yx13Z9iMmhwoKJxXxm28nHK\", addrs: @[\"/ip4/0.0.0.0/tcp/8000\", \"/ip4/0.0.0.0/tcp/8004/wss\"], protocols: @[\"/ipfs/id/1.0.0\", \"/vac/waku/relay/2.0.0\", \"/ipfs/ping/1.0.0\", \"/vac/waku/swap/2.0.0-beta1\", \"/vac/waku/store/2.0.0-beta4\"], protoVersion: \"ipfs/0.1.0\", agentVersion: \"nim-libp2p/0.0.1\")"
INF 2022-04-07 10:19:38.494+08:00 PeerInfo                                   topics="wakunode" tid=159153 file=wakunode2.nim:934 peerId=16U*m28nHK addrs="@[/ip4/0.0.0.0/tcp/8000, /ip4/0.0.0.0/tcp/8004/wss]"
INF 2022-04-07 10:19:38.494+08:00 Listening on                               topics="wakunode" tid=159153 file=wakunode2.nim:941 full=[/ip4/0.0.0.0/tcp/8000/p2p/16Uiu2HAmGKwNPJPZM7neRPjLcm8f5Yx13Z9iMmhwoKJxXxm28nHK][/ip4/0.0.0.0/tcp/8004/wss/p2p/16Uiu2HAmGKwNPJPZM7neRPjLcm8f5Yx13Z9iMmhwoKJxXxm28nHK]
INF 2022-04-07 10:19:38.494+08:00 DNS: discoverable ENR                      topics="wakunode" tid=159153 file=wakunode2.nim:942 enr=enr:-KO4QILHd6KfosJtst1rsUoUI0zNIxFzPKCQq47woLGKWSN7AtdITYJpKkSseeuNFSUwD4LNr_fnRhZXSKBaebv3MAsBgmlkgnY0gmlwhAAAAACKbXVsdGlhZGRyc4wACgQAAAAABh9E3gOJc2VjcDI1NmsxoQM2jVdxm3EPSj-nc5kQeshOzpyDM0JtfPW1HhsfQV8KboN0Y3CCH0CFd2FrdTID
INF 2022-04-07 10:19:38.494+08:00 starting relay                             topics="wakunode" tid=159153 file=wakunode2.nim:656
INF 2022-04-07 10:19:38.494+08:00 subscribe                                  topics="wakunode" tid=159153 file=wakunode2.nim:267 topic=/waku/2/default-waku/proto
DBG 2022-04-07 10:19:38.494+08:00 Registering default handler                topics="wakunode" tid=159153 file=wakunode2.nim:288 topic=/waku/2/default-waku/proto
DBG 2022-04-07 10:19:38.494+08:00 subscribe                                  topics="wakurelay" tid=159153 file=waku_relay.nim:63 pubSubTopic=/waku/2/default-waku/proto
INF 2022-04-07 10:19:38.494+08:00 subscribe                                  topics="wakunode" tid=159153 file=wakunode2.nim:267 topic=/waku/2/default-waku/proto
DBG 2022-04-07 10:19:38.494+08:00 start                                      topics="wakurelay" tid=159153 file=waku_relay.nim:89
INF 2022-04-07 10:19:38.494+08:00 relay started successfully                 topics="wakunode" tid=159153 file=wakunode2.nim:676
INF 2022-04-07 10:19:38.494+08:00 Node started successfully                  topics="wakunode" tid=159153 file=wakunode2.nim:950
INF 2022-04-07 10:19:38.494+08:00 Connecting to dynamic bootstrap peers      topics="wakunode.setup" tid=159153 file=wakunode2.nim:1270
INF 2022-04-07 10:19:38.494+08:00 connectToNodes                             topics="wakunode" tid=159153 file=wakunode2.nim:838 len=0
DBG 2022-04-07 10:19:43.495+08:00 6/7 Starting monitoring and external interfaces topics="wakunode.setup" tid=159153 file=wakunode2.nim:1353
INF 2022-04-07 10:19:43.495+08:00 Starting JSON-RPC HTTP server              topics="JSONRPC-HTTP-SERVER" tid=159153 file=httpserver.nim:42 url=http://127.0.0.1:8545
DBG 2022-04-07 10:19:43.495+08:00 Adding API topic handler for existing subscription topics="relay api" tid=159153 file=relay_api.nim:47 topic=/waku/2/default-waku/proto
INF 2022-04-07 10:19:43.495+08:00 subscribe                                  topics="wakunode" tid=159153 file=wakunode2.nim:267 topic=/waku/2/default-waku/proto
DBG 2022-04-07 10:19:43.495+08:00 Registering handler                        topics="wakunode" tid=159153 file=wakunode2.nim:292 topic=/waku/2/default-waku/proto
DBG 2022-04-07 10:19:43.495+08:00 subscribe                                  topics="wakurelay" tid=159153 file=waku_relay.nim:63 pubSubTopic=/waku/2/default-waku/proto
DBG 2022-04-07 10:19:43.495+08:00 MessageCache for topic                     topics="relay api" tid=159153 file=relay_api.nim:52 topic=/waku/2/default-waku/proto
DBG 2022-04-07 10:19:43.495+08:00 HTTP RPC server started                    topics="JSONRPC-HTTP-SERVER" tid=159153 file=httpserver.nim:215
INF 2022-04-07 10:19:43.495+08:00 RPC Server started                         topics="wakunode.setup" tid=159153 file=waku_setup.nim:66 ta=127.0.0.1:8545
DBG 2022-04-07 10:19:43.495+08:00 7/7 Setting up shutdown hooks              topics="wakunode.setup" tid=159153 file=wakunode2.nim:1360
DBG 2022-04-07 10:19:43.495+08:00 Node setup complete                        topics="wakunode.setup" tid=159153 file=wakunode2.nim:1386
DBG 2022-04-07 10:19:54.073+08:00 Accepted an incoming connection            topics="libp2p switch" tid=159153 file=switch.nim:198 conn=:624e4a4ad9e331300a1f284e
DBG 2022-04-07 10:19:54.073+08:00 About to accept incoming connection        topics="libp2p switch" tid=159153 file=switch.nim:172
DBG 2022-04-07 10:19:54.073+08:00 Exception upgrading incoming               topics="libp2p muxedupgrade" tid=159153 file=muxedupgrade.nim:155 exc="MultistreamSelect failed, malformed message"
DBG 2022-04-07 10:21:00.865+08:00 Accepted an incoming connection            topics="libp2p switch" tid=159153 file=switch.nim:198 conn=:624e4a8cd9e331300a1f284f
DBG 2022-04-07 10:21:00.865+08:00 About to accept incoming connection        topics="libp2p switch" tid=159153 file=switch.nim:172
DBG 2022-04-07 10:21:00.865+08:00 Exception upgrading incoming               topics="libp2p muxedupgrade" tid=159153 file=muxedupgrade.nim:155 exc="MultistreamSelect failed, malformed message"
DBG 2022-04-07 10:21:00.935+08:00 Accepted an incoming connection            topics="libp2p switch" tid=159153 file=switch.nim:198 conn=:624e4a8cd9e331300a1f2850
DBG 2022-04-07 10:21:00.935+08:00 About to accept incoming connection        topics="libp2p switch" tid=159153 file=switch.nim:172
DBG 2022-04-07 10:21:00.935+08:00 Exception upgrading incoming               topics="libp2p muxedupgrade" tid=159153 file=muxedupgrade.nim:155 exc="MultistreamSelect failed, malformed message"
DBG 2022-04-07 10:21:01.184+08:00 Accepted an incoming connection            topics="libp2p switch" tid=159153 file=switch.nim:198 conn=:624e4a8dd9e331300a1f2851
`

**Comment by captZhan** [comment]
I use websockify, and now the js-waku connection is successful. Thank you for your answer

**Comment by jm-clius** [comment]
@captZhan glad it's working!
