### ISSUE TITLE
Waku v2 protocol - store: Implement basic `vac/waku/store` protocol

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#99]
Should be mounted onto Waku node and implement basic req/resp RPC.

MAY use a similar req/resp mechanism as `filter` protocol.

Also see https://github.com/status-im/nim-waku/issues/100

~ related spec issue https://github.com/vacp2p/specs/issues/166

**Comment by decanus** [comment]
@oskarth can you link spec issue.

**Comment by oskarth** [comment]
Haven't written one up, but probably something like https://github.com/vacp2p/specs/issues/166 as minimal req/rep, feel free to add/amend

**Comment by oskarth** [comment]
This isn't actually done. It doesn't mount to the node API as per OP.

It should also be hooked up to the Node API `query` method, though this could be a separte issue. This comes before enhancements like https://github.com/status-im/nim-waku/issues/109

**Comment by oskarth** [comment]
Closing as done, @decanus will create follow up issue for mounting, node API etc.
